### ISSUE TITLE
[NPC] Gargantuan Abyssal - Fire Shield

### ISSUE THREAD

**Issue by craberi** [ccshiro/cc-buglist#104]
The spell http://www.wowhead.com/spell=38855/fire-shield#used-by-npc  Works, It's just that the range seems to be a bit off. For example I could stand max melee range on my ret and avoid it.

**Comment by ccnim** [comment]
Possible that it should take into account the model data.

**Comment by Bearmanpig** [comment]
According to the Wowhead comments (http://www.wowhead.com/npc=20898/gargantuan-abyssal#comments) no one was able to outrange the ability, or didn't report it. Everyone talking about the fireshield is implying that you weren't able to outrange it. Some examples from the comments:

"If your group doesn't mind, it may be a good idea to test the range of the fire shield & whether it can be spell stolen or otherwise removed (heroic/non-heroic)"

Response to above comment:

"For range dps - If you stand 5 yards from the mob, you can still dps without getting hit by the fire aura and still get hit by the meteor. Worked for us like a charm just now in heroic."

Suggests outranging it was only something ranged DPS could do.

I didn't find anything else in the internet archive, hope this helps with the needed research.

**Comment by exltus** [comment]
No you cant avoid it. I found one video where is rogue standing really far from mob and is beeing atacked. At 3:16-17 you can even see, that rogue is attacked in stealth when he is surely still too far to melee attack. https://www.youtube.com/watch?v=xb17AVMI1P8#t=187 If you watch this short video closely you will se more reasons, that are showing, that you cant hide to this spell if you are melee dmg. so this whole topic is INVALID

**Comment by exltus** [comment]
I have some new info! TBC melee range is 5 yards [source](http://web.archive.org/web/20080914153005/http://www.wowwiki.com/Melee) and in [this](http://web.archive.org/web/20080916125757/http://www.wowwiki.com/Gargantuan_Abyssal) guide is written this:

> Abyssal's fire shield being about 3-4 yds

So YES it is possible to avoid fire aura damage even you you are melee dps, but you have to stand on max melee dmg range. So it is working correctly and this issue can be closed.

**Comment by Bearmanpig** [comment]
After stating that the range is about 3-4 yards, why doesn't the writer of the guide go on to suggest that the tank should stand out of range of the Fire Shield as well? He explicitly mentions only the casters being out of range.

This leads me to believe that the writer just got the 3-4 yards wrong in the guide, since all other evidence seems to suggest melee isn't able to avoid the AoE.

**Comment by exltus** [comment]
This issue looks impossible to research. Only way is go to retail right now and go to test it. I doubt, that blizzard changed it and how it works on WoD is same as how it worked on TBC. So if anyone have retail acc please test it, and record results.

**Comment by craberi** [comment]
my sub just ended and i really dont wanna renew it, damn should have tested it, oh well

**Comment by ccshiro** [comment]
Will test on retail with @ccnim.
