### ISSUE TITLE
Potion overrides Flasks

### ISSUE THREAD

**Issue by xtrawelt** [ccshiro/cc-buglist#1041]
When you pop an Destruction Potion while having a Blinding or Pure Death Flaks up (not restoration), 
the Flask will be gone. 
Could test the other Flaks, but doesnt happen with Haste Potions.
- you can stack Restoration Flask with Pure Death OR Blinding.

**Comment by xtrawelt** [comment]
related #838

**Comment by Danddelion** [comment]
I also tested a similar thing: Ironshield Potion http://wowwiki.wikia.com/Ironshield_Potion?oldid=1460629 does not stack with Elixir of Major Defense http://wowwiki.wikia.com/Elixir_of_Major_Defense?oldid=1460572 ; wowhead comments from patch 2.1.3 - so after the introduction of the posibility to have only one Battle and one Guardian elixir active at a time - say they should:
"These do stack with Elixir of Major Defense, or for what matter with any kind of Battle + Guardian Elixir(s) combo you may be using."

When i took an Elixir of Major Defense first, then drank Ironshield Potion, Ironshield Potion overwrote the Elixir of Major Defense, however when I took the Ironshield Potion (+2500 armor) first and then the Elixir of Major Defense (+550 armor) i got the "A more powerful spell is already active" error message.

Another combination of items which in my opinion should follow the same principle of stacking but does not (I did not find direct comments about this):
Nightmare Seed http://wowwiki.wikia.com/Nightmare_Seed?oldid=1574988 overwrites the effect of Flask of Fortification http://wowwiki.wikia.com/Flask_of_Fortification?oldid=1468400 (acutally, I tested  it with Flask of Titans which gives 400 hp, not Flask of Fortification which gives +500 hp and 10 defense rating as it was not available to me, but the issue will be present even here in my opinion). Again, when i used Nightmare Seed first (+2000 hp) and the Flask after (+400 hp) i got the error "A more powerful spell is already active".

Heroic Potion http://wowwiki.wikia.com/Heroic_Potion?oldid=1464177 overwrites a Flask of Fortification as well, even if in my view it should not. Again, i do not have evidence about this, but the principle of this stacking seems to be the same to me as in the case of Elixir of Major Defense and Ironshield Potion (Flasks are a type of Elixir http://wowwiki.wikia.com/Flask?oldid=1556825 ).

Additionally, I tested the combination of a buff and one flask - the flask of Distilled Wisdom http://wowwiki.wikia.com/Flask_of_Distilled_Wisdom?oldid=1562200 and Arcane Intelect; in the current state the Flask (gives + 65 intellect) overwrites Arcane Intellect (plus 40  to intellect at the highest rank). 
This sentence from the patch notes of patch 2.1 (the patch that introduced the one Battle Elixir and one Guardian Elixir only rule) makes me think they should stack: "Elixirs now stack in two categories, Battle (Offensive) and Guardian (Defensive) Elixirs. You can only have one of each type of Elixir up at a time. As a result Elixirs now stack with class abilities such as Arcane Intellect." Flasks are a type of Elixir so it should apply to them.
I suppose the same bug would be present even when using Arcane Brilliance instead of Arcane Intellect.

**Comment by Danddelion** [comment]
I found a video with evidence about Flask of Fortification and Nightmare Seed stacking, it even has these two combined with an Ironshield Potion, so the tank in the video has them all three up at the same time:
https://www.youtube.com/watch?v=77ZvVYQEjCk
In the video it is at 2:29 and again at 6:05.
