### ISSUE TITLE
Frost Trap + Slows Stacking Incorrectly

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1111]
![image](https://cloud.githubusercontent.com/assets/13057166/9149084/ecd5d8a4-3d4b-11e5-93aa-39955b3e0756.png)

https://www.youtube.com/watch?v=YRD0p0oV54w&feature=youtu.be&t=2m21s

**Comment by Aasamath** [comment]
https://www.youtube.com/watch?v=9zXiP13WQOM 2:15
rogue he targets has frost trap debuff + crippling poison (might be due to effect having a different slow reduction) 

AHA GOT THEM ALL !
wing clip + concussive shot + frost trap   all at once
https://www.youtube.com/watch?v=9hExikWBzpI at 3:09 precisely
(it's retail btw around 4:00 you can "see" server name in bg chat)

**Comment by YourNewfriend** [comment]
Seems like it was changed in TBC for some reason.
