### ISSUE TITLE
[Druid] - Root's stacking

### ISSUE THREAD

**Issue by Jonssown** [ccshiro/cc-buglist#1126]
Nature's Grasp seems to stack with Entangling Roots.
![wowscrnshot_080815_142720](https://cloud.githubusercontent.com/assets/11741856/9150463/e61bf1ae-3dd9-11e5-8a6a-a48ff8ac55ec.jpg)

**Comment by Klimpb** [comment]
Can confirm, they also doesn't seem to share DR.

**Comment by ccnim** [comment]
This is probably correct but would still like a video of it.

**Comment by Ickler** [comment]
This really doesn't need research, there's no way those should stack and not share DR. From playing several thousand arena matches as druid I can guarantee that. 
If it was like this (DR on Root + Grasp not sharing) you can CC a target for literally ever. 

Example:
10 sec root
5 sec root
2.5 sec root
6 sec clone
3 sec clone
1.5 sec clone
6  sec Bash now it's 6 +3 + 1.5 + 6 seconds since root landed aka new root
Root 10sec
root 5 sec
root 2.5 sec
Clone 6 sec
Clone 3 sec
Clone 1.5 sec
_pop Nature's Grasp go melee range, get hit_ 
Nature's grasp 10 sec
Root 10 sec
Root 5 sec
Root 2.5
Clone 6 sec
Clone 3 sec
Clone 1.5 sec
Bash 6 sec (second time, 63 seconds since last time aka it's off Cooldown)
Root 10 sec (as last time we used bash this is now off DR, so let's go ham)
Root 5 sec
root 2.5 sec
Clone 6 sec 
Clone 3 sec
Clone 1.5 sec 
Nature's Grasp (70+ seconds since last time it's one minute cooldown so it's ready again!)
10 sec
Root 10 sec
Root 5 sec (60+ sec since we used bash aka it's up again :)) 
Clone 6 sec
Clone 3 sec

OK I won't go on :) I feel like I proved my point, in addition you can add in if you at some point gathered combo points on enemy in cat and throw in a 6 second Maim if something fails or a warstomp. But it's an endless CC chain if DR on Entangling roots and Nature's Grasp doesn't share..

Perhaps some of these are subject to luck, on whether you get the 15 or 20 sec DR "ticks".. But at least this is what you can expect from a decent druid if Nature's Grace doesn't share DR.

**Comment by Klimpb** [comment]
https://www.youtube.com/watch?v=_HNqnWD1JBs
@10:09 - 10:36

Seem to share DR

Though Ickler, druids can already CC/root targets forever if they have bear charge

**Comment by Ickler** [comment]
No they can't, you can't reset DR on root with just clone/feral charge. 
So you can essentially just do:

6 sec clone
3 sec clone
1.5 sec clone
10 sec root
5 sec root 
2.5 sec root
6 sec clone
3 sec clone
1.5 sec clone
6 sec bash
10 sec root
5 sec root
2.5 sec root
6 sec clone
3 sec clone
1.5 sec clone
3 sec feral charge  (only 6+3+1.5+3=13.5sec since root DR started) 
How do you suggest you get beyond this point, without Warstomp or pre-combo points for Maim?

**Comment by Klimpb** [comment]
@Ickler 
Feral charge is a 4 second root, which turns into 14,5 sec, you're missing 0,5 and some rng on DR, the 0,5 sec you can easily be fixed by waiting 0,1-0,2s between the cyclones, and I wouldn't really consider a person being free to do what he wish for 2-3 seconds a problem. It's pretty much forever.
