### ISSUE TITLE
Hunter's Mark

### ISSUE THREAD

**Issue by Dailybs** [ccshiro/cc-buglist#117]
Sorry about that but I will tell you something that is not backed up with pics and stuff.I played hunter, its good but hunter's mark says it improves to a max of 440 ap when invested 5 pts in it and I didn't see any difference with or without, I go even further and state that I couldn't sense actual dps boost even with or without hunter's mark while doing range dps, idk guys if it's supposed to be like that but to me 440ap is alot, because I look at my hunter max gear enchanted + gemmed 1100 ap, and I think to myself lol there is no use of this ability!

**Comment by Iliana-sc** [comment]
With a 2.0 speed bow I get 31-34 damage per hit.
440 AP is 31.4 dps, which is about 63 damage per shot using the above bow. With max rank aimed shot up and shooting for a while my damage goes up to 75-78. That's an increase of ~45 damage which is very close to what you would expect since the target dummies have armor.

Conclusion: I don't think this is bugged.

**Comment by Dailybs** [comment]
well maybe I just was in the dark about this, anyway thanks for clearing that up, also as I now continued with testing I began to doubt my post here :) so I guess it's not bugged.
