### ISSUE TITLE
Group waypoint bug after killing a member and wiping

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1220]
We were doing ramparts, we asspulled selected mob (ravener with his 2 dogs) along with the mobs on the right, we managed to kill the dogs and then wiped. he would not follow his patrol route (which he was doing perfectly before the try) and would not do anything until engaged.

steps: 
1. get a party go ramparts and proceed to SS location.
2.asspull, kill dogs
3.wipe
4.come back in
5.hopefuly the mob will be doing the same -- aka nothing --

[mob stuck no dogs](https://cloud.githubusercontent.com/assets/13721369/9156762/896dac88-3ee5-11e5-8a89-f9006ebbe475.png)

**Comment by lynxzor** [comment]
## Seen a movement bug?

Please target the NPC that is bugging, and while the bug is happening, type
".movegens --verbose" in chat (without quotation marks) and take a print screen
of the output and the broken NPC visible in the screenshot. Any movement bug not
including this will be ignored (as we can't really debug them)!

**Comment by ghost** [comment]
@lynxzor you are right, there should have been another SS which i might have lost with the command processed in it. i though i had included it before deleting it.

however, i believe that with the information provided this can be "triggered" again.

Sergio.
