### ISSUE TITLE
Pathing Issue

### ISSUE THREAD

**Issue by InvisibleJon** [ccshiro/cc-buglist#1276]
The mob Master Daellis Dawnstrike got stuck while I fought him, he simply stood in place not attacking me.
He has a bow, but didn't use it, some sort of pathing issue.

Movement bug Screenshot with the ''.movegens --verbose'' command
http://i.imgur.com/OEhHKQk.jpg

Video: http://webmup.com/3701b/

**Comment by Iliana-sc** [comment]
from http://pastebin.com/j6VfjZSG:

## Seen a movement bug?

Please target the NPC that is bugging, and while the bug is happening, type
".movegens --verbose" in chat (without quotation marks) and take a print screen
of the output and the broken NPC visible in the screenshot. Any movement bug not
including this will be ignored (as we can't really debug them)!

**Comment by InvisibleJon** [comment]
Ah damn... I even knew I that, but totally forgot about it... I guess its too late.
I'll try to do it again, thanks for reminding.

**Comment by InvisibleJon** [comment]
http://i.imgur.com/OEhHKQk.jpg

Got it!

**Comment by Peter1337** [comment]
Well, I killed this mob 3 days ago and he attacked me with his bow and behaved normally.
