### ISSUE TITLE
[Mage] Fireball DoT Refreshes Every Shot

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1291]
I don't believe it should refresh itself every time.  Spamming Fireball results in 0 ticks of the spell occurring currently.

Evidence: none yet

**Comment by PantelisK** [comment]
This is how ignite works.
at http://wowwiki.wikia.com/wiki/Ignite_%28old%29 

WoW Patch 2.0.1 (05-Dec-2006):

```
All mages now get their own Ignite stack per target.
```

---->    Ignite now reset the DoT duration when recast.

If you cast fireballs you will get 1 tick of ignite from your first fireball before the 2nd fireball launches and refreshed the dot. If you are spamming scorch though since there wont be 2 seconds gap between casts you might not get any ignite tick

**Comment by shadowraider** [comment]
I think he is talking about the fireball dot, not the ignite.

Fireball dot has 3 secs tick period, fireball cast time (talented, 0 haste) is exactly 3 secs. If you add some milliseconds between the fireball cast times, you should be getting 1 fireball dot tick from fireball right before your next fireball hits the target.

In later content when you are getting some haste (being unable to getting fireball dot), you also get higher bonus dmg so the dot doesn't even matter.

Everything working as intented, I hope.

**Comment by Confined-** [comment]
The fireball dot refreshing on every hit is how it worked on retail.
Watch the dot timer above his cast bar.

> https://youtu.be/eetPTbn-30Y?t=38
