### ISSUE TITLE
Players Can Bind Themselves To A Hearth Location Repeatedly

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1320]
![image](https://cloud.githubusercontent.com/assets/13057166/9215663/839860b8-4062-11e5-930f-a7451b8b6235.png)

http://wowwiki.wikia.com/wiki/WoW_Constants/Errors?oldid=1497785
"ERR_DEATHBINDALREADYBOUND 
You are already bound here!"

**Comment by ccshiro** [comment]
Needs proof that this error was used. (Note: I'm fine with current retail as proof on this.)

**Comment by Shanghi** [comment]
I think that error is for something else. On retail you're able to bind repeatedly:
![wowscrnshot_031016_140556](https://cloud.githubusercontent.com/assets/2672633/13681594/eae897be-e6cb-11e5-8ec3-3a74cb9ead43.jpg)

There's a few more "deathbind" messages, and one has a comment about bindstones:
`DEATHBIND_SUCCESSFUL = "Your soul is bound to this place."; -- Clicked on a bindstone`

Bindstones seem to be some beta version thing where players could respawn after dying. The extra messages just seem leftover and unused now.
[Gamespot article](http://www.gamespot.com/articles/exploring-the-world-of-warcraft/1100-6093288/): "Blizzard added corpse retrieval to the death system because players started abusing the bindstone system. Back then, players could respawn at their bindstone without an experience penalty after dying."
