### ISSUE TITLE
Scripting on Captain Skarloc introduction seems off

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#1330]
Problem: the captain seems to spawn in a bit too close, and needs to be placed a bit further back (see video). The captain dismounts but stops, and turns East for a moment, while still inside of the horse. This is incorrect as on retail, he dismounts and continues to walk forward with no hesitation. Note how also Thrall should not say anything after killing the captain. 
How to reproduce: fight against Captain Skarloc
Solution: modify scripted event
Proof: http://www.twitch.tv/hatefiend/c/7022782
Burning crusade proof: https://youtu.be/w1-zXr6pUFA?t=665 (not burning crusade but event hasn't seemed to have changed)

**Comment by ccshiro** [comment]
Everything seems fine in your video except that he turns after dismounting. It seems to be that he's looking at the rogue...

**Comment by KevinTyrrell** [comment]
In the retail video, do you not see how Skarloc doesn't 'spawn inside' of the horse at any point? In the CC video, this does occur.

**Comment by KevinTyrrell** [comment]
Also note in the retail video, Skarloc gestures once with his hands as an emote. This should be fixed as well.

**Comment by ccshiro** [comment]
@KevinTyrrell As I said, it happens because he notices the rogue after dismounting. That's what causes him to stop there; NPCs stop their patrolling/movement when they spot a rogue and stare at him. The horse has a slight delay from when he dismounts to when it appears, which makes them not occupy the same space, but since he stopped there they now do.
