### ISSUE TITLE
[Heroic] Underbog - Mob not patroling

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#1345]
http://i.imgur.com/p71p4Re.jpg

The bog gigant in the screenshot should patrol but he just stands still right on that spot.

**Comment by Chulain** [comment]
from http://pastebin.com/j6VfjZSG:

## Seen a movement bug?

Please target the NPC that is bugging, and while the bug is happening, type
".movegens --verbose" in chat (without quotation marks) and take a print screen
of the output and the broken NPC visible in the screenshot. Any movement bug not
including this will be ignored (as we can't really debug them)!

**Comment by ccnim** [comment]
That mob doesn't patrol.
