### ISSUE TITLE
Control+run

### ISSUE THREAD

**Issue by ASrozaev** [ccshiro/cc-buglist#1370]
Any control connected with movement _disorientlike_  (canceled/finished/trinketed) cancels running process holding/pressing by player
forcing player to repress/rehold run button

makes pvp process for melee classes completely awful

**Comment by Peonstomperx** [comment]
pretty sure this is client side

**Comment by Sakatoro** [comment]
than Shiro have to write patch 2.4.4 for us :D

**Comment by ASrozaev** [comment]
guys, just check
use numlock and get any control

**Comment by Magnumspb** [comment]
check, working fine. problem on you side

**Comment by ASrozaev** [comment]
I play other server BC, there it works fine

**Comment by nullfoxh** [comment]
Can confirm. Not sure if it happens all the time, but if you hold "w" while being CC'ed then break the CC with PvP trinket, you have to release "w" and press it again if you want to move. Also not client side as this doesn't happen on other pservers (or retail).

**Comment by ASrozaev** [comment]
I tested it many times, each time got the bug

**Comment by Klimpb** [comment]
EDIT: Not sure about this one.

**Comment by Aasamath** [comment]
@killas077  what was the control you took, might vary beewteen fears, stun, roots etc...
autorun isn't reliable, i got stopped on it by a cc that wouldn't stop me when i was holding "Z"; well "W".
I did some pvp duels (thanks again Dark) other player was moving forward and hold the movement key at all time.
Fear: stop the movement at end
sheep: stop the movement at break
seduce: doesn't stop movement at break
frost nova: doesn't stop movement at break
death coil: stop movement at end
shadow fury: doesn't stop movement at end
For this particular player, only cc that would cancel the movement eventhough key was pressed, are controls that make your character move (lose control of your character).
forgot to try mind control -_-
I can't honestly remember if that's normal or not

**Comment by ASrozaev** [comment]
@Aasamath it is not normal at all
 in pvp u need 1-2 more seconds to turn face to your target and repress W

**Comment by Aasamath** [comment]
@killas077 you can also hold down right click while looking where you wanna go, to make that faster, or bind your left/right keys to "strafe" not turn

But if it shouldn't stop movement while holding the key, then when your character gets turned in the opposite direction you want to go, just before cc breaks or you trinket it, you'll end up making a few steps in the wrong direction (that behavior might be noticeable on videos if it was scripted that way on retail)

**Comment by ASrozaev** [comment]
@Aasamath , u propose to adapt to bug, 

rly?

**Comment by Aasamath** [comment]
watch when the rogue filming gets blind and trinket it
https://youtu.be/xF4Rx1sQYQU?t=390 
https://youtu.be/xF4Rx1sQYQU?t=140
this is the kind of weird fuck up that happens to me too when a cc blocks me on an other private.
Because to trinket "loss of control effect" i have to trinket, right click to make my character face the direction i'm looking at, press movement key (then jump); in that order and as quickly as possible.
If the order is wrong or not fast enough, you obtain scenarios like those.
first one: jumped before moving
second one: doesn't start moving immedialy after trinket, you can see his character stopping briefly
(message on video is wrong on second clip if you're wondering, wotf for luls not blind ^^)

But at 2:34 when the stun on him fades, you can see his character moving briefly in the direction it's facing instead of where the camera looks, cause in that case he didn't have to release W but still had to press right mouse button, just after stun fades, to make his character face the same direction as the camera.

**Comment by ASrozaev** [comment]
@aasamath 
delays after trinket u show in this video is not this bug delay

bug delay is longer, I will show u in game

**Comment by ccnim** [comment]
I can turn and move instantly after trinketing, I don't see an issue here.

**Comment by ASrozaev** [comment]
@ccnim , just try to run after control/trinket without repressing W
