### ISSUE TITLE
Intercept range too short

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1399]
Can't 5-8 kite because warriors just jump and intercept me

**Comment by PatchnotesTBC** [comment]
Sure its not just l2p issue? :D

**Comment by Peonstomperx** [comment]
@PatchnotesTBC no, I never make mistakes

Often it happens I'm right behind chasing someone but not able to use abilities, maybe everything is abit shorter than usual because something with movement updates.
It's also possible to outrun pets.

**Comment by killas077** [comment]
I thought that deadzone is 3-7, not 5-8

**Comment by shadowraider** [comment]
test this with a charge spell...... duel someone, step right in front of him on 1 yard range, now walk backwards and wait for charge to become available, now stop, mark the point where you stand with smoker, cooking campfire or just remember it....... now hit your duel enemy and walk backwards again, see if the intercept becomes available on the spot you marked

i think this is just noob issue, since you haven't included any video but only QQ post
