### ISSUE TITLE
Seal of Command & Vengeance

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#14]
Report: "Paladin Retribution talent Vengeance does not proc with Seal of Command Seal criticals. It should proc with all offensive critical strikes from the Paladin skillset."

Vengeance tooltip: "Gives you a X% bonus to Physical and Holy damage you deal for 30 seconds after dealing a critical strike from a weapon swing, spell, or ability. This effect stacks up to 3 times."

Question: is this report accurate? A single video or screenshot where this happens, or indeed a trust-worthy source (such as some elitistjerks threads), would be enough to confirm this.

**Comment by kolchax** [comment]
http://www.wowwiki.com/Patch_1.11.0
http://www.wowwiki.com/Seal_of_Command_(old)

As you can see with patch 1.11.0 "Vengeance: Seal of Command critical hits can now trigger this ability".  The next change to Seal of Command was done in patch 3.0.2 which does not concern you since the server will be running on 2.4.3. 
So to answer the question, Vengeance should proc from Seal of Command crits.

-Kolcha
