### ISSUE TITLE
Underwater breathing visual bug?

### ISSUE THREAD

**Issue by Sinergyy** [ccshiro/cc-buglist#143]
So, in a duel or alliance vs horde fight, if I use Mind Control (as a Priest) on the enemy and go underwater, that person can see the Breating Bar underwater, but I cannot. 

http://i.imgur.com/xNcaWSg.jpg

Here is how I see it. Ain't I supposed to see it? As I am mind-controlling him. 

If you go underwater and your breathing bar is almost used, and I use Mind Control, I'm still not seeing it and the person takes damage. In a duel, this is a thing I want to know and see using Mind Control. 

Best regards,
Sinergyy

**Comment by Bearmanpig** [comment]
I don't think the bar is supposed to appear, since the MC'd target counts as your pet. Your Breath Bar is controlled client side as far as I know and is never shown for pets, only for your own character.

From my own experience (and I've done this a LOT in vanilla and TBC) I never used to get a bar either for my targets. What would happen anyway if you (the caster) and the target are under water at the time of the MC? One bar for yourself and one for your target seems a bit weird.

**Comment by exltus** [comment]
No you don't see breathing bar. I was doing this a lot in AB on retail and breath bar was never there. I found (video)[https://www.youtube.com/watch?v=WN-xySlgzQI#t=152] where are using mind control to drown enemy in lava (I don't remember, if you have breath bar in lava, but i suppose yes) and you don't see any breath bar here.

**Comment by ccshiro** [comment]
@exltus Thanks for the video.
