### ISSUE TITLE
[Shaman] Windfury OH Weapon Damage Not Calculating Correctly

### ISSUE THREAD

**Issue by WCGH** [ccshiro/cc-buglist#145]
After some testing it appears the Windfury damage proccing off offhand weapons is lower than it should be. The AP bonus from WF should not be getting the 50% Dual Wield penalty. Currently it's being calculated as:
(weapon damage + ( ( ( AP + windfury bonus ) / 14 ) \* weapon speed )) \* 0.5
While it should be something like:
weapon damage \* 0.5 + ( ( ( AP + windfury bonus ) / 14 ) \* weapon speed )

This is causing FT and FB offhand imbues to parse much higher than WF/WF, since offhand is eating WF procs with very low output. Here are two sources which specifically mention the AP bonus not being affected by DW penalty:
- http://web.archive.org/web/20080204142249/http://elitistjerks.com/f31/t13297-enhance_shaman_collected_works_theorycraft_vol_i/
- http://web.archive.org/web/20080207011157/http://forums.worldofwarcraft.com/thread.html?topicId=79203452&sid=1

Otherwise the WF ICD, Flametongue and Frostband Weapon all seem to be working fine. Thanks for all your work! If you'd like any additional shaman testing let me know.

**Comment by ghost** [comment]
Further evidence, younger versions of that 2nd thread. Conflicting contradictory posts from retail. Well not really conflicting, just updated, since one is older.
And one should assume the later one to be more correct. Because patch, and more recent finding made it be !changed! when compared to the older thread.

http://web.archive.org/web/20080329010641/http://www.wowblues.com/us/tbc-shaman-faq-79203452.html -> date 28/02/2007
"The two offhand attacks are affected by the standard offhand 50% damage reduction."

http://web.archive.org/web/20080331205134/http://www.wowblues.com/eu/tbc-enhancement-shaman-faq-394130313.html -> date 09/08/2007 -> updated for patch 2.1
"The two offhand attacks are affected by the standard offhand 50% damage reduction. The WF proc's attack power bonus is not."
