### ISSUE TITLE
[Warlock] Healthstone can't crit

### ISSUE THREAD

**Issue by Aasamath** [ccshiro/cc-buglist#1461]
The healing effect of Healthstones should be able to crit. I ate like 15/20 of them by now, with a 30% crit gear. Didn't happen once.
http://wowwiki.wikia.com/wiki/Create_Healthstone
I came accross a good example of it on a clip, gonna try to find it back.
Here are some wotlk comments too.
http://www.wowhead.com/forums&topic=55887/a-little-bit-of-everything

**Comment by Doppelmoral** [comment]
Since you mentioned your crit stats, Healthstones do have the basic crit chance of 5% I presume, same as Potions - impossible to increase said percentage with talents, gear, or similar.

**Comment by ccshiro** [comment]
Confirmed. It calculates your chance to crit with healthstone to 0% at the moment.

**Comment by KimmoKM** [comment]
Healing potions don't seem to crit either. I just used 300 health pots and didn't get a single crit. I don't know where Doppelmoral has got his 5% base crit information from but potions critting is well-documented at least. [This comment](http://www.wowhead.com/item=33447/runic-healing-potion#comments:id=669747:reply=150183) from WotLK (a detail I believe is very unlikely to have been changed, at least deliberately) claims the potion crit chance is based on your spellcrit and I'd suspect HS would work the same, but then again, it's just a comment with no proof. Whether or not mana potions should crit is another question.

Since I just got 7 days of free WOD game time, I'll check how it currently works in retail.

**Comment by KimmoKM** [comment]
[This guide](http://warcraft.securityorg.net/Mana%20consumables-58.htm) mentions Dark Runes can crit while there's no mention of such a thing in regards to mana potions. It doesn't directly say anything either way but I think you can kinda read between the lines and assume there would be a mention of mana potion crits if the author of the guide was aware of such a thing. Either way, to an extent memory is a reliable source, I'm also fairly confident mana potions shouldn't be able to crit (I had a habit of potting the exact moment I missed 3k mana so I was paying attention to my mana when I used pots, and I must have used several thousands).

Thank bjplunk for the link.
