### ISSUE TITLE
[Warrior Class Bug] Heroic Strike and Autohit Bug

### ISSUE THREAD

**Issue by Sakatoro** [ccshiro/cc-buglist#148]
If i use heroic strike (Need 15 rage ) and i my rage drop down under 15 ( before the next autohit) it follow  no heroic strike (right) but also no autohit (bug) 

Normaly if i lose my rage for heroic strike before the next autohit the warrior dont use heroic strike but autohit.

I fraps and uploaded it on YouTube. There you can see what i meen.

https://www.youtube.com/watch?v=PwKndZgEjoc

**Comment by ghost** [comment]
sources it should autohit?

**Comment by Piranhaz** [comment]
Yeah i can confirm this, was wondering in arena why sometimes it felt like no autohit comming...coz there was no autohit.

**Comment by solowt** [comment]
I don't think we need a source for this...It's pretty obvious that it should autohit.

**Comment by FurioCC** [comment]
It should autohit clearly.
If you activated heroic strike, but before next atack happened, had spent range with some instant, like MS, heroic strike stays activated (white border) but dimmed due to not having enough rage, and then when swing timer comes just normal autoatack occurs and heroic strike is deactivates.
If after MS but _before next swing_ you gain enough rage through some way (for example you are being hit) then activated HS undimmmed and instead of normal atack you perform HS.
So in the end, if you activated HS, it's about having enough rage for HS at the moment of the swing - if you do HS happens, if not then normal autohit.

**Comment by Piranhaz** [comment]
Rulerx lol, when u need a source for THIS u better don't "help" bugtesting because it makes u look like u got no idea of this game.

**Comment by ghost** [comment]
Are you claiming that you remember how the game should be from 10 years ago?

**Comment by solowt** [comment]
Yes?

Heroic strike replaces an autoattack.  It's an on-next-attack ability that you queue up that adds damage to your next attack.  You don't lose that attack if your rage drops below a certain level between pressing the button and your swing timer finishing, you just don't cast heroic strike and get a normal white hit instead.

There is no other way it could possibly work.  This is clearly a bug.  You're not helping anyone by arguing about it.

**Comment by ghost** [comment]
if there's no other way it could possibly work, then it should be very easy to find evidence (from vanilla) of that being so.

**Comment by solowt** [comment]
If this report gets tagged as "needs research" then I'd be glad to go look for a video.  But it won't, because we all know how this mechanic worked.

Please stop trolling.
