### ISSUE TITLE
Movement and skill lag 

### ISSUE THREAD

**Issue by Sakatoro** [ccshiro/cc-buglist#149]
Got realy problems with the movement system and also delay with skills. 

Example: Iam standing behind a other player and try to hit them but the system told me "not in range".

Or i charged someone and he port oneself 5meters. Or a druid start to cast a cyclone to me and after 50% of the cast i get the cc, but for my visual Display the cast was not finish, it happen realy realy often.

My ping was around 50-55 and fps ~60. Tryed other privat Servers (ping 30-50) and the laggs was gone, go back to corecraft and got the movement lags again.

**Comment by ShuTestCC** [comment]
Not sure if this is related, but as a caster I sometimes noticed spell casting delays (delay before the cast began) despite having a stable, low latency. This does not happen on other servers I play on. I need to do more testing on this today.

**Comment by jessyo** [comment]
I experience this issue aswell. I have a stable 30-40ms latency.

As far as I can recall, the delay on spells is legit as it's the way it was on retail and it is good to have it here. Although I can't remember if it was this huge.

The issue is that, for example as a melee (I play rogue mostly), I have trouble hitting other players, despite being in melee range when they're trying to get away. I'm like spamming my abilities but nothing happens even though I'm in the 5 meters range.

**Comment by ShuTestCC** [comment]
Sorry Jessyo if I wasn't clear enough. I'm talking about a delay before the character starts casting, much like lag, but not from my side.
I am aware that there should be a delay before a spell impact actually causes damage and it is well implemented.

**Comment by Stoney21** [comment]
I blocked Death Coil with my IB and and cancelled it right away and I still got full Death Coil for some reason. This delay was weird.

**Comment by Klimpb** [comment]
During half of the test or so they had some issues causing you to experience a lot of extra lagg which many people seem to think was the implemented "spell delay", which is not the case. 

I'd suggest you to try these things again on the next test.

**Comment by ccshiro** [comment]
What @SuddenDeath said.
