### ISSUE TITLE
Ramparts vazruden the herald yields rep on each kill in same instance id 

### ISSUE THREAD

**Issue by ConfusedCC** [ccshiro/cc-buglist#1540]
an exploit used to farm thrallmar and honor hold rep might work on the test server
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/12591-easy-war-farm-thrallmar-exalted.html

have only tested on normal difficulty but its possible there to kill the orc then reset the encounter by running out/in and killing him again

![wowscrnshot_082915_151425](https://cloud.githubusercontent.com/assets/10581981/9562071/6c4fe8e2-4e61-11e5-9034-de9ed52e3511.jpg)

**Comment by petaal** [comment]
We tried to abuse this on heroic ramparts, but killing Vazruden gives no rep. While Vazruden was dead, running outside and back inside reset the whole event. 

After we killed the dragon, we got the rep although Vazruden was still alive. Dunno if this is a problem because it was pretty difficult to stay alive while both of them were attacking. We didn't try running outside after killing the dragon and Vazruden alive to see if the encounter resets.
