### ISSUE TITLE
[Mage] Arcane Blast debuff applies to slowly

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1543]
When casting Arcane Blast, if you immediately cast after casting the initial one - your next cast will still be 2.5 seconds (debuff applies too slowly). 

Easy to reproduce:
- Level 70 mage
- Get Arcane Blast
- Spam this very quickly, and watch how debuff doesn't apply before your next cast begins

**Comment by Confined-** [comment]
While I wasn't able to check this before the fix went through, it sounds as though this was not a bug and was actually working as it did on retail. The debuff granted as the cast completes should not apply the cast time reduction but should apply the mana cost penalty.

An example cast sequence with the number in parenthesis denoting the debuff stack applied to the spell.

Arcane Blast(0)
Arcane Blast(0) Mana cost of (1)
Arcane Blast(1) Mana Cost of (2)
Arcane Blast(2) Mana Cost of (3)
Arcane Blast(3)

Some posts from EJ mentioning this mechanic:

[That's 9sec, because unless you're rotating AB-filler-AB-filler, you'll do a 2.5-2.5-2.2-1.8-1.5 AB cycle rather than 2.5-2.2-1.8-1.5 cycle.](http://forums.elitistjerks.com/forums/topic/18293-sweet-informational-thread/?page=33#comment-716004)

[The reason people are saying do AB-> FB -> AB -> FB is essentially that if you do AB spam, there is a slight delay between when the spell hits and when the debuff stacks. So what happens is you have to pay extra mana on the next AB spellcast, but you DONT get the extra increase in speed, if you throw a frostbolt in between AB casts while you are trying to apply stacks, this doesnt happen anymore.](http://forums.elitistjerks.com/forums/topic/18293-sweet-informational-thread/?page=27#comment-692601)
