### ISSUE TITLE
Abolish Poison / Abolish Disease

### ISSUE THREAD

**Issue by petaal** [ccshiro/cc-buglist#1576]
If the target is not poisoned, Abolish Poison removes itself after the first tick, that is 2s after casting it. Same thing happens for Abolish Disease after 5s. If the target is poisoned, the poison is cured and the buff stays until the next tick. Not sure if this should be working this way, seems strange at least.

Couldn't really find definite proof by watching druid pvp videos or by googling. However, found the same bug reported in Trinity Core github.

**Comment by Doppelmoral** [comment]
Tooltip is quite clear about that:
_Attempts to cure 1 poison effect on the target, and 1 more poison effect every 2 seconds <b>for 8 sec.</b>_
_Attempts to cure 1 disease effect on the target, and 1 more disease effect every 5 seconds <b>for 20 sec.</b>_

Means it lasts a set duration and does not cancel prematurely after "unsuccessful" ticks..

**Comment by Doppelmoral** [comment]
Check #873 

https://github.com/ccshiro/cc-buglist/issues/873#issuecomment-121565989

_"I have no idea how you implemented it, but if you did basicly the same I did please recheck it for triggered spells, otherwise it will remove Ambolish Poisons on first tick if there is nothing to dispel."_

Looks like you used some external code from someone who foresaw this interference.

**Comment by ccshiro** [comment]
> Looks like you used some external code from someone who foresaw this interference.

No, I did not use his code, nor did I see his follow up comment. We had implemented it in a fairly similar approach, and had managed to create the same bug, however.

**Comment by Doppelmoral** [comment]
Just trying to help.
