### ISSUE TITLE
A Letter To Yvette drops all the time even if you already completed the Q

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1652]
First of all, it should have really low chance to drop, according to wowhead comments:
http://www.wowhead.com/item=2839/a-letter-to-yvette
At the moment it drops with 100% chance off every mob in Agamand Mills.
Second, it keeps dropping if you accepted the quest, it keeps dropping if you accepted the quest and already have another item in your bags, it keeps dropping after you completed the quest ages ago...
It just keeps dropping again and again.
That Thurman spent the end of his life writting tons of these letters it seems xD

![wowscrnshot_090515_205849](https://cloud.githubusercontent.com/assets/5777848/9701287/e2e4299a-542a-11e5-8374-552ff80ca10e.jpg)

**Comment by Sleekcrush** [comment]
Can confirm. Some of my notes I wrote when doing this quest, might as well add them since there is already a listed issue.

o   (http://www.wowhead.com/item=2839/a-letter-to-yvette#comments) (even though it is mostly 3.3.5 comments)
o   (http://db.valkyrie-wow.org/?item=2839) (another private server, not sure of accuracy)
o   (https://vanilla-twinhead.twinstar.cz/?item=2839) (another private server, not sure of accuracy)
o   (http://db.vanillagaming.org/?npc=1520) (On the other hand, says otherwise with a 100%                                   droprate).

**Comment by netherspite** [comment]
I highly doubt Blizzard would greatly reduce droprate for WotLK so I think we can trust wowhead comments.
