### ISSUE TITLE
Mobs not linked together [Blade's Edge Mountains]

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1754]
For the quest "The Trappings of a Vindicator" and follow-up quest "Gorr'Dim, Your Time Has Come..." one has to kill 3 NPCs in total which are located in 3 big huts of ogres and are surrounded by 2 non-elite and 2 elite-mobs. 
In all mob groups i noticed that you can pull (at level 70) one mob at the time and kill them easily. screenshots added 

![wowscrnshot_091115_125453](https://cloud.githubusercontent.com/assets/12044027/9813573/01f851e8-5887-11e5-93be-e244af8b481a.jpg)
![wowscrnshot_091115_125519](https://cloud.githubusercontent.com/assets/12044027/9813575/03a98264-5887-11e5-87bd-0fbffd159129.jpg)
![wowscrnshot_091115_125604](https://cloud.githubusercontent.com/assets/12044027/9813576/04d728f8-5887-11e5-9c39-c31355cce8f6.jpg)

**Comment by DeeMarie** [comment]
According to Wowhead comments this was how it worked on live:

http://www.wowhead.com/quest=10516/the-trappings-of-a-vindicator

"By Seiki (354 – 1·4) on 2006/12/31 (Patch 2.0.1)  
Actually, you don't even need the brew. The named ogres will pull solo without the guards, even though that seems highly unlikely."

"Jormundgand on 2007/12/15 (Patch 2.3.0)
I didn't need to put the brew down at all on Mugdorg. I just stood directly in front of the named ogre and pulled him. The elites didn't care, and I looted my quest item nice and easy. However, when I did the same on Droggam, the guards came with him, I don't know what caused it."

"By grizman (197 – 1·1) on 2007/03/05 (Patch 2.0.8)  
39, 53 - droggam
41, 58 - mugdog

you dont need to use anything.... just kill the first guy on each side, then pull down the middle. Droggam is a caster, so you need to back up quite a bit before you can attack him to not agro the elites. easy as that "

It's possible they solo pull because you're meant to lure them with the Bloodmaul Brew while the two sober elites ignore it.
