### ISSUE TITLE
Gnarlpine Vengeance ability cast on player

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1761]
Some of the Gnarlpine furbolgs ([Augurs](http://www.wowhead.com/npc=2011/gnarlpine-augur), possibly some other mobs as well) in Teldrassil have an ability called [Gnarlpine Vengeance](http://www.wowhead.com/spell=5628/gnarlpine-vengeance). I can't find how precisely the ability should be used (comments concerning Augurs seem to suggest it probably wasn't used as intended in retail either), but I think it's quite clear mobs shouldn't be buffing the player.

**Comment by Zindai** [comment]
I was able to find one walkthrough from before Cataclysm, [here](https://youtu.be/XPCmIWXUQmY?t=7m10s). I recommend playing the video at 0.25 speed because the creator is fastforwarding through the boring parts. At 7.10 (which the link starts at) and 8.20 there is some Augur action. You can tell that they applied Gnarlpine Vengeance by the enrage icon above their heads.

They generally seem to be applying Gnarlpine Vengeance to themselves shortly before they die - probably applying it at less than 10 or 20 % health, like "you're going down with me!". They act the same way in Cataclysm walkthroughs, but it's still hard to tell exactly _when_ they are programmed to do it because of the high DPS.

The buff is also used by Gnarlpine Avengers.
