### ISSUE TITLE
[Hellfire Peninsula] Ravager Egg Omelet buff not activating

### ISSUE THREAD

**Issue by Ayatan** [ccshiro/cc-buglist#1792]
This is a quest reward for killing ravagers in souh-western Hellfire Peninsula. It is supposed to provide 10 Stam but nothing happens when you eat it. I also notice it doesn't display the usual well fed note in the tooltip ("If you spend more than 10 seconds eating..."). 

I didn't try through cooking and the other foods seem to be working properly - the tooltip is properly displayed as well. Screen below as evidence (the well fed buff displayed is that of the buzzard wings, which work as intended).

![wowscrnshot_090615_115913](https://cloud.githubusercontent.com/assets/2815339/9895933/092381a6-5c68-11e5-97d9-6521ac0446bc.jpg)

**Comment by ccshiro** [comment]
The reason you don't get it is because you have power word: fortitude. Normal Well Fed stamina food stacks with PW:F because it also applies spirit; making them different type of buffs.

As another example, Scroll of Stamina does not stack with PW:F either, because it too is the same type of buff.

If you think this is incorrect you'll need to provide evidence for the Ravager Egg Omelet in particular.

**Comment by Ayatan** [comment]
This is correct, I just tested it again. It works as intended without PW:F. Food with spirit + stam stacks correctly on top of PW:F as well.

Maybe it's worth noting that the buff of the Ravager Egg Omelet insta-applies, no need to spend 10 seconds eating. Not sure if you want to keep it like this but as far as the buff itself is concerned there is no need to investigate further.
