### ISSUE TITLE
Slice and Dice: "A more powerful spell is already active"

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#18]
Report: "Slice and Dice: if the duration of current slice and dice is a 5 CP, and you use a 1 CP one, it won't overwrite the current one but it will use the Combo Point. It should say 'A More Powerful spell is already active'.

Question: The above report is indeed how buffs normally behave when attempting to overwrite a less effective one. However, slice and dice works quite differently from normal buffs, so we'd prefer to find some evidence that this is true. A video, screenshot or textual source would serve as evidence.

EDIT: Reading my post again my explanation is rather poor. What it boils down to is: what happens if the SnD you're about to apply would have a lower _duration_ than your current one? Will it eat up the combo points, but not update your buff? Or will it deny you casting the spell at all (with the above mentioned error)?

**Comment by Lekritos** [comment]
The thing i find a bit unclear about this is in what manor you mean it i kinda understand it in two ways. 

Scenario 1: You have a 5 CP SnD up and running it's down to 2 seconds like and you want to replace it with a 3 CP SnD as a 3 CP SnD will keep SnD up and have a longer up time than the current 2 seconds you have left of the 5 CP SnD 

Scenario 2: You have a 5 CP SnD up just popped it so however long is left of that. You then build up 1 CP and try to do a SnD. 

Which of these two Scenarios is it you mean?

**Comment by ccshiro** [comment]
Scenario 2.

**Comment by Lekritos** [comment]
I looked a bit around but it's kind of hard to find information on it. 

The subject was briefly mentioned in the thread below but well to be fair it could just be some guy talking shit but it's mentioned that you could always override a longer lasting Slice and dice. Also this is a new thread so the question is also what he means by "always" as we do not know how long he've played. 

http://us.battle.net/wow/en/forum/topic/10357946626 

But i'd say it should work either in such a manor that it says a more powerful spell is active or it should simply override it. Consuming the CP and doing nothing shouldn't happen.

**Comment by MakDizdar** [comment]
I have played TBC the longest as a rogue and I remember well that a low effect S'n'D replaced a 5 cp snd. So yes, it consumes the cp and replaces it with a worse timer. I remember a guide on elitistjerks that explained spreadsheets for PVE rogues and mentioned this manner. Maybe the article is still there, not sure. /proditor

**Comment by kolchax** [comment]
I don't think it matters how it was on retail. If the duration of the 5CP SnD is less than a duration of a 1-5 CP SnD than the buff should be replaced. If the duration is greater than the CP SnD you're trying to use than 'A More Powerful spell is already active' error should pop preventing you from wasting a combo point. If it was actually consuming a combo point and doing nothing or replacing the greater duration with lesser on retail it's blizzards fault. This is your chance to fix it Shiro.

Source: Logic.

PS. Didn't you make charge work like on patch 4.3? If so, you know what to do here.

-Kolcha

**Comment by Lobogo** [comment]
from what i remember (yes it has been a looong time, but i been a rogue for 5years, vanilla-tbc-wotlk) SnD works like this: 
if you have longer duration on you active and, say, you use 1cp SnD, it overwrites your current buff so you get shorter duration, simple as that
SnD works like a finishing move that doesnt need a target, you are never ever prevented from using it, you just need the CPs
and i never got a "more powerfull spell is already active" message, didnt know what that was untill i started playin paladin

**Comment by MakDizdar** [comment]
Why is it blizzards fault?
PVE rogue rotations in tbc are repetetive and boring. It is mostly all about having the right mix of hit rating, AP and expertise which most rogues use spreadsheets for to calculate their dps and to decide what piece of item is temporarily the best for their dps.

Not fucking up with s'n'd is not hard and should be there so that you can actually mess upp other than just clicking sinister strike, s'n'd and rupture with the occasional cloak of shadows and vanish for survival.

But yeah, it is not a dealbreaker anyway. It sounds stupid that it consumes a combo point to make it worse for you but I liked it that way,

**Comment by ccshiro** [comment]
@Lekritos That's interesting.

@kolchax Logic unfortunately does not provide a good source when it comes to mechanics in WoW. Also, I don't know what 4.3 charge mechanic you're referring to.

It'd be nice if we could find some more evidence about this, maybe just a few more threads where it's mentioned to make the claim at least a bit stronger.

**Comment by Vetinari1** [comment]
There is some bugreport from retail: http://us.battle.net/wow/en/forum/topic/6893519841
There is possible explanation: 
When this happen while you use rupture its because you used previous rupture with AP trinket or any kind of AP buff which is not on you anymore. Then you will get your error message.
So maybe its the same with Snd that you will not get any message if you use "buffed" snd (haste buff, Adrenalin rush... w/e)

But what I personally recall is that I only got error messages on rupture, never on snd.

**Comment by kolchax** [comment]
@ccshiro I understand that but regarding this specific case about this specific spell you have only to gain by making it the way it is now on retail. You are not buffing the rogues, nor nerfing them. You would be fixing a very annoying issue.

Also regarding the charge mechanics. In the video on youtube you are comparing tbc to cata and I thought that you implemented the fix to charge that was done in the 4.3 patch. I might be wrong though.

http://www.wowwiki.com/Patch_4.3.0
"Charge (and related abilities) should now correctly path to a target even if the target moves during the Charge. This change should decrease the likelihood of the warrior Charging to a different location than the target."

**Comment by Ickler** [comment]
I did a fair share of PvE and a lot of pvp as rog in retail TBC. As far as I recall early TBC pre 2.3.0 at least, I remember a short one overriding long ones.. However that was changed so that it works just like it currently works on CC. 
To eliminate confusion: 
If you have a 5CP SnD running as long as the one you're applying doesn't last shorter dura, it should overwrite it and renew the updated duration... If new application was shorter, CP's removed - nothing changed with time on current SnD.
How I recall it being early TBC:
The new SnD renewed and overrode the previous one disregarding everything, meaning  a shorter and less CP SnD overrode a longer in duration SnD and replaced with a shorter duration one.

But having played a lot of rogue in TBC environment after retail, I would really just recommend keeping it as it currently is.. Anything else creates a lot of frustration in certain scenarios, and it's not really of great impact... 
But then again finding some proof of any claims in this case, will be a challenge. But I think the SnD change came along with one of the rogue talent re-makes. 
As for rupture, it's incredibly annoying if you get the message that a more powerful spell is active, and I can't recall ever being annoyed by that on retail. I'll set off some time and look through some old EJ content to see if I can find any validation of my claims.
- Ickler

**Comment by kolchax** [comment]
I came upon an elitistjerks thread where they are talking about a Slice and Dice addon. Sadly this is from vanilla but it may be the way SnD worked in TBC.
http://forums.elitistjerks.com/topic/6464-slice-and-dice-optimization/

"alright, thanks much, i'll have to figure out why that would happen. I haven't seen that yet, but i'm sure there's a corner case somewhere I didn't think about which would have made the behavior you saw possible.

oh, nm, i just got in game and found it.

Example:
you do a 5 pt SnD (with 3/3 talent), you get 27 seconds on it.

you cast a 1 point SnD 10 seconds later.

the bar refreshes to 10, even though your actual buff doesn't get overwritten by the smaller value. So, the bar will dissappear in 10 seconds, but slice and dice will go another 7 seconds beyond that because of the initial 5 point SnD's time encompassing those.

So, i'll have to modify the code for that scenario. thanks so much! "

Considering this, I guess there is no "A More Powerful spell is already active". A smaller duration doesn't replace the longer duration but it eats up the combo points anyway.

**Comment by Vetinari1** [comment]
Yeah, what Kolchax wrote seems to be accurate. I think it should be like that.

**Comment by ccshiro** [comment]
@kolchax Thanks for that link. That actually feels like a fairly good indicator. This is also the workings we currently have on our server, so I guess all in all we can deem this not a bug.
