### ISSUE TITLE
Huge Screen freeze Ramparts

### ISSUE THREAD

**Issue by Piranhaz** [ccshiro/cc-buglist#183]
I was in a 5 man grp lvl 60 doing Hellfire Ramparts (Normal difficult). We pulled the last 2 mobs in front of the bragon boss and all of us got a HUGE freeze for like 5 secs or maybe more.

**Comment by Barroth** [comment]
Me and some of the group members had a freeze in ramparts aswell, though on different mobs: At the 5caster pack after the stairs

**Comment by Bearmanpig** [comment]
This happened to myself and other members of my party as well (in Ramparts), but never to everyone at the same time. It might have something to do with the client side settings, combined with a server side bug, since not everyone was affected.

I'm running the game on highest possible settings (1920x1080 @60Hz resolution)

Someone mentioned deleting the cache folder could fix the problem, but I didn't get the oppertunity to test that.

**Comment by FurioCC** [comment]
I in that run with @Piranhaz confirming freeze on last two mobs.
In previous runs on other tests i had freezes in Ramparts on big caster packs with that single melee mob in center.

**Comment by ccshiro** [comment]
Freezes are not really dependent on the mobs themselves from what it seems (e.g. I can pull these two without freezing). We are aware there are freezes though, but have not had the time to figure out why. As such I will close this as invalid, but we're still going to debug and try to figure out why freezes do happen in general.
