### ISSUE TITLE
Dueling Timer countdown

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1869]
This is what occurred to me when I attempted to duel. Oddly, this is the first and only time this has occurred. I believe went down as far as -100 and something. Also, I didn't get a screenshot of this, but the flag remained after the duel ended:
![wowscrnshot_092815_214702](https://cloud.githubusercontent.com/assets/13790554/10184862/a325d9d2-66f6-11e5-8e95-bb60849955ee.jpg)

**Comment by Jumpka** [comment]
I know how to reproduce this issue. It happens when two people request a duel at the same time, the duel starts without accepting, and if you declience, it will act as a forfeit, but if you accept it, another countdown for the duel starts, and this countdown will go below zero.

Steps to reproduce:
1. Request duel with someone at the same time 
2. One of the chars will be asked to accept the duel or declience, if you accept it, this bugs happens

note: also there should be two flags, one of them will stay forever

**Comment by ccshiro** [comment]
Think I've fixed it, wasn't able to test the fix on my own, though.
