### ISSUE TITLE
AoE, traps, totems, etc in a friendly region: how does it affect PvP flagging?

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#19]
Question: If an area of effect spell, trap, totem, and so on, is placed down in, let's say Elwynn Forest, and a Horde walks by with /pvp flag on. Should, assuming the Alliance that used the effect is _not_ /pvp flagged, the effect work on the Horde, and bring the Alliance into /pvp? Or, should it ignore the Horde as a potential target?

A video would serve as good evidence in this case.

**Comment by ghost** [comment]
http://www.youtube.com/watch?v=60To4LaFt90 -> earlier version, Video date: 28/11/2007
http://www.youtube.com/watch?v=JLWIvF0r_Ok -> older version, Video date: 01/12/2007
TBC release date: 15,January, 2007

So it must be from retail.
It is a PvE realm, they are in horde friendly zone.
Beginning Alliance and Horde with pvp flag off.

In it you see 2 alliance dueling, nelf druid and dwarf hunter puts trap on ground.

The trap only releases after the druid goes on top of it!, even though there are plenty of horde in range. -> Right at start of video, at 1:51 undead rogue standing on trap without triggering it,
After the trap is relesed the snakes aggro nearby hordes.

But at 2:01 you can see the dwarf Gnarak <The Peacefull Storm> getting flagged and getting attacked by the 70 orc hunter.

Clarification comes from watching the 2nd video:
This corresponds to 1:48 timestamp, where you see the comment of: "Oops, They Hit The Flagged 70 Hunter".

So:
1st-> They shouldn't trigger to players with pvp flag off!
2nd -> They trigger to players with pvp flag on?!? Unknow from this video? Not sure if hunter was in range of them at 1:42 of second video.
3nd-> If they attack player with pvp flag off! The flag stays off!
4rd -> If they attack player with pvp flag ON! The flag turns ON! -> and because that hunter died.

**Comment by Ghhlox** [comment]
I don't have any evidence except my word that I played before and during TBC on a PvP server (not sure if that's important). You were flagged for PvP if you laid down traps or put down an AoE (like consecration or flamestrike, etc...) for damaging a horde in a friendly zone, even if it was not your intention to (suppose they walked into your flamestrike after you had put it down). I specifically remember putting down flamestrikes in Westfall while horde were harassing us, and when they would walk into it I would get flagged. I can't speak for totems (I didn't play horde); I imagine Fire Nova totems would work the same way, but I couldn't begin to speculate on Searing Totems or Grounding Totems.

EDIT: In reference to Subzero's post, you can read some old discussion on WoWhead about how Blizzard initially designed the Snake Trap spell to spawn "Venemous Snakes", which were not considered pets or guardians of the hunter who had laid the trap, but simply hostile units. Hence why they wouldn't flag you for PvP if they attacked someone from the opposing faction (unless, I believe, they specifically activated your trap, in which case the trap would count as a spell performed against an enemy player).
http://www.wowhead.com/spell=34600/snake-trap#comments

**Comment by Vetinari1** [comment]
https://www.youtube.com/watch?v=60To4LaFt90 there is the video, Ghhlox.

Any kind of damage or even interaction (like throwing heavy leather ball) against opposite faction will flag you for PvP. Without any restriction on zones (doesnt matter if you are in neutral or friendly zone)

**Comment by ghost** [comment]
Adding... through more searches found...
http://www.wowwiki.com/Snake_Trap?oldid=1580422
"It appears that if the snake trap is triggered by a mob, the snakes will attack members of the opposite faction if they are within the snakes' attack range, whether or not either character is marked for PvP. Furthermore, the snakes will force that player's PvP flags up if they fight back regardless of what their flags are set to, allowing other players to force PvP on unwilling members of the opposite faction, in essence, a loophole. This is supposedly fixed in patch 2.4.0 "

Important bit:
"will force that player's PvP flags up if they fight back regardless of what their flags are set to"

http://www.wowwiki.com/Patch_2.4.0
"Snake Trap will no longer affect non-combat flagged players."

From this sentence... and using counter logic, one can assume that...
If the player has pvp flag ON, it will affect them!!

So that should take care of 2nd point of my post above.

**Comment by ghost** [comment]
http://wow.joystiq.com/2007/10/31/encrypted-text-how-to-be-evil/
"Follow a lowbie around, close enough that he can hear your stealth sounds but can't see you. If you're feeling lucky, you can also stealth and unstealth around him, hoping that he has a mod that will show your stealthing on the screen. The lowbie will either think you're a same-level player and AOE to knock you out of stealth, whereupon you can kill him for "attacking you first", or he'll leave you alone, and you can watch his nerves become frayed to the breaking point as he wonders when the other shoe is going to drop."
^2007 article

-> Basically, go near lowbie in friendly zone ( to him ), if he aoes you in friendly zone, he gets pvp flag ON and you can kill the lowbie.

Now about the duels...
But wowwiki states that, http://www.wowwiki.com/PvP_flag?oldid=1433806 :
"Your flag will be put up in any of these situations:
->You engage another player of an opposing faction in combat other than dueling."

So while dueling, your effects shouldn't trigger pvp flag coming up!
And the whole snake trap thing above was a loophole of sorts!
And regular aoes, without "summoned" mobs, shouldn't hit anyone other than the person you are dueling.

So then... spells that are used before duels end should be treated one way, example consecration, and spell used right after duels end should be treated another way?
And players from opposite faction, with bad intentions, might just lurk nearby to be caught by an accidental aoe right after the duels end.

Less relevant, current changes to retail:
http://wow.joystiq.com/2014/08/30/warlords-of-draenor-pvp-now-requires-active-flagging-on-pve-rea/
"This means no more accidental flagging for players that are simply trying to DPS or quest out in the open world on PvE realms. And this also applies to healers as well -- healers will simply not be able to heal flagged players unless they choose to actively flag for PvP."

Cause many times, people would just stand near tanks, that did aoes as part of their rotation while tanking bosses on Timeless Isle.

**Comment by fishworld** [comment]
I don't have evidence like a video to prove this, but yes, back in BC you would indeed get flagged if you're for example using blizzard in a friendly zone where you're not flagged, but an enemy player that walks into the AoE effect will make you flagged. 

If you're buffing a friendly target that is flagged, and you're not, you will become flagged. I remember this because back when we used to set up people (it was fun!). For example, a friend of mine would duel someone outside of orgrimmar, and I then would (I'm playing alliance) run into some area effect from the person my friend was dueling just to make him flagged and kill him. The easiest way was though just to flag yourself and ask some someone who you wish to kill, to buff you with something (arcane intellect for example) and they would get flagged. I am aware I told the exact same thing twice.

**Comment by kolchax** [comment]
According to wowiki there are 6 categories of AoE.
http://www.wowwiki.com/Area_of_Effect

In this video: https://www.youtube.com/watch?v=4jDdyLLDoNM (0:42-0:46 and 1:30-1:33)
you can see that Arcane Explosion does not flag the UD mage for pvp. Since Arcane Explosion is a 'Point Blank AoE' spell, all spells of that type should behave the same.

Consecration: http://www.wowwiki.com/Consecration 
"Patch 1.7.0: Consecration and other similar spells can no longer be used by non-PvP flagged players to damage PvP flagged enemies."

This thread: http://us.battle.net/wow/en/forum/topic/7004011863 "Cleaves still trigger PvP flagging." shows that cleave effects do trigger the pvp flag.

This might cover the GTAoE.. and the AoE question altogether.
http://www.wowhead.com/forums&topic=76830/question-mage-getting-flagged-with-aoe

Also: http://us.battle.net/wow/en/forum/topic/7005431484
"No AOE should hit a flagged player if you're unflagged. I've tested it with targeted AOEs, Cone AOEs, ground AOEs. You cast Blizzard Rain of Fire for example and it hits everything in the area but it ignores any flagged players even though it's a targeted AOE."

http://us.battle.net/wow/en/forum/topic/6893610224?page=1
"Are you certain you did not target the flagged player and use a different ability, Sepher? AoE's should not hit a flagged player if you are not flagged yourself. 
I just tested it with Death and Decay myself and at no point did the casting character become flagged while using that spell. " - Support Forum Agent.

Totems:
http://www.wowwiki.com/Patch_0.10
"Pets and totems will no longer attack PvP-flagged players if you're not in PvP."

Hunter traps:
http://www.wowwiki.com/Trap
"Patch 1.8.0 (10-Oct-2005): Hunter traps no longer affect opposing players when the hunter is not flagged for PvP."

http://www.wowwiki.com/Patch_0.7
"Actions that will enable a player for PvP status on the Horde vs. Alliance race war server will be: entering or being in an enemy territory, entering or being in a contested territory, attacking an NPC of the opposing faction, attacking another player, and/or aiding a player engaged in PvP. Players will also be able to enable PvP on their own by using the /pvp command. Once PvP has been enabled for a player, no matter what the method, it will remain in effect for five minutes."

I think that pretty much covers everything.

**Comment by ccshiro** [comment]
Fixed. Should work correctly now.

Thanks for help with the research.
