### ISSUE TITLE
Scroll of Protection doesn't stack with Mark of the Wild

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1945]
It's certain that protection scrolls didn't [stack with MotW in WotLK](http://www.wowhead.com/item=33459/scroll-of-protection-vi#comments:id=999700). However, [this guide for Brutallus](http://www.mmo-champion.com/content/313) mentions buff scrolls and the [Wowhead comments](http://www.wowhead.com/item=27500/scroll-of-protection-v#comments) theorycraft the value of buff scrolls seriously, a moot exercise if they didn't stack with standard raid buffs.

Strength and Agility scrolls seem to stack with MotW and SoE totem just fine.

**Comment by opzor** [comment]
this requires more research.

http://www.wowhead.com/item=27500/scroll-of-protection-v#comments

patch 2.1.1
"Since this scroll stacks with elixirs, buffs, et cetera, it couldn't hurt to save these for your main tank. "

patch 2.4.1
"The effect doesn't stack with the exalted tank ring from MH. So when the ring proccs, the scroll-buff is completely removed. "

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/36014-lots-of-spirit.html
" you can have both (divine spirit)(50spirit) and (prare of spirit, or what ever (the one that is to all party members for (40spirit) so with both the prayre(40) and regular(50), you have a total of 90 spirit"

**"Normally you are only supposed to have the most powerful spell that gives a stat."**

"Even though both buff icons show up, you only get +50 spirit, and not +90... so they don't really stack! "

**Comment by KimmoKM** [comment]
https://www.youtube.com/watch?v=38arl7HL5nc shows a warrior tank with protection scroll buff with MotW, although it disappears and gets replaced by a proc at 1:48 (Mount Hyjal ring? Bulwark of Azzinoth? I don't quite recognize the buff icon). While the video is more recent, it seems to be a reupload of an older MMO guild showing off their historical achievements (http://www.arcanum-gaming.com/index.php/les-arcanum/historique).

I thought Brutallus tank PoV videos might be the best place to look and that was the only one I found with armor scroll and since it gets overwritten by procs, it's kinda expected it doesn't get used as often. Interestingly, I didn't see any videos with agility scrolls, although the [comments](http://www.wowhead.com/item=27498/scroll-of-agility-v) in Wowhead specifically mention it stacks with GoA, at least in 2.3.0 and with food/potion buffs in 2.4.2

**Comment by Ickler** [comment]
https://youtu.be/38arl7HL5nc?t=108 Here is where the scroll is removed, and if you look closely at the aura's he gain as this happens it's Bague du Defenseur Eternel. 
http://fr.wowhead.com/item=29297/bague-du-defenseur-eternel
http://www.wowhead.com/item=29297/band-of-the-eternal-defender for us mortals that don't understand french very well...

So it appears that the MH exalted ring procc indeed removes Scroll of protection.
