### ISSUE TITLE
Invisibility + Ice Block

### ISSUE THREAD

**Issue by Summoning01** [ccshiro/cc-buglist#1998]
should be possible to cast invis -> ice block and then cancel it just before invis countdown is over.
https://www.youtube.com/watch?feature=player_embedded&v=LFUCxjyMIsY (7:18)
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/14448-invisibility-ice-block.html

**Comment by Liesara** [comment]
So first of all the video seems to be at around 2.1-ish since he says so in the description. And those forum posts seem incredibly questionable.
1. You use invisibility.
2. You use iceblock.
3. You remove iceblock aprox 5 seconds before invisibility starts kicking in.
   Note: You need a timer.
4. You'r invisible, without haveing a chance of getting hit.

What does that even mean?
And in a later post someone said:

This doesn't work because casting Ice Block will break your 5 second Invisbility countdown. Ice Block counts as a hostile action that stops your fade.

Besides, no point in Ice Blocking right before you fade out. Any form of DoT on you WILL stop you from fading out. Ice Blocking before you cast Invisbility is the only way to clear debuffs before attempted to vanish.

I'll look up patchnotes, maybe it was changed during tbc.

EDIT: Nope, can't find anything specific. Only bit I found concerning invis at all: http://us.battle.net/wow/en/game/patch-notes/2-1-0

Invisibility: Clarified the tooltip on this ability to indicate any action breaks the invisibility effect.
Need to point out here though, that the tooltip doesn't say "hostile" action anymore (or at least not only) according to this patchnote.

and then in 3.2.: http://us.battle.net/wow/en/game/patch-notes/3-2-0

Invisibility: Can no longer be interrupted by a hostile action or damage done during the 3-second Fade time, however an invisible mage is still vulnerable to Stun and Silence effects.

Stopped looking at that point.

Also, I'm just being curious here, but I noticed the Invis buff icon in the video changing from the normal icon to a weird one right after cast. Can someone explain? I'm completely lost there.

**Comment by Chulain** [comment]
http://www.engadget.com/2008/11/15/arcane-brilliance-leveling-your-mage-through-northrend/
If you find yourself plagued by DoTs that would otherwise break your Invisibility, Ice Block them away prior to making your escape. I've already made liberal use of a macro to break Ice Block and cast Invisibility at the same time. It's an almost fool-proof panic button.

**Comment by Chulain** [comment]
Nov 26 2006 (yeah thats beta)

http://wow.allakhazam.com/forum.html?forum=243&mid=1164584439222999658
Q: What exactly constitutes a "hostile action" that breaks Invisibility?
A: At present, it appears that you can cast Invisibility and then engage in any action that does not affect the enemy without breaking the fade effect (Evocate, start a spellcast, bandage, etc.) An action that does effect the enemy will break the fade effect when the spellcast is complete -- in other words, you can cast Invisibility, then cast a Pyroblast. Six seconds later, when the Pyroblast launches, your Invisibility fade will cancel, but you will have dropped 75% of your threat. 

It also appears that any ongoing action is cancelled when the fade period ends and you become invisible. For example, if you cast Invisibility, then cast Evocation, your Evocation will be cancelled before it ends, losing the final tick.

Finally, it appears that any action other than moving, whether hostile or not, breaks Invisibility once you have become invisible. No using Invisibility to go out of combat, then eating and drinking while invisible.

**Comment by Summoning01** [comment]
sambjo on 2007/06/09 (Patch 2.1.1)
" _yes, useability nerf in so many ways. 1) invis + fireball: dps loss. before you could invis and then_ _fireball effectively only losing a global worth of dps for 4 ticks of the invis -threat. now you have to_ _stand there and do nothing. 2) invis + evocate. no longer possible. if you want to shed aggro and_ _regen mana you have to spend twice as much time now. 3) invis + blink/frost ward/fire ward/mana_ _shield/etc. all of these nondamaging spells now cancel the **invisibility fade**. blink is the most_ _important one and was extremely useful for kiting in heroics. keep in mind that the part of in_ " ([wowhead](http://www.wowhead.com/spell=66/invisibility#comments:40))

totally missed that Killimus' comment :sweat_smile: 
apparently in 2.1 notes (and the tooltip) they really meant invis fade effect.

**Comment by Jumpka** [comment]
Well then just close it I guess 0x62616c616e6365 ?
