### ISSUE TITLE
Feign Death not losing target in duels

### ISSUE THREAD

**Issue by distant1** [ccshiro/cc-buglist#2002]
Feign Death doesn't make your enemy lose target on you in duels, whether in combat or not.
"For PvP encounters, this will cause enemies to drop you as a target." - Wowwiki (http://wowwiki.wikia.com/wiki/Feign_Death)
https://vid.me/4sSP
https://vid.me/nFeX

Edit: Removed part about feign death removing CPs as it was disproved below.

**Comment by Liesara** [comment]
I don't know about the dropping target thing, since I haven't tested it. That is to say, even in a duel between two hordes it should drop target, but I don't know how it currently works. I'm here to disprove the Combo Points part.

While in Vanilla dropping your target did indeed make you lose your Combo Points, this was patched with 2.0.3:

Combo Point loss upon target switch in vanilla:
https://youtu.be/cA8ueCWc4VQ?t=5m45s

Proving the behavior of not losing Points upon quick retarget even in vanilla (if you're curious):
https://youtu.be/jOAGAPpaxDg?t=1m57s

http://us.battle.net/wow/en/game/patch-notes/2-0-3

Combo points added to a target should not be reset until you add a combo point to a different target.

And a random forum post for further proof:

https://forums.penny-arcade.com/discussion/5827/wow-huntering-the-thread/p19

Rogues only lose their combo points on a target if they start building combo points on a seperate target. Losing your target then reselecting them doesn't matter. At least in TBC.

There's still the possibility of Feign Death being special in that regard, since you in fact do lose your Combo Points if your target dies, but I feel that needs to be proven first. I went through the patch notes up to 2.4.3 to see if at one point it did that, just to be patched later and didn't find anything.

Jumpka being salty, best issue ever.

**Comment by Jumpka** [comment]
EDIT: Weow Liesara maybe tell me that you'll make the post yourself in the end. I typed all this shit not even insulting distant1 once as you aked me, even tho he did 0 fucking research before posting the CP part and you post it 2 and a half minutes before me, KYS pls.
Anyway, heres basically the same thing that Liesara posted, I'll leave it here since I already typed that (there's like one different link in our comments I think)

The combo point part wasn't true anymore during TBC:
Deselecting target before patch 1.4.0 caused you to lose all CPs from the target, that means feign death would remove all CPs from you. This changed a bit in 1.4.0:
Patch 1.4.0 (2005-05-05): Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected.
That's why you can still see people losing their CPs if their target switches like here:
https://www.youtube.com/watch?v=cA8ueCWc4VQ&feature=youtu.be&t=5m39s
This was removed in 2.0.3 tho:
As of the 2.0.3 Patch, the rogue will not lose combo points upon switching targets until a combo point has been added to another target.

http://forums.elitistjerks.com/forums/topic/9414-203-ptr-is-up/?page=2
(last comment)
That'll be a very welcome change. I'd essentially thrown in the towel when it came to big finishers on hunters and rogues in PvP. It's par for the course to build up a few points and go in for the finisher, only to be thwarted by a well-timed Feign Death or Vanish. Nothing wrong with that, of course, but I'd almost always lose those points after instinctively mashing Tab to pick up the target again and fixing on another player instead. Adios, combo points.
(Yes, I know I should use Target Last Target more often.)

also: https://forums.penny-arcade.com/discussion/5827/wow-huntering-the-thread/p19

**Comment by Ickler** [comment]
I know this was the case, unless you were in a group / party with the people you duelled. Did you make sure you weren't grouped before posting this?

**Comment by Ickler** [comment]
So we re-tested this today. There is no issue with this. Feign death drops target as supposed to, however it doesn't if you're grouped. Which is also correct.

**Comment by ccshiro** [comment]
@Ickler thanks for testing, will close this.
