### ISSUE TITLE
Silence Reduction from Necks

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#2010]
There are 2 necks in the game that grant 20% reduction to silence and interrupt effects.
Talisman of the Breaker, which drops from Keli'dan in Furnace Heroic and
Pendant of the Lost Ages, which drops from Morogrim in SSC.

Both of these currently have an effect on both silences and interrupts the wearer casts on others, as well as silences and interrupts cast upon the wearer. These necks should only have an effect on silences and interrupts cast on the wearer of the item.

Since shamans have a talent with a similar effect it might be worth taking a look at their lockout durations from earth shock as well. Paladins' Concentration Aura is most probably fucked up as well (which is a huge deal since it applies to the whole group).

**Comment by Jumpka** [comment]
Ok since Liesara has some late night brain cancer or something, let me clarify it a bit. All effects that reduce the duration of incoming silences and interupts also reduce the duration of silences and interupts you do to others. We did a quick test in nagrand arena where I used improved concentration aura on Liesara's priest, he would then use his silence on a mage not affected by the aura, but the silence was only 3.5 seconds, then we switched it aroud and I gave the aura to the mage and silenced Liesara who wasn't in the group with the paladin and the CS was only 2.8 sec.
It has nothing to do with the necks specifically, it's global bug with silence / interupt duration working both ways.
