### ISSUE TITLE
[Shaman] Totems and spell delay

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#2066]
Don't have any proof but it's kinda obvious that spell delay on totems affecting the shaman is wrong right now. You can intantly break your own fear on CC right now if you cast tremor totem after someone finishes casting a fear on you, since the tremor pulse will be affected by spell delay. Everyone knows that this wasn't the case on retail (it's not even ahrd thing to do on CC, you can basically instantly break any casted fear and a lot of instant ones too with good timing), because there would have been comments about this etc. The same should be true for grounding totem, which redirected spells from shaman instantly after being dropped, without any spell delay (I'll try to find some video proof for this)

**Comment by Klimpb** [comment]
I played a lot of enh shaman in S9 and I had to put down tremor constantly because people destroyed it all the time in 3v3. I remember that it was of very high importance of putting down tremor then swiftly get the fuck away from it. Because of how easy it was for people to fear me and then destroy it within the pulse timer.

Sometimes I would have grounding totem up and be sitting in sheep, it did happen but it was rare, I don't remember anything of tremor breaking fears instantly when used in a similar way though.

EDIT: After thinking about it for a bit.. How I believe it worked was totems functioned like buffing yourself, or at least similar to it. Meaning the effect would be instant, but the reason why grounding could be up a lot of times when you got sheeped etc, was because of the spell delay of the polymorph spell, when it had already "landed" on you but during the batch you were still able to cast spells etc, so here's when you could put up grounding totem, which would obviously not redirect polymorph since it already landed on you.

Doing the same with Tremor totem for fear would simply equal in the tremor pulsing instantly during the batch, after it has landed on you but before you've gotten the fear debuff on you.

At least that's my thoughts on it, would be nice to actually see it being used in a video from retail. If anyone could find any.

**Comment by Jumpka** [comment]
Ye, no idea why I didn't say that in my first post, could have saved Sd's time I guess, but the correct behavior is definitely totems acting like buffs, which means no spell delay on shaman, again, this doesn't actually need any video proof since everyone who ever played arena a bit on retail knows you can't break fear from yourself with tremor.
The edit is also correct about the Sheep + grounding thing. It's the same as getting cloned/sheeped with spell reflect up.
