### ISSUE TITLE
[Mind Control] When MCing a mob in a pack the priest get/can get initial aggro

### ISSUE THREAD

**Issue by Oldwal** [ccshiro/cc-buglist#207]
When MCing a mob in a pack inside SL, at least 2 mobs in the pack just ran straight to me instead of having aggro on the mob i MCed.

What should happen is that all the mobs should aggro (and kill) the mob i MC, not aggro me first.

The blue/purple mob in the first pack was MCed when this happened.
![untitled](https://cloud.githubusercontent.com/assets/10577633/5793316/56351888-9f3f-11e4-9c62-033451ef46b3.png)

**Comment by leroy1** [comment]
Since you're in combat with that pack and mc'ed mob havent got any threat points on them your mana gain tick cause threat so they run to you?

**Comment by Oldwal** [comment]
I have played priest since 2005 and i cant remember ever pulling aggro when pulling with MC. As mentioned my experience with this is that the pack aggros the MCed mob and kills it (a mob killed this way should yield no loot).

**Comment by KuroiKensai** [comment]
Mobs within aggro range of an MCed target will regard it as hostile - they have no qualms over beating up a unit that was a trusted ally only moments before, so you can mind control something and let the surrounding 'linked' NPCs kill it. Note, however, that if the MCed target is freed from your control, they will once again regard it as a friend and will immediately seek another hostile target to attack - which may be you.
Mind controlled NPCs have their own aggro; spells cast by an NPC do not get 'added' to your current aggro, so in group situations you do not have to worry about enemies that you attacked with an MCed mob favoring you over your tank.
Mobs must take damage from players in order to generate loot; should they be killed solely by a Mind Controlled mob they will drop no items. In addition, a Mind Controlled mob will generate no loot if it dies while still MCed; it must be released if you wish to take its items. 

/c/ wowwiki

**Comment by Oldwal** [comment]
I don't see how this adds something to the discussion. All this is already known.

**Comment by FurioCC** [comment]
It means that while mind controling you are not gaining additional threat towards surrounding NPCs.
It means that you are put into combat as result controlling NPC who is in combat himself, and that casting MC not viewed as action that causes global threat to nearby NPCs but only target itself.

Basicly MC situation treated by mobs like bodypull - suddenly 2 hostile entities apear on their threat list and they simply atack closest.
