### ISSUE TITLE
Seal of Command / Seal of Blood

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#2116]
Should SoC / SoB proc have level based partial resists ?
From what i have found it looks like it should not have the level based partial resists.

Will add a few videos here as i find them:

SoB:
https://www.youtube.com/watch?v=UyooXkH6mT8
https://www.youtube.com/watch?v=GQK8QWOv-5Y

SoC:
https://www.youtube.com/watch?v=_niDEJTiRLc

**Comment by joovah** [comment]
Looking at Wowwiki  

http://wowwiki.wikia.com/wiki/Seal_of_Blood  "This seal is counted as a second melee strike in terms of game mechanics, meaning that the damage it deals can miss, be dodged, be blocked, and be parried. Since it deals non-physical damage, it can also be partially resisted when used against mobs that are higher level than the player."

http://wowwiki.wikia.com/wiki/Seal_of_Command_(old) "Patch 1.3.0 (07-Mar-2005): The damage effects can now be resisted instead of dodged, blocked, or parried."

Also looking at the spell hit part of the prot paladin 3d @ EJ both proc are NOT mentioned in a "special" section

"Seal of Righteousness and Judgement of Blood are special in that they're incapable of either missing or fully resisting; if your auto-attack hits your Seal of Righteousness will hit as well, and if you cast Judgement of Blood it'll always land."
(http://web.archive.org/web/20080913121550/http://elitistjerks.com/f47/t21425-paladin_protection/#Hit__Spellhit_and_Expertise_and_what_they_do_for_you)
