### ISSUE TITLE
Succubus remain invisible when casting & channeling seduction

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#2121]
it shouldn't

**Comment by ccshiro** [comment]
Is it possible that it remains until the spell cast finishes? The reason I ask is because the spell is not marked to break on start casting.

Can't find anyone talking about succubus, seems mounting breaks lesser invis pot (same interrupt flags as the invis succubus has) at end of cast, though: http://www.wowhead.com/item=3823/lesser-invisibility-potion#comments:id=889938

**Comment by Jumpka** [comment]
https://vimeo.com/5356030 cancels stealth on cast finish (before spell delay tho)
can be seen many times in the video, but the most obvious one is 3:23
(9:27, 11:31, 13:00 very obvious one as well)

PS. Today should have been the beggining of my 2 month no internet time wasting period, pls stop fixing m88

**Comment by Klimpb** [comment]
@ccshiro @Jumpka 
Yes that seem to be the case.
Better quality of a section of the video Jumpka linked: https://www.youtube.com/watch?v=cG-qjDn8iO8
