### ISSUE TITLE
Perception range/Stealth mechanics, something is off.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#2157]
https://www.youtube.com/watch?v=2CMLa2enhG4 - Game starts at 0:47, set to 0.25 speed or download the video and go frame by frame. (Tournament Realm, likely patch 2.4.0 or 2.4.1)

Can't see the rogue(or is just about to fade into detection)
![vlcsnap-error751](https://cloud.githubusercontent.com/assets/9938017/12091241/ea3bd1d2-b2f5-11e5-856a-15437fc953ec.png)

Sees him
![vlcsnap-error867](https://cloud.githubusercontent.com/assets/9938017/12091255/042361dc-b2f6-11e5-93fd-08f748781b64.png)

Targets him
![vlcsnap-error350](https://cloud.githubusercontent.com/assets/9938017/12091263/149f738e-b2f6-11e5-97cb-72bc112b7baa.png)

Tested it on Corecraft: https://www.youtube.com/watch?v=RmU2MGhfd-Y
Retail video & Corecraft differ a lot

**Comment by Ickler** [comment]
There are quiet a lot of variables here that aren't known. The warlock could be wearing detection items and the rogue might not be specced master of deception. Judging by his use of deadly/cripp as his choice of poisons I would say it doesn't look like he's very bright. Also having Shadowstep, but not using Backstabs or Hemorrhage it's pretty obvious that this guy has probably never played a rogue before. And are testing the class for fun on AT since you can create any char with gear. As most of this warlocks other opponents appear to be as well.

Even from warlocks with paranoia, goggles and perception on retail during TBC I've never been discovered that far, neither while playing a druid or a rogue.

**Comment by Mephisto22** [comment]
Isn't there some sort of chance mechanic? It doesn't look like some variables could make such difference. Try doing it with a rogue without master of deception talent and test it multiple times.

**Comment by Klimpb** [comment]
This seemed to be a "one time thing" and I have not seen any other video that display such a massive range like this specific game. You can see that he spots enemies at a much lower distance with perception later on in the video.
