### ISSUE TITLE
[Dungeon] Blackheart the Inciter 

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2195]
Apart from all the reported issues about his MC.

After his charge he switches target and does not return to the tank.
He charges his target and then runs to a completly new target and hits it untill tank comes and grabs it.

He also evaded once after his MC and reseted completly

**Comment by ccshiro** [comment]
https://www.youtube.com/watch?v=XeZLEYiCEzE&t=88 Here you can see charge + aggro reset. Notice how it goes for the mage as her frostbolt hits just as the boss dumps aggro. That's important because the mage is also not in melee range, so the 130% threat buffer is still in effect post charge.

https://www.youtube.com/watch?v=XeZLEYiCEzE&t=201 Here you can see thunderclap and blackheart sticking to the tank. The tank does taunt as he get knocked away, but blackheart is immune to taunt so that's irrelevant (you can see the taunt debuff isn't applied).
