### ISSUE TITLE
Crushing blows from level 72 mobs

### ISSUE THREAD

**Issue by Gadixsp** [ccshiro/cc-buglist#220]
When looking through combat logs after a wipe we noticed out healer received a crushing blow from a Tempest-Forge Peacekeeper in heroic Botanica.

I was under the impression that crushing blows were only possible from mobs 3 or more levels above yours (http://www.wowwiki.com/Uncrushability)

**Comment by Barroth** [comment]
Yes, if the Player's Defense and the Attacking Mobs Attack skill have more than 15 points difference(5 points per level above the player) die Mob can crush him. So it is level 73+ if the priest had max Defense. Since Priests do not rely on weapon/meele combat it could be quite possible that your priest didnt do .maxskill

**Comment by FurioCC** [comment]
Just minor correction that **MIGHT** explain your case: crushing blows are not level based but based on difference between defender's defense and atacker's weapon skill and happen when difference is more then 15.
If your tank didn't have defense skill maxed (with .maxskill) then he could have been technically crushed by level 62 mob.
Referencing TBC version of article
http://www.wowwiki.com/Crushing_blow?direction=next&oldid=1514260

**EDIT** Nevermind i didn't see it was priest not tank. Clearly he didn't max his weapons/defense skills. Damn you @Barroth for being faster :p

**Comment by Gadixsp** [comment]
Ahh, didn't realize it was a defense skill issue. That makes much more sense.
