### ISSUE TITLE
[Core mechanic] Melee physical ability with debuff

### ISSUE THREAD

**Issue by Winns** [ccshiro/cc-buglist#222]
#### Introduction

If a melee ability that apply debuff (Mortal strike, Gouge, Kidney Shot and etc) was completely(100%) blocked by a target, should it still apply debuff ?
#### Research

Comment to **Gouge** spell -
["Gouge can be fully negated by successful block."](http://www.wowhead.com/spell=1776/gouge#comments:id=761584)

Comment to **Shield block** spell -
["This is immunity to Gouge."](http://www.wowhead.com/spell=2565/shield-block#comments:id=761595)

Some theme on blizzard forum about **Kidney Shot** -
["why can this move be blocked doged and parryed so much latley."](http://eu.battle.net/wow/en/forum/topic/2226277394)

Comments to **Hamstring** spell -
- ["Anyone noticed if this is still blockable?"](http://www.wowhead.com/spell=1715/hamstring#comments:id=349800)
- ["Sorry to not make you happy, but both Pummel and Hamstring are still blockable. This is because these abilities were hardcoded to be negated by block.."](http://www.wowhead.com/spell=1715/hamstring#comments:id=349800:reply=106551)
- ["IIRC, only attacks that deal damage can be blocked.."](http://eu.battle.net/wow/en/forum/topic/3061870241)
- ["Mobs with shields seem to have an annoying habit to block this attack (and all other ranks of hamstring) too often to seem normal."](http://www.wowhead.com/spell=1715/hamstring#comments:id=82052)

1.12 movie summary comment  -
["High Block rate of 19% is also achievable with Rage of Mugamba with 2 piece ZG set bonus and +def. This is important vs Melee to block Hamstring, Wing Clip and Gouge."](http://www.warcraftmovies.com/movieview.php?id=26625)

Some videos from retail (At chrome you can watch youtube on 0.25 speed):
- **Shield Block** (WOTLK 100% block chance) up but **Kidney Shot** was applied successfully.
  https://www.youtube.com/watch?v=pUiDsNpIh3c&feature=player_detailpage#t=177
- **Shield Block** (WOTLK 100% block chance) up on movie maker, **Mortal Strike** was blocked but debuff was applied.
  https://www.youtube.com/watch?v=cKKZ__GiJ7U#t=230
#### Corecraft

**Hamstring** effect goes through block
http://i.imgur.com/IMiOI5E.jpg

**Rend** was not blocked
http://i.imgur.com/cn2NtCm.jpg?1

**Mortal Strike** effect goes through block
http://i.imgur.com/MDO5xt9.jpg

**Kidney Shot** was not blocked, rogue does not have [Surprise Attack](http://www.wowwiki.com/Surprise_Attacks) talent.
http://i.imgur.com/crYe1dZ.jpg
http://i.imgur.com/qzwIrca.jpg

**Gouge** was not blocked
http://i.imgur.com/Kj7rgsB.jpg?1

[Bonestripper Buzzard](http://www.wowhead.com/npc=16972/bonestripper-buzzard#abilities) was able easy to stun me even that i had 60 lvl tanking epics 
#### Conclusion

From my retail server memories if a melee ability is blocked(100%) then it blocked! aka does not reach target. 
I believe that current mechanic is incorrect and if melee ability was blocked then a debuff should be blocked too.
There is an exclusion, [list of abilities that cant be dodged parried or dodged](http://www.wowhead.com/spells?filter=cr=60;crs=1;crv=0#50+1+16+2)

Also i found similar mechanic in pve encounters.
On Illidan boss, warrior and paladin tanks should have 101.8% avoidance to avoid Illidan **Shear** spell.

Comment to **Shear** spell -
["You need only 101.8% avoidance for Shear, since it cannot miss, and so there is no additional 0.6% for reduced chance to be missed against a lvl 73 boss."](http://www.wowhead.com/spell=41032/shear#comments:id=225917)

Maybe other players can give more facts, against or for.

**Comment by FurioCC** [comment]
As for warrior spells, "Overpower" exactly states that it can't be blocked, dodged or parried (we all know it's anti-rogue "lol he pressed evasion" button but what about other abilities).
Which brings me to the point that other offensive warrior specials  performed with weapon should be  affected by block/dodge/parry.
Requesting warrior/rogue PVP guru to this issue.

**Comment by Lobogo** [comment]
yep, from my memory, you can block the whole "spell" (or call it ability)
so you can block Kidney shot, and you should NOT get stunned if you blocked it (or dodged, or parried or if rogue missed)
though thats only my memory (which is more faulty every day)

**Comment by Ickler** [comment]
If Mortal Strike is dodged parried or blocked it should definitely NOT apply the debuff. Same goes with Hamstring, gouge etc. 

Kidney Shot to my knowledge should not be blockable since it has no damage application at all. Maybe something like blind? Blind is a physical ranged attack, but it cannot be blocked it can only miss.  (I could be wrong on this, I just don't seem to remember KS'es being blocked very often). However if you dodge it, obviously the stun is not supposed to land.

You can block kick for example, in which case kick should not interrupt your cast.

@the birds, it's probably swoop which is a knockdown not a direct stun. Knockdowns really can't be blocked, parried or dodged.

**Comment by Winns** [comment]
[Swoop](http://www.wowhead.com/spell=37012/swoop) is not in that [list](http://www.wowhead.com/spells?filter=cr=60;crs=1;crv=0#0+1+16+2) also it has flag "On next swing (players)". On other side in description you can read "Inflicts normal damage plus 18 to enemies in a cone in front of the caster, stunning them for 2 sec." maybe its like old thunderclap which cant be dodged parried or blocked as i remember or more like a druid swipe which is dodged parried and blocked, who know now 8(

**Comment by Iliana-sc** [comment]
I think the following is true based on memory (which is a useless source, but hey)
- If a spell that does damage is fully blocked it will not apply the debuff (e.g. hamstring)
- If a spell does not have any damage component it can not be blocked (e.g. kidney shot)
- As far as I know you can't block while casting, so while the above two rules would apply to kick/pummel/shiled bash, that condition can never actually happen

**Comment by Soyoen** [comment]
http://forums.penny-arcade.com/discussion/70707/wow-rogues-or-how-i-stopped-worrying-and-learned-to-facestab

Halfmex: "2. Gouge/Kidney Shot was parried/blocked, which it often was. Literally there were so many fights where BOTH fucking abilities would be parried/blocked, and you'd stand there going toe-to-toe with the mob, so yeah, time to Sinister Strike (you don't get Shiv until 70, so that didn't help out any) the mob until you built up enough combo points to try kidney shot again (and pray it didn't get blocked, dodged or parried)."

Posted during 2.4.0
http://www.wowwiki.com/Timeline_%28World_of_Warcraft%29

As always, open for interpretation :)

**Comment by blastlol** [comment]
@Ickler "You can block kick for example, in which case kick should not interrupt your cast."
Soz but this is incorrect, coz u cant dodge/parry/block while casting non-instant spells

**Comment by tedrasiel** [comment]
"I think the following is true based on memory (which is a useless source, but hey)

If a spell that does damage is fully blocked it will not apply the debuff (e.g. hamstring)
If a spell does not have any damage component it can not be blocked (e.g. kidney shot)
As far as I know you can't block while casting, so while the above two rules would apply to kick/pummel/shiled bash, that condition can never actually happen"

this

**Comment by Ickler** [comment]
I'll say it more boldly this time, Kidney Shot is not blockable. 

Not sure what the general conclusion here is, but in TBC having played very competitive arena I like to think those memories sit fairly clear with me still. 
Also it was a very prominent feature when someone dodged / parried Mortal strike in 2v2, it could literally save them the "all in". So this was a common relief for the person who dodged the attack, debuff not applying.

Also not sure if people know or not but this thread is mostly clearly WotLK/WotLK beta chatter: http://forums.penny-arcade.com/discussion/70707/wow-rogues-or-how-i-stopped-worrying-and-learned-to-facestab 

With the quote in question being from leveling, possibly in TBC it yields no real information. Gouge can be blocked or parried, KS parried. It just means he has issues landing consistent stunlocks on mobs in order to mutilate. If anything I guess it leads us to believe what I've been saying that avoiding an attack also makes you not take the debuff.

**Comment by zoofCC** [comment]
If it can help in any way:
1:33 Swifty uses hamstring and its parried, motomi doesnt get the debuff
2:07 Swifty used MortalStrike and gets parried, debuff isnt applied
https://www.youtube.com/watch?v=VZk1NJXHUqk
