### ISSUE TITLE
Spell Reflect & Poisons

### ISSUE THREAD

**Issue by Horrorfever** [ccshiro/cc-buglist#2234]
Warrior's spell reflect does NOT reflect poisons. (e.g. Shiv-Crip).
It /should/.

**Comment by Ickler** [comment]
This is completely false. Not sure where you got this. Anyway provide some proof to your report.

**Comment by ASrozaev** [comment]
reflеcts  **flytimе** spеlls 
poisons havе no flytimе

**Comment by Horrorfever** [comment]
curses do?

**Comment by Schaka** [comment]
It has never reflected poisons, ever. The same way grounding totem doesn't absorb them:
Where the hell did you get that information? You've played on shitty private servers for too long.

**Comment by Evolvee** [comment]
it doesnt even work on any private server imo :D

**Comment by Astixium** [comment]
If you search wowhead and battle.net forums nobody gives a clear answer. The only thing that I found was this https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/991
But how much would you trust Archangel. :s 

On the other hand there is this conv going on at Smolderforge. https://www.smolderforge.com/forums/5652-cloak-of-shadows-stealth-and-spell-reflect/0

According to http://wowwiki.wikia.com/wiki/Reflect?oldid=1580129 "_Rogue poisons use the spell mechanic and as such can be reflected, too._" since 2011 at least. Not sure about before that.

**Comment by DarkenRal** [comment]
Yes, this rumor came from wowwiki. You can see that there were nothing about poisons in Revision as of 03:25, 2 May 2008 http://wow.gamepedia.com/index.php?title=Reflect&oldid=1340020 but in the next revision, as of 11:02, 23 June 2008 - http://wow.gamepedia.com/index.php?title=Reflect&oldid=1421766 you can read this "new info". I believe someone who added this part was wrong. I've never seen rogue poisons being reflected on retail but maybe i'm just "unlucky".

p.s.: And gamepedia lags again :(

**Comment by ASrozaev** [comment]
@Schaka , why do u say it to mе? dumb

**Comment by Schaka** [comment]
I think it's more likely that spell reflect just doesn't reflect any triggered/procced spells. I'm pretty sure Shamans frostbite weapon was also never reflected. In years of playing DPR on retail (TBC, as priest) and rogue actively from Wrath til Cata, I have never seen poisons being reflected except on shitty Ascent/Arcemu cores back in 2008/2009.

**Comment by Horrorfever** [comment]
My bad, poisons are not meant to be reflected in TBC but later expansions. (MoP+ I believe)
