### ISSUE TITLE
Too short melee range while target & caster is moving

### ISSUE THREAD

**Issue by Horrorfever** [ccshiro/cc-buglist#2288]
Shiv (Chase POV):
https://youtu.be/JG1eNwyKAho

Auto Attack But No Shiv (????):
https://youtu.be/7Y4M1QF2N7U

5-7 OOR Shiv (Runner POV):
https://youtu.be/ycF5f8Yg7wo

// Horrorfever out

**Comment by ccnim** [comment]
https://www.youtube.com/watch?v=XgD59lIXfpY&feature=youtu.be&t=85
https://youtu.be/Ts318qxKaOw?t=99
https://www.youtube.com/watch?v=jj0pvjU7GXg#t=387
https://youtu.be/y_3pkCA6sZQ?t=197

**Comment by Horrorfever** [comment]
Scandalous.

**Comment by Ickler** [comment]
I would say this is still worth looking into, desync issues if they can be minimized are well worth the time spent... It's a nightmare playing melee at times. I tend to stay away from even testing these things, because I get too emotional, hehe.

**Comment by brndd** [comment]
mlgkid_introduced_to_the_concept_of_latency.txt

Your ping to the server is 100ms, and since WoW has no antilag of any kind that's quite substantial in a situation like that. The person chasing you in the third video likely has a lower ping, as he evidently has no issue hitting you in melee.

If this kind of thing bothers you, you have a few options:

1) Don't play melee
2) Play melee, but accept the fact that you will have issues like this
3) Uninstall WoW and start playing a game where competitive PvP is a development priority rather than an afterthought.

A quick personality analysis based on your IRC activity rules option 2) right out, and option 1) is probably ruled out by ranged classes not being MLG high skillcap enough.

Therefore I'd suggest option 3); there's a whole slew of various arena games coming out this year in addition to the already existing ones. These will probably suit your fancy better than a ten-years old poorly balanced WoW expansion does.

**Comment by Horrorfever** [comment]
Stick to PvE dood

**Comment by Ickler** [comment]
My ping is usually lower than 40ms, still this happened on CC though. Mostly because of target I was attacking I guess (90ms for him).

**Comment by Horrorfever** [comment]
NiM, I did not watch the whole videos, rather than the parts you have linked/underlined, and if that is all you have to show (single moments every now and then) - I am going to say that these links of yours point single occassions that could be blamed on the friggin lag or whatever.

Here we are talking about a very persistant clusterfuck of an issue that borderline murders melee pvp. It criples it if anything.

The problem does not persist in PvE, why would you torture the PvP player-base with a blizz-like technical flaw?

**Comment by ccnim** [comment]
The linked times show when the targets are actually moving continuously away from the target without a slow on them. The issue is clearly shown to exist when this happens.

**Comment by Klimpb** [comment]
Corecraft seem to be missing the "leeway" melee range which you get when both players are moving

I did a quick test on corecraft & retail

Retail: https://www.youtube.com/watch?v=_DgUcqXwtwk (2:03 in the video)
Corecraft: https://www.youtube.com/watch?v=2EWAWj0EdFA

If you watch the entire retail video you can that if your range indicator is precisely "white", you will almost never hit the target. The melee range leeway was most likely put in place by blizzard because people had so many out of range issues, if you're 6,5 - 7 yards away from someone, you shouldn't always expect to be able to hit the target even though the indicator shows that you should.

**Comment by Horrorfever** [comment]
I am not saying that it does/does not exist, I am saying that the degree of its existance here in Corecraft is far too extreme.

**Comment by Horrorfever** [comment]
BEFORE:
https://youtu.be/JG1eNwyKAho

AFTER:
https://youtu.be/Vw-yrPVoyzI

// GG WP

**Comment by Schaka** [comment]
So leeway range (2 yards iirc?) has been implemented now then? I guess that was the issue the entire time then. I'm glad to see it has been resolved. Thanks, SD!
