### ISSUE TITLE
Old Hillsbrad Foothills: shapeshift + human form

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#23]
Report: "At Old Hillsbrad heroic after shapeshifting i didn't get turn into a human anymore."

Note: Someone (can't remember who) told me this was how it worked. Personally I have no memory of it, and it'd be nice to have some evidence of it.

**Comment by ghost** [comment]
On this video:
http://www.youtube.com/watch?v=xrZpUOCzDdE
http://www.youtube.com/watch?v=mzc96p38jYI

@1:54 of first video, you can see the druid on left side, in human form, he is the one using the puple hat, and the druid mace.
On rest of video none of party members has hat visuals turned on.

@3:07 of second video, you see him left of the loot windows.

**Comment by DeeMarie** [comment]
Pretty sure Human Illusion should always apply when not shapeshifted, although there were ways to prevent this, ie aquatic form.

http://www.wowwiki.com/Old_Hillsbrad_Foothills - "Most players (most likely races who were not affiliated with the Alliance during that time) upon entering the zone become humans in appearance. This allows Horde races to interact with Southshore and other places. Night elves and draenei, who at the time of the escape were not part of the Alliance, are also humans in appearance. Since you are technically time traveling, a non-member of the alliance would make no sense at all in that time; this is probably why the effect happens. Savory Deviate Delight and other items that transform you will remove this effect. Unlike some other illusion, druidic shapeshift forms are visible."

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/87326-bug-useless-lose-human-illusion-buff-cot-old-hillsbrad-druid.html - I was in Old Hillsbrad the other day on my druid to try out the bearform-while-looking-like human bug, which worked flawlessly by the way , when I found out how to lose the Human Illusion buff altogether while in humanoid form.

If you cast aquatic form as a druid and shift back out, you wont look like a human but instead like your normal form. Shifting into cat/bear/travel will still make you human after you shift out though."

http://www.youtube.com/watch?v=xrZpUOCzDdE - Horde druid tanking, at 1:58 they all appear human again.

From the youtube comments: "We're all horde... Horde get disguised as Alliance in this instance. Problem is shapeshifting such as noggenfogger / deviate and any other methods of altering your model cancel out this disguise in most cases, so he looks Tauren (Which he is, but in Tauren form he will look human)."

**Comment by MakDizdar** [comment]
I remember that it always turned you into human form when not shapeshifted.
Or well at least when removing the noggenfrogger or savory delight effect to exit skeleton form /pirate form.

**Comment by zoofCC** [comment]
https://www.youtube.com/watch?v=6lOWgKhAMvU

At 3:44 the druid who is the first party player in his ui, shows an human head in his picture after being in cat form seconds before.

**Comment by Ickler** [comment]
I have some personal screenshots of this I can show, I am feral so I've been going in and out of forms. And this is just before getting to last boss.. As you see I'm in Human form. 
http://imgur.com/IO8lYEJ

**Comment by ccshiro** [comment]
PM'd by Mustonen: https://www.youtube.com/watch?v=6lOWgKhAMvU#t=216

Thanks everyone.
