### ISSUE TITLE
Vanish Blind issue or not?

### ISSUE THREAD

**Issue by Dusky1** [ccshiro/cc-buglist#2318]
I dont know if its a bug or not, but it seems an issue with delayed spells. Situation looks like this:

I see someone is going to Blind me and I press Vanish but I end up Blinded with a cooldown on vanish..
I think it should be impossible. If i vanish too fast, someone should drop my target and be unable to cast Blind on me. If he blinds me and I Vanish it should break both vanish and Blind. 

proof: 
![blind wowscrnshot_021216_192010](https://cloud.githubusercontent.com/assets/17127512/13016784/259ac35c-d1c1-11e5-8ca4-89d377c89e0a.jpg)
![blind wowscrnshot_021216_193524](https://cloud.githubusercontent.com/assets/17127512/13016785/25a994e0-d1c1-11e5-8699-cb8f2bf85b7b.jpg)

**Comment by ccshiro** [comment]
An explanation of what happened:
There's a small grace period after you use vanish, where in you're fading from visibility for other people. During this split second period you can still be hit by a spell (usually if they hit blind as you clicked vanish). If they do so, then your vanish will break (the buff gets cancelled) and you'll be fully affected by their spell.

Here's proof in case you're skeptical: https://youtu.be/hyYixOpAGC4?t=6

**Comment by Ickler** [comment]
What should be investigated is if this is something limited to ranged instant spells without travel time only. Because that's the only scenarios of which I can recall this happening. However on Corecraft any melee ability spammed can "break" vanish. Which pretty much makes vanish extremely unreliable, borderline useless in many situations.
Would make a lot more sense if this so called "grace period" didn't apply to melee attacks and abilities.
