### ISSUE TITLE
Durability loss in Arena?

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#2334]
I sort of remember having to repair back on retail after having played a lot of arena games, think it should be that the hits/damage you receive from players will damage your gear but dying from players will not.

Anyone else remember something like this? Couldn't find anything when I researched.

**Comment by Ickler** [comment]
I can back this up, don't really have any proof except for a 100% super clear memory...

My longest ever 2v2 match, lasted 5 hours 40ish minutes. At which point we lost because nearly all my gear was red. It was a druid / hunter mirror -_- Never has helping a friend on the same LAN been more annoying.
