### ISSUE TITLE
earth shield healing puts shaman in combat

### ISSUE THREAD

**Issue by dmsolow** [ccshiro/cc-buglist#239]
If a resto shaman puts earth shield on an ally, and the ally enters combat and takes damage, the healing done by earth shield puts the shaman in combat. 

I know that for a long time on live, earth shield healing was not credited to the casting shaman at all (so it would not show up in healing meters). I don't know how this worked in 2.4.3, but I'm certain that it didn't put the shaman in combat

**Comment by KuroiKensai** [comment]
He is right. 
Patch 3.0.2 (14-Oct-2008): Earth Shield threat is now added to the healer. Previously the threat was added to the target being healed.

**Comment by DeeMarie** [comment]
#240

**Comment by ghost** [comment]
Ok, so you are reporting multiple bugs:

1) Earth shield healing gives threat to the shaman instead of to the shield target
2) If shield target and shaman are both out of combat and the target gets in combat and takes damage, then the healing event puts the shaman in combat
3) The healing event does not credit the shaman (so doesn't show up in healing meters).

For 1st I agree it's a bug, evidence from 3.0.2 patch nodes.
For 3, it makes sense to be a bug, prolly need to look over some videos.
For 2 I am not sure, it sounds about right. Being in combat does not imply you have threat (e.g. pulling a raid boss puts everyone in combat). The heal should not give threat to shaman but I think it's correct to put shaman in combat. Again need to look over some videos.

**Comment by dmsolow** [comment]
You're wrong, it should not put the shaman in combat. 1 and 3 are not important bugs in my opinion.

Pulling raid bosses is irrelevant because that's a special case. During part of vanilla WoW, you could have some healers remain out of combat during a raid boss and rez people who died instead of healing. Forcing everyone into combat prevents this tactic.

Earth shield is sort of a weird spell. You can't heal allies who are dueling, but you can put ES on them before the duel starts. And the healing done during a duel won't put you combat.

**Comment by ghost** [comment]
Ok, I have found some videos to confirm it should not put the shaman in combat, it's from early wotlk but still https://www.youtube.com/watch?v=KYBu6M__Uvw#t=3m10s ; you can see the shaman drinking and the rogue getting healed by earth shield proccs

For 1, it is as equally as important because earth shield and prayer of mending were used in TBC for initial aggro gain in 5mans so are necessary mechanic for tanks and healers. I wonder if similar bugs can be observed for prayer of mending here.

For 3, I assume it might be an issue with the string parsing in the combat log, needs research.
