### ISSUE TITLE
Shiv energy on immune

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#24]
Report:
"Shiv energy on immune
https://www.youtube.com/watch?v=eWof214huCM&feature=youtu.be
RETAIL VIDEO
https://www.youtube.com/watch?v=Ba6Ty72eSH8 (6min:0sec / 7min:20sec / look it with slow speed)
Here other video(season2) but rogue are on adrenaline rush, you can see him spam shiv on icebloc)
https://www.youtube.com/watch?v=mBWnrYbFRPE (4min50sec)"

Note: The report claims that shiv should not consume energy on immune. However, the first video both at 6 minutes and 7:20, if you slow it down to 0.25 is actually _not_ shiv from what I and nim saw, but poison.
In regards to the first video:
At 6:00 you can see him pop sprint, enter GCD and start spamming shiv. However, the immune message is before the GCD is over (from poison?) and his shiv goes off late, and seems to be absorbed (and cost energy).
At 7:20 he spams shiv, but it seems to not go on cooldown, and again the immune message is probably poison.

In regards to the second video:
He seems to be variating between clicking shiv and hemorrhage. He does also lose some energy (does not seem to be enough for the 20 that Shiv costs?)

Looking for further evidence about this report.

**Comment by Skillboi** [comment]
Everything used on immune targets consumes energy and combo points and theres no reason to believe shiv doesnt as its a normal ability that just has a BONUS of applying poison from it. Ofc ill be looking for evidence but the claim itself doesnt make sense.

**Comment by kolchax** [comment]
The videos show that it consumes some energy but not the full cost of the ability. Weird..

**Comment by Walter1007** [comment]
https://www.youtube.com/watch?v=pgXZuyxpAYA  at 2:38 (slow speed 0.25) you can see 1 hemorrhage + 1shiv (during tbc my brother always spam shiv on icebloc that was like a "yoyo" consume like 5-10 energy and bring back it instant (like you can see at 2:38) ) sorry for my english i hope you can understand what i mean

**Comment by Raiilan** [comment]
as Walter1007 says,  this video https://www.youtube.com/watch?v=pgXZuyxpAYA  

As i can see the shiv consumes from 88-83 ( 5 energy) when the rogue Shivs the icebloced mage.

dont know if the rogue talent "Quick recovery" have a part here to.
but i think it was a shadowstep speced rogue in the Video so that is not possible. 

"quick recovery"
(All healing effects on you are increased by 10/20%. In addition, your finishing moves cost 40/80% less Energy when they fail to hit.)

**Comment by Whatsthis880** [comment]
Raiilan that's right, he can't have the talent "quick recovery" as he is using "Shadow Step" during the duel, which requires 41 talent points in Subtlety, and "quick recovery" needs at least 21 talent points in Assassination. So that is not possible as we've got 61 talents points at level 70.

**Comment by Walter1007** [comment]
i got another example but this is woltk(season5)http://www.warcraftmovies.com/fr/movieview.php?id=96763 (11min40sec)

 you can see rogue spam garrote with shadow dance on IB (consumme 5energy and bring back energy so rogue can spam it on immune without lose energy )

that was exactly the same principe for shiv or hemorrage on immune like here https://www.youtube.com/watch?v=mBWnrYbFRPE  (4min50sec)

**Comment by ccshiro** [comment]
That's interesting, especially that it seems to not only be shiv. Perhaps that means it's a general thing, if the spell was immuned only 5 energy is consumed?

If we assume that is the case, a follow up question would be: does this only happen for rogues & druids (I will assume they work the same in cat form), or does this extend to for example warrior's rage?

**Comment by Lest26** [comment]
Rage attacks on immune targets videos:

https://www.youtube.com/watch?v=tvqww3G8s_U  or  http://www.warcraftmovies.com/movieview.php?id=42348
28:01
Hamstring consumes 2 rage on immune. He's wearing battlegear so hamstring's cost is 10 -3 = 7 (18:01 for proof hamstring is costing 7). (from  14 to 12 rage) His health also stays at 9782 so he didn't get hit.
30:38
Pummel has a 10 rage cost and also consumes 2 rage on immune. (from 11 rage to 9 rage) His health stays at cap so he didn't get hit.

Misc: 16:58 regen BG buff dropped on +combat/charging

https://www.youtube.com/watch?v=Z_4QCCzInVs  or  http://www.warcraftmovies.com/movieview.php?id=51295
7:05
Just before he gets up to him the mage hits him up to 41 rage, then ice blocks. The combat log shows MS hits him while immune and his rage doesn't move from 41 until he uses commanding shout (-10) a little later and is at 32 rage showing he has Anger Management.
"Your Mortal Strike failed. Mupps is immune"

I think it might be working this way since nothing can really become immune to the MS effect in the way blessing of freedom would make Hamstring's slow immune, or a boss being immune to pummel's interrupt. I assume equally generic abilities like Bloodthirst would also work this way.

Misc: 2:18 The immune attack is shown to be deep wounds in the combat log, but it also shows that the mace stun effect gives rage even if they're immune.

**Comment by ccshiro** [comment]
@ Lest26 thank you for those videos.

**Comment by ccshiro** [comment]
There are still some questions in regards to this mechanics. If anyone could find anything of the following it'd be great:

Immuned sinsiter strike or backstab.
Some immuned druid feral ability (to make sure it's a general thing).
Immuned finishing move (preferably not KS).

**Comment by Ickler** [comment]
I found this: It appears that the druid shapeshifts into Cat, gets Furor (40 energy), then 1 instant tick of energy brings him to 60, then uses Shred (42 energy cost) and only appear to be losing 2 Energy (I have the downloaded movie, better to see details there...)

https://www.youtube.com/watch?v=3t8AwJDVes4#t=646

**Comment by Ickler** [comment]
Also found Sinister strike used on Iceblock, Spex's 2v2 movie (with Bigfatlp). I have the downloaded movie, but unsure if it's uploaded to stream anywhere.

**Comment by ccshiro** [comment]
Got PM'd these videos by Mustonen (thanks):

mutilate: https://www.youtube.com/watch?v=lhl-GOLhSew#t=85
sinister strike: https://www.youtube.com/watch?v=yE-bqlexN9Y#t=694
eviscerate: https://www.youtube.com/watch?v=f58HrzVc4Q4#t=88 (patch 2.0.1)
backstab: https://www.youtube.com/watch?v=1d1eV3tcW4c#t=49

**Comment by Ickler** [comment]
So I uploaded the two movies I referred to to my Youtube acc, the Spex movie's quality was somewhat bad, but it shows sinister strike into IB at: https://www.youtube.com/watch?v=hTcTzCqt7MA#t=490 He's at 45 energy -> Sinister strike leaves him at 37 Energy - Then shiv when IB ends and after that left at 22 Energy. 

Eviscerate into IB: https://www.youtube.com/watch?v=hTcTzCqt7MA#t=1819 Costs 35 Energy (full cost).

The Fat Cow shredding into IB: https://www.youtube.com/watch?v=tB0lXEgpLZU#t=1166

**Comment by ccshiro** [comment]
Thanks for the help with research everyone. I think I have what I need to implement this now.
