### ISSUE TITLE
[Warlock] Fellhunter spell bug

### ISSUE THREAD

**Issue by vexxedd** [ccshiro/cc-buglist#247]
![spell_nature_purge](https://cloud.githubusercontent.com/assets/10693653/5892987/fc0f1e6e-a4dc-11e4-8628-3b5e3a6ec333.png)
Devour Magic (Fellhunter spell) can be cast on friend/enemy even without any debuff/buff.
You should get the message "There is nothing to dispell" or something like this.

**Comment by ccshiro** [comment]
Other similar spells are checked client-side for that error message, which is what has led us to believe in the past that this is intended behavior.

**Comment by lorino** [comment]
I remember that when I played my warlock back on tbc retail, I had devour magic on autocast and was always on cooldown, even if nothing was to dispel. The tooltip says:
"Purges 1 harmful magic effect  from a friend or 1 beneficial effect from an enemy.  IF AN EFFECT IS DEVOURED, the Felhunter will be healed for 915 (rank 6)"
So Devour magic is not like Priest Dispel Magic or Paladin's Cleanse, which says nothing to dispel in TBC, which was "fixed" (wasn't a bug, worked as intended ) on WoTLK, which those spells worked as Devour Magic in TBC so you could spam them even if nothing was there to dispel.
So devour magic, IIRC is working as intended here

**Comment by vexxedd** [comment]
I will prove, that you are talking bullshit, as soon as I get home with billions of retail videos.

**Comment by Klimpb** [comment]
The "if an effect is devoured" part probably refers to if the spell would miss/resist.

Proof: http://webmup.com/A7GSe/ (watch in full screen)

@ 0:07-0:11 watch his focus target gaining the shadow trance buff and the pet literally instantly(same frame) dispels the target.
This proves that if devour magic is on auto-cast and there are no buffs to dispel on the target, the pet won't cast it. But the pet will use devour magic instantly when there is something to dispel on the target.

You can also read the text in the beginning of the video

Quite a powerful spell indeed.

Still not sure about if it would go off if you casted it manually but I assume it would not?

**Comment by ccshiro** [comment]
@SuddenDeath Note that the report is only about when you manually press the spell. The auto-cast AI indeed only uses it if there's something to dispel (but that already works as such).

**Comment by Klimpb** [comment]
@ccshiro hmm, could be quite difficult finding proof for that though. I'll look around a bit.

**Comment by harbie** [comment]
This well be hard to find, but I do remember that if you use devour magic on a party member it'll put them in combat (if your in combat obviously). So, if you vs RD as LD and your druid is blinded and rogue is going to sap then you could devour magic, but I don't ever remember this happening you had to predict when rogue going to blind and bear form it. So, I think it is supposed to say there is nothing to dispel.

**Comment by Klimpb** [comment]
Patch 1.10.0 (28-Mar-2006): All spells/abilities that remove existing effects (e.g. Dispel Magic, Cleanse, Remove Curse etc...) will now verify that there is an effect that can be removed before casting.

Anything changed since then?

**Comment by exltus** [comment]
I found one discussion from april 2008, where are talking about this topic. There is clearly said ' "Nothing to dispel" message occurs if you use devour magic. [link](http://wow.joystiq.com/2008/04/24/blood-pact-tanking-leo/) Next I found a lot of cata discussions, where are talking about it too. You can read a lot about "Nothing to displel" call in this discussions : 
[link](http://us.battle.net/wow/en/forum/topic/1127126315)
[link](http://www.wowhead.com/forums&topic=100716/pet-attack-macro)
Things has changed after turn of the year 2011/2012, because they made it only usable, and regarding to next discussion, that I found the call "Nothing to dispel" disappeared and spell was allways called and puted on cooldown. [link](http://us.battle.net/wow/en/forum/topic/3595342725)
so finaly words: THIS IS A BUG

**Comment by Iliana-sc** [comment]
The second and last link in @exltus post are from a patch that is too new, the dispell behavior had changed too much by then:

> Since dispels were made to be **usable even while a target has nothing to be dispelled**

In the blood pact link it's not clear if the comment is made by a warlock that actually knows the message comes up because he tried, or by someone who knows the debuff is not magic and assumed the message comes up.

The macro link is interesting though, it has rather good evidence that in patch 3.1 it was indeed showing the nothing to dispell message:

> The Devour Magic **macro** doesn't work as I wanted. When I select a person with a magic debuff **it says Nothing to dispel**. So I assume it means me, cause I didn't have any debuffs. Can anyone fix this?

Now we just need to test if the wrath client after 3.1 does the check client side. I don't have a wrath client though. Do you @SuddenDeath or @ccshiro?

**Comment by ccshiro** [comment]
@Iliana-sc Tried it in 3.3.5, it does still query the server even when there's nothing to dispel. So I guess this one really used to be checked server-side.

Thanks for the input guys.
