### ISSUE TITLE
Queues while off

### ISSUE THREAD

**Issue by Evolvee** [ccshiro/cc-buglist#2488]
![wowscrnshot_031216_154357](https://cloud.githubusercontent.com/assets/1942409/13862490/f55a085e-ec93-11e5-8715-0ba59fb600c7.jpg)

I have honestly no exp with that, so this is more like a question. I rly like this feature for disconects while in ranked que so you can get back into arena, but should it save ques longer than 14 hours?

repro: get into skirmish que, log off for few days, go back online

**Comment by somnu** [comment]
Thing is, once the server will be live you will never see this happen because people will queue and once the queue pops for you and you won't join (because you're logged off) you will lose it so it's not really that big of an issue. I remember the queue on retail held for a lot of time, even after logging off, but I don't think there is a way to say for certain for how long.

**Comment by Jumpka** [comment]
Might be somewhat related https://www.youtube.com/watch?v=cPthiiMeVVo

**Comment by ccshiro** [comment]
What @somnu says is how it works. If you're offline when the queue is ready to pop, you will lose your spot. As long as it doesn't pop, you'll keep your place while logged off.

**Comment by Evolvee** [comment]
so does this mean that if it pops while im disconected in ranked que, i wont be able to get into arena when i login? or i can get back until the time of pop ends
- another situation: i get disconected while it already poped
