### ISSUE TITLE
Multishot targetting

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#25]
Report:
"Multishot went way out of its range several times. Heres one example: http://imgur.com/kN3dXiz "

Another Report:
" http://oi62.tinypic.com/21ov8mq.jpg "

Note: We're looking for some research to figure out how wide the "cone" of multi-shot is / how exactly the targetting ought to work.

**Comment by DeeMarie** [comment]
Not sure if this helps:

http://www.wowwiki.com/Area_of_Effect

Cone spells (epicenter: player; angle: 90°) - Typhoon, Multi-Shot, Cone of Cold, Dragon's Breath, Shadowflame, Shockwave

**Comment by Barroth** [comment]
I think the calculation is based on the multishots Target instead of the caster.

http://www.youtube.com/watch?v=dKx0KsCNBH4#t=452

This cast has quite a big angle ~ 45 degree I'd say, which, at 41 yards range and if it works like a cone, means it could hit enemies which are 30yards away from each other.

It probably should be area based around the Maintarget, like:

cast at maintarget, check circle area with 10yards radius around that target. if sth is found the closes one is the 2. target and then it checks the circle area(10yards) around that target.

**Comment by Raiilan** [comment]
wowpedia says it's a chainspell?

Chain spells (epicenter: afflicted target; angle: N/A)
Multi-Shot, Avenger's Shield, Chain Lightning, Chain Heal

http://wowpedia.org/Area_of_Effect

Also i found this and thought i could share it:
- Multi-Shot: This ability will no longer strike any secondary targets which are under the effect of crowd-control spells that break on taking damage. i.e. Polymorph, Sap, etc.

http://www.gry-online.pl/S030.asp?ID=42773

**Comment by ccshiro** [comment]
Check this video: https://www.youtube.com/watch?feature=player_detailpage&v=ZZ7Op2oMzXw#t=125

EDIT: Barroth measured the distance, and it lines up with the chain jump workings.
