### ISSUE TITLE
Shaman Elemental  Overload talent does not proc as often as intended

### ISSUE THREAD

**Issue by jovce17** [ccshiro/cc-buglist#272]
I did some testing in terokar forest on adds ...and from around 10-15 mints of mobs killing i manged to get ONLY 1 SINGLE  overload proc
http://s9.postimg.org/m7r068i1b/Wo_WScrn_Shot_033115_215303.jpg
http://s21.postimg.org/hu358q23b/Wo_WScrn_Shot_033115_215306.jpg
from 45 casts ...only 1 proc ...that's not even 3% chance ...it should be 20%

**Comment by Samphtos** [comment]
TL,DR: I'm pretty sure it's working as expected and this is my proof. OP was slightly unlucky with his chain lightning tho and this spell should be tested with a bigger sample size.

So as I've also played some shaman on the tests and from my experiance this talent works, I will try to argue against this bug report.
I'll start with a question:
Why do you say you've only had 1 procc? I can't see any counter in your screenshots.

This is the description of the spell that we're discussing: (with 5/5 points in it)

Gives your Lightning Bolt and Chain Lightning spells a 20% chance to cast a second, similar spell on the same target at no additional cost that causes half damage and no threat.

We conclude that the "bonus-spell" deals half the damage of the main spell.

Lets now discuss chain lightning.

Looking at your damage meter for chain lightning, we see that the minimum damage and maximum damage for both hits and crits are very close to eachother with <10% more damage on the maximum hit compared to minimum. That likly means that no overloads procced from chain lightnings.
Now bear in mind that 11 casts of chain lightning is a very small samplesize. Using the formula for discrete probability distributions (feel free to try it in wolfram alpha ((11 choose 0) \* 0.20^0 \* (1-0.2)^(11-0)) ) we find that it is about 8.5% chance to proc 0 overloads from 11 casts. This is a very possible senario, OP may simply have been unlucky with his chain lightnings but a slightly larger sample size to confirm that chain lightning is working would still be suggested.

On to lightning bolt. 

This one is a little bit trickier. Judging from the damage meter, both hits and crits from lightning bolt has procced overload (since the min damage is roughly ~50% of the maximum damage). (Sidenote, it's not possible to be 100% sure overload procced since it could be partial resists but this is VERY unlikly) Now, to calculate the ammount of overloads procced, we apply some basic maths. Lightningbolt has, like most other spells, a damage range. The average damage displayed in the damage meter is incorrect (to low) as it includes the overload hits. To calculate the real average damage from a lightningbolt hit we have to estimate minimum damage to be 2 times the displayed minimum damage (the 50% damage hit from overload). This gives us average damage of a lightning bolt hit to be ((799_2 + 1770) / 2) = 1684. As number of overload hits is VERY low (again, a bigger sample size would be good) 799 is not expected to be at the very bottom of the damage range and the number 1684 is therefore expected to be slightly to big. Furthermore, OP may have had trinket proc etc for his max hit of 1770. To account for this, 1684 is slightly rounded down to 1650 for further calculations.
This gives us 1650 average damage of lightningbolt hit and 825 average for overload hit.
We know that the total damage from lightningbolt hits are 1523 \* 19 = 28937
We use this knowledge to calculate the ammount of overload procs from lightning bolt hits by solving the following equation:
825_x+1650*(19-x)=28937
This gives x = 2,93
This leads me to belive that 3 out of the 19 lightningbolt hits were acctually overload proccs.
Furthermore, this means OP did not do 19 casts, only 16 (as 3 are overloads). 3 procs out of 16 casts means 18.75% procc chance.
This is very close to expected 20% proc chance and applying same probability formula from chain lightning we find that 3 procs from 16 casts is more likly (25% likly) than either 2 hits (21% likly) or 4 hits (20% likly). Keep in mind that with this small sample size, neither 2, 3 or 4 (or even 1 or 5) overloads would proove the talent to be malfunctioning, the only conclusion we can draw from the above calculations is that it is likly working as expected.

To further investigate I've done the same calculations on OPs lightning bolt crits. This sample size is even smaller and should not be seen as any further evidence of the talent not working.
Same calculations gives us 3227 average critical hit damage rounded down to 3150 with same reasoning as above.
1575_x+3150_(13-x)=39338
Gives x = 1,02
This means that there were likly 1 proc out of 12 crits. 1/12 = 8.3% proc chance. This seems slightly low but the tiny sample size would still lead us to belive it to be correct as the probability of 1 proc out of 12 casts is 20.6%

**Comment by jovce17** [comment]
@Samphtos OR you could have JUst simply asked me ...i was specifly checking if it proced 2nd cast ....except for that ONE minimum dmg from lightning bolt there were no other overlaod procs 
The dmg difrence might be if i used or not used the air spell dmg totem trinkets etc
I did a bit more testing and it was procing roghtly on 3-5 mobs killed ..thats 10-15 spell casts ...srry no screanshot for that  ...i did test in pvp in duel i was attacking my friend with only lightning bolt ....it procced once on our 3rd duel that was around 15 casts also i doubt that i was ONLY unlucky 

I dont ask to trust me on this but atleast slap an "needs more reaserch" label

**Comment by Samphtos** [comment]
Well, I could have replied that you're wrong and that I have allready tested it. But instead I went with the approach of trying to explain to you why you can not assume it is bugged based on the evidence you provided.

Reporting bugs like this with such a tiny sample size is just slapping the developers in their faces giving them more job to investigate spells that you are to lazy to properly test. A sample size below 200 is simply not enough to draw any conclusions. And no offence but a real test would also include a correct count of the procs prefferably by some addon. You looking at your screen for procs is simply not enough evidence.

**Comment by jovce17** [comment]
yes i agree and i also said that it should get labeled as need more research and be tested on next test i didn't have time to test it properly alone.
and on your approach ...dude im not blind i was specificly watching and waiting for a proc .....it only proced that one time but i agree it needs more comprehenzive testing with better addon on more casts around 200 would be fine.

**Comment by Samphtos** [comment]
I'm not saying that you're blind. But simply looking for a proc will not rule out if its only a visual bug (which is also a possibility)

**Comment by NErlandsson** [comment]
I would just like to second what @Samphtos has said and add that based on your targets I'm guessing every 4-5th hit is a killing blow which would make it impossible to have proc on those spells.

**Comment by tedrasiel** [comment]
"I would just like to second what @Samphtos has said and add that based on your targets I'm guessing every 4-5th hit is a killing blow which would make it impossible to have proc on those spells."

bullshit, even if the cast "would kill" the target without overprocc it still can procc. the proc then flies into the lifeless corpse.

**Comment by tedrasiel** [comment]
cause the cast overprocs when the cast is finished casting, not when the cast hit its target and dealt dmg.

**Comment by tedrasiel** [comment]
the proc itself is just a 50% less powerfull version of the normal spell casted before. so its an indipendent lightning for example. it can crit even tho the main cast didnt and its dmg doesnt scale higher if (for exmpl) the main cast its triggered off critted or dealt more dmg than usual. its just takin the tooltip of the main cast and reduces the dmg by 50%, then spell etc are calculated for this one. 

on topic: 1 spell ot of over 40 casts sounds really low, but can also be hard badluck ofc. this needs further testing to be proven.

**Comment by ccshiro** [comment]
As @Samphtos says, to statistically test this spell the method would need to be revisited. I looked in our data and it's listed as 20% chance to proc, so unless something underlying is bugging the chance is correct.
