### ISSUE TITLE
Mind Control Threat

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#28]
So, turns out we missed an issue that needs research. Namely mind control in conjunction with threat. The points needing to be determined are:
1. Does the mob's threat table reset when he is mind controlled?
2. How much threat does the priest generate on the mob he mind controls? (*)

(*) In regards to question 2 we have found various sources speaking about it, but nothing conclusive. The various interesting topics we found are as listed:

Comment in Omen:
-- Mind Control
--605, 10911, 10912,
-- No known testing is done to conclude Mind Control threat values
-- Closest is http://elitistjerks.com/f31/t23307-priest_mind_control_threat_testing/ (**)
-- which is highly inconclusive. Wowwiki says "To this date it is not clear
-- precisely how much threat Mind Control causes, but it is very substantial"
-- MC threat is not a flat 5500 threat as Satrina's guide says.
Two posts discussing it:
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/93187-priest-mind-control-guide.html
http://us.battle.net/wow/en/forum/topic/1869409941#6
Some people even claim the threat is infinite, and not even taunt can bring it back to the tank (sounds very unlikely):
http://wow.allakhazam.com/forum.html?forum=243&mid=120302245470583552#8

(**) Wayback link for that thread: http://web.archive.org/web/20110509104657/http://elitistjerks.com/f31/t23307-priest_mind_control_threat_testing/

**Comment by Barroth** [comment]
Take from the Threatlist addon Diamond Threat Meter: 
   ["MIND_CONTROL"] = {     -- Non damaging ability
        class = "PRIEST",
        effect = {
            type = "ADDITIVE_THREAT",
            value = {
                numRanks = 3,
                -- Guessed
                [1] = 1500,
                [2] = 3000,
                -- Confirmed
                [3] = 5500,

Edit: Apparently omen says its not 5500 :/

**Comment by ccshiro** [comment]
This is only related to this issue by association, but I'll add it here anyway: http://wow.allakhazam.com/wiki/Threat_%28WoW%29#Taunting

**Comment by r00ty-tc** [comment]
Well, here's how I approached this. But we have to assume threat wasn't changed in 3.x (is there a reason to suspect it was?).

In 3.0, Blizzard made an addon API for reading threat info. Omen et al were updated to use this rather than their complicated lookup table. Which is good for us. We just need to find a video where someone MCs a PvE creature and has omen on screen and where the patch is >3.0.

I found one. https://www.youtube.com/watch?v=OEhJtXwc3bY at 1:25

You can see, it's a level 80, so at least 3.x. Just for a second at 1:25 after he releases Gamon you see threat = 247. Gamon's HP = 247.

So, my feeling is that it's likely the creature HP is the correct value to use.

I can't think of a way (short of a time machine, or storming blizzard offices and demanding source code) of getting a better answer.

**Comment by Barroth** [comment]
It could make sense, that upon mind controlling(taking full control of the creature) it gives the mindcontroller threat equal to its hp, aka threat equal to the amount of hp you "control"

**Comment by ccshiro** [comment]
I agree. We will roll with the hp theory for now, since it seems the most repeated and also has been backed up by some data in the various links in this thread.

Posting some stuff linked by Chulain:
10:38 <Chulain> http://file3.guildlaunch.net/93655/Killer%20Priest%20Guide.pdf
10:38 <Chulain> control + f "mind control is a fun"
http://vanilla-wow.wikia.com/wiki/Mind_Control
http://www.lurkerlounge.com/forums/printthread.php?tid=6826

I'll close this for now, and if new evidence that contradicts it comes in I'll reopen it. Thanks for the research help.
