### ISSUE TITLE
[70 Rogue] Pickpocket issues (very low success rate), mob levels 58-70

### ISSUE THREAD

**Issue by plebbb** [ccshiro/cc-buglist#284]
Pickpocket seems to enter you into combat most of the time on mobs which are green and above to you, instead of giving you a failure message of a miss/resist.  Not only that, when you do successfully loot from a stationary mob and are moving away, it sometimes even decides for whatever reason to initiate combat anyhow.  I seem to remember it being much easier do drive-by pickpocket runs of entire humanoid camps.  Grey mobs suffer from the same issue, but at a much lower rate.

Is pickpocket running off spell hit formulae, or physical hit?  This might answer my question.

**Comment by Ickler** [comment]
I can confirm this, it appears to be very low success rate. And no "miss" message. Afaik it should scale off of phys hit.

**Comment by ccshiro** [comment]
I think stealth is what's actually breaking, not pick pocket, with the combat initiation. Also, might be using wrong hit chance as @Ickler says. Will check.

**Comment by Ickler** [comment]
Yeah stealth breaks, but I can't tell if it just breaks, or if it breaks because mob is attacking me. I think mobs should have a chance to detect the pick pocket. I would speculate and say that should probably be a set amount based on the stealth level vs mob level perhaps, or just player level vs mob level? I know you can get "Miss", but in those cases mobs don't attack, and you don't drop stealth. 
So something else seems to happen here. I'm gonna read up a bit, see if I get any wiser.

**Comment by Ickler** [comment]
Can't find much on the topic of pick pocketing:P Lots of random comments on WoW head and other similar sites, nothing informative though. 

Only information I can find is from http://www.wowwiki.com/Pick_Pocket 

One thing I might add was that it seemed pickpocket didn't pick up the loot if you have auto-loot enabled. I don't have any addons that govern this, so it would be odd if it was only me that had this problem.

**Comment by jovce17** [comment]
hmmm as i remember it failing to pickpocket resulted to the mob detecting you and attacking you 
that happened while i was doing the poison quest on retail...when you had to do the pickpocket the key thingy.
probably only the success chance is to low here
