### ISSUE TITLE
Zeppelin not visible to all players

### ISSUE THREAD

**Issue by Tasserski** [ccshiro/cc-buglist#290]
This will be in story form so bear with me.

We went to the Orgrimmar zeppelin with a bunch of players. Stood around for around 10 minutes, saw no zeppelins. After the server crashed, we rolled back to Shattrath so I instantly ran back to the OG zeppelin. Just as I arrived, I saw the Undercity zeppelin leave - before the crash I had not seen any zeppelins at all.

After that Nim joined me in the wait and we waited for a little over 10 minutes. During this time, Nim teleported to Grom'gol twice - on the first teleport he saw the zeppelin docked there, on the second it was not there any longer.

Eventually, as I understand, the zeppelin did arrive at Orgrimmar and Nim was able to see it, but I wasn't. I simply saw Nim disappear as (if I understood correctly) he stepped into the zeppelin. I had not relogged or switched instances in between the wait. The zeppelins simply appeared invisible to me (and likely to my party mates earlier).

**Comment by rylaiii** [comment]
I had the exact same thing happen to me while i was waiting for the boat in Auberdine which leads to Menethil Harbor. waited 15 minutes for good measure.

**Comment by Voodopad** [comment]
Same as Rylaiii, waited for 10 min in Auberdine.

**Comment by r00ty-tc** [comment]
Unsure how relevant this is. But, I remember years ago (during actual BC on retail) I tried installing mangos and checking out the emulation for myself. This was one of the bugs from back then. So, I wonder if some of the changes to grid handling hasn't brought back this particular issue.

It was exactly this. Basically what would happen is. If the zeppelin was there (or at least in visible range) when you zoned in. You would see it. If you were in the visible area when the zeppelin was "teleported" into that area you would never see it.

It's get even more interesting. Because you would see other people able to get on the zep you couldn't see. If you tried you'd fall through the floor to them and to you (rightly) fall off the edge.

Probably it doesn't help fix the problem (unless there is commit text from that long ago somewhere showing what was changed and how it might relate to recent changes). But, I thought I'd mention it.
