### ISSUE TITLE
Spell: Wing Buffet (ID: 32914)

### ISSUE THREAD

**Issue by Tasserski** [ccshiro/cc-buglist#291]
Used by Vicious Teromoth (18437). Currently seems to dismount affected targets. Quite sure it shouldn't: not mentioned in the description nor the Wowhead comments, nor do I personally remember such a thing happening.

**Comment by ccshiro** [comment]
We made it so knockbacks dismount you. If you get knockbacked while on a flying mount the client "forgets" you're flying and you fall. Now, it's possible the outcome should be different; e.g., maybe you can't be knockbacked on a flying mount.

Anyway, seems like a very low prio issue that needs research.

**Comment by Platzwart** [comment]
Until Patch 3.3.0 knockbacks dismounted the player (from ground and flying mounts).
In the Patchnotes for Patch 3.3.0 they stated that knockbacks _no longer_ dismount players which can be found here:

"Knockbacks no longer dismount players. If on a flying mount, you will be knocked back a short distance before being able to resume flying."
http://us.battle.net/wow/en/game/patch-notes/3-3-0

And on wowwiki aswell:

"Before patch 3.3 WotLK, receiving a knock back could also cause a player to become dismounted from their ground or flying mount."
http://www.wowwiki.com/Knock_back

So no issue here?

**Comment by Tasserski** [comment]
@Platzwart you're right, should be no issue. I'd forgotten about making a report about it, but just run into the same patch note change you just linked while researching something else. The behaviour was indeed only changed in WOTLK.

**Comment by nz54445** [comment]
This is indeed the correct behavior, there are many sources (not to repeat the patch notes as well) that suggest this. In WOTLK the players got knockbacks, which were abused to dismount and kill flagged players.

http://wow.gamepedia.com/Knock_back

```
Patch 3.3.0 (2009-12-08): Knockback effects no longer dismount players. If on a flying mount, you will be knocked back a short distance before being able to resume flying.

    This change is most likely due to some players abusing their knock back abilities on flagged players leading them to fall to their death.
```

http://www.wowhead.com/forums&topic=153060/knocking-people-off-of-mount-with-typhoon-stat-question

By foleynuts on 2010/04/18 at 10:42 PM (Patch 3.3.3)
You cant knock people off their flying mounts anymore.
Read patch notes.
ClientPatch3.3.0: said:
Knockbacks no longer dismount players. If on a flying mount, you will be knocked back a short distance before being able to resume flying.

Including the above sources. Since it's correct behaviour as is on Corecraft (knockback DOES dismount) this issue can be closed.
