### ISSUE TITLE
Weird critter behaviour.

### ISSUE THREAD

**Issue by Wtfeater** [ccshiro/cc-buglist#295]
The Cows in the Hillsbrad farms have way to much hp (insignificant) and don't behave like they should. They will sometimes stop to evade for no reason and will sometimes reset even though you are attacking them. perhaps an issue with other critters aswell?

Critter in the picture might seem stuck in the wall, but I had them evade out in the open aswell.
![wowscrnshot_033115_221230](https://cloud.githubusercontent.com/assets/10584393/6929581/29180306-d7fc-11e4-945e-d2a66aaf86d9.jpg)

**Comment by ccshiro** [comment]
Our critter AI makes critters run away for a while and then evade back to their spawn position if attacked directly, which is true for rats and stuff, but maybe this shouldn't apply to bigger critters like cows or deers?

**Comment by teddys** [comment]
:DDDD

**Comment by Chulain** [comment]
"Critters are (mostly) harmless and low level.
Some critters, such as the rats in Deadmines and the Deeprun Tram, the Biletoads in Wailing Caverns, or Frogs (no, really!) will strike back at an attacker if the attack doesn't immediately kill them. "

also! 
"Critters can also be killed by Sleepy Willy, a non-combat small pet that is a quest reward from the annual Children's Week event."

http://www.wowwiki.com/Critter?oldid=1613967

---

extra: "Before Patch 3.2.0 (although it was not mentioned in the patch notes - the effect just occured) critters such as Sheep, rabbits , Gazelles, and Deer were able to be skinned. As of Patch 3.2.0, they can no longer be skinned. "

http://www.wowwiki.com/Critter

**Comment by nz54445** [comment]
I think MaNGOS default cows have some 3k hp for some reason (Remember that being the case on another private server).

@ccshiro I think the critter AI that you describe is the normal critter AI with the exception of some of the mobs that can attack, such as those mentioned by Chulain. The only fix here would be a fix on their hp.

As far as them evading out in the open, the only thing that pops to my mind is the notorious bug where you have to stand in the mob space otherwise they are stuck and just evade you (the mobs also don't move). But you're a rogue and the mob was moving so this should really not be a problem (this is probably a pathing related issue in that case).

**Comment by jovce17** [comment]
Hmm i dont see this relevant to the gameplay and having big impact on it ....
Leave it for post launch as long as it doesnt causes problems with the server stability it can be overlooked for now ... PPL the more we focus on small bugs like this the further server launch date goes in the future lets keep the bug reports to game play mechanics quests spells and things that will have impact on the overall game play

**Comment by nz54445** [comment]
@jovce17 I disagree, this is actually more important then it appears at first glance:

Let's assume that this influences other critters. A warrior can then use anger management in dungeons to keep their rage at 100 just by hitting it and letting it run around. Normally critters are rage batteries for warriors/druids, since you get rage from attacking them. Furthermore, if a critter can not die, this means that people can get stuck in combat for longer periods of time, thus being unable to drink/eat while doing a dungeon, if a critter is pulled.

In any case i doubt something like this is going on, so I also do not think that this is a high priority issue, but it's still worth checking out as it can have exploitable consequences in the game.

**Comment by jovce17** [comment]
@nz54445  the OP said only that he cant kill the cow because she has 3k HP and that she was constantly evading and resetting aka going out of combat all the time  ...he wasnt getting stack in combat  and he didnt mention about the small critters not being able to get killed aka unkillable 
this bug only makes them reset and evade  and that thingy wit warrs and druids was abuse ...and usually warss were doing b4 the start of the fight so they could start the fight with full rage  the rat was always getting killed during boss fight then he needed to find another one ...and on  and on 
 that was Still bug Abuse even on retail

**Comment by ccshiro** [comment]
@ccnim Did some checking, all that's really bugged is some critters having way too much health.
