### ISSUE TITLE
Capturing PvP goals

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#30]
"gaining influence at a PvP location should happen at a much slower rate if the player is mounted(eots,halaa,twinspire ruins, hellfire etc)
https://www.youtube.com/watch?v=14gSH_00LUQ low quality,sped up."

I think the report itself is probably correct; the main reason I add this to research is to figure out how the rate of capture changes when you're mounted.

**Comment by FurioCC** [comment]
With all respect, i found this statement absurd and totally contradicting what i remmember.
There's no any written proof in any of numerous battleground guides and strategy discussion topics.
Also i can't see any proof of the concept in the video - quality of video prevents you from seing if the're any other players nearby helping capturing objective and thus speeding up the process.
Probably easiest to test on live, which i can't do due to not having active acc.

**Comment by tedrasiel** [comment]
i just know that beeing on a flying moint, even if u where on the ground with it, didnt gained any influence at a PvP location. Anything else, aslong you've been standing on the ground (mounted or not), gave you exactly the same "slow" gain of influence. (if alone ofc)

**Comment by DeeMarie** [comment]
http://wow.joystiq.com/2008/01/07/the-art-of-war-craft-outdoor-pvp-part-ii-an-outlandish-war/

via Sergio - "Needless to say, players must flagged for PvP and not be in stealth or be otherwise invisible, while players on flying mounts must be grounded, in order for the slider bar to progress."

Nothing to suggest being mounted progresses the timer less than non-mounted.

**Comment by Bwayzoe** [comment]
It has always been my experience that being present at a contested world PvP objective while on a ground mount or a grounded flying mount will grant the same capture rate as being unmounted.

**Comment by Barroth** [comment]
Did a frame to frame analysis for two videos
https://www.youtube.com/watch?v=d3DXrSR08h4 showing mounted ticks
and http://www.arpunkt5.de/category/wow/ showing unmounted.

Both ticks gave the same progress, so its the same for mounted/unmounted

**Comment by ccshiro** [comment]
@Barroth Thank you, will close this as not a bug.
