### ISSUE TITLE
Quest - Blade's Edge Mountains - Did You Get The Note?

### ISSUE THREAD

**Issue by sandfury** [ccshiro/cc-buglist#305]
http://www.wowhead.com/quest=10719/did-you-get-the-note
http://www.wowhead.com/item=31120/meeting-note

It appears that the quest item drops at 100% rate from every mob related to the meeting note (however I'm uncertain whether that started happening after I accepted the quest itself or not), but according to wowhead's statistics and user comments I can conclude that shouldn't be the case.

![wowscrnshot_033115_205332](https://cloud.githubusercontent.com/assets/11744594/6930726/1f174e20-d806-11e4-89c8-b060bd0773aa.jpg)
![wowscrnshot_033115_205330](https://cloud.githubusercontent.com/assets/11744594/6930727/1f1b20b8-d806-11e4-9f2f-57f5aeac4499.jpg)
![wowscrnshot_033115_205328](https://cloud.githubusercontent.com/assets/11744594/6930728/1f1de5be-d806-11e4-8e39-61b7f4e49228.jpg)

**Comment by n0psled** [comment]
Based sandfury. Great finds! Nice!

Best regards.

**Comment by ccshiro** [comment]
This item does actually have a 100% drop rate, the guy in the comments just didn't fulfil the drop criteria. However, we do have a bug with starting quest items dropping while you already have the quest accepted. I will close this issue however since we are already aware of the latter, and it's not only this quest.
