### ISSUE TITLE
Crowd Control and running out of range

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#31]
"Sheeped monster doesn't evade if you run away so you have to wait the full duration till it drops combat"

This report could use some investigating to determine how it ought to behave. Also, if it turns out correct, would being in a dungeon disable this mechanic (I'm inclined to think it would)?

**Comment by Schaka** [comment]
I remember this specifically, but cannot currently provide any proof. After you went out of their aggro range, the CC broke and they went into evade mode, running back to whereever they spawned.

**Comment by netherspite** [comment]
I've played mage a lot. I can confirm Schaka's words.
It is also logical: since you get out of combat, the mob gets out of combat as well and should evade, thus removing any negative effects (including Polymorph).
Tried to find some proofs yesterday but could not find any.
Regarding the dungeons: since mobs never evade in dungeons, you should not get out of combat, the mob should not evade and the debuff should not get removed.

**Comment by solowt** [comment]
Tested on live.  

Sheeped monster loses polymorph and evades if you get far enough away.  This occurs almost exactly when the monster is far enough away so it's no longer drawn on your screen.

I doubt this has changed since TBC but I don't know for sure as I didn't play wotlk->mop.

It does feel right though.

**Comment by tedrasiel** [comment]
"Regarding the dungeons: since mobs never evade in dungeons, you should not get out of combat, the mob should not evade and the debuff should not get removed." youre completely right with this. also when sheep breaks, the mob will start aiming for you, no matter where you are in the dungeon.

**Comment by netherspite** [comment]
Unless you're not on the top of his agro list

**Comment by Lobogo** [comment]
Tested on retail, can confirm this:
"Sheeped monster loses polymorph and evades if you get far enough away. This occurs almost exactly when the monster is far enough away so it's no longer drawn on your screen."
for dungeons:
If you sheep something and you have aggro, the mob always stays in combat with you. Even if you try to run the whole distance of the instance, after the sheep breaks, it will chase you, have aggro on you the intire length of what you run, untill you exit the instance.

**Comment by ccshiro** [comment]
Fixed, should work as described in here now.
