### ISSUE TITLE
Enslave Demon 

### ISSUE THREAD

**Issue by Owsikchaosue** [ccshiro/cc-buglist#310]
Enslave demon dont give melee and casting speed reduce and after enslaved he dont is like ur pet
u cant soulink him and some Demo talents dont work on him

**Comment by ccshiro** [comment]
We had some reason to think it shouldn't, but I have no idea why. Some research needed.

**Comment by nz54445** [comment]
http://www.wowwiki.com/Enslave_Demon

For reduction of melee and casting speed, it should be clear on this page that:
3.1.0 (14-Apr-2009): Spell haste penalty reduced by 10%. Melee haste penalty reduced by 10%.; Warlocks now innately have an increased 10% spell hit chance on the Enslave Demon spell.

Since: 
Enslaved
While enslaved, the time between the demon's attacks is increased by 30% and its casting speed is slowed by 20%.

This leads me to believe that the correct reductions are 40% and 30% respectively in TBC.

Furthremore:

http://www.wowwiki.com/Patch_2.1.0

Demonic Knowledge: This ability will now work with enslaved demons. 
Soul Link: Adjusted tooltip to explain that the damage transferredto the pet cannot be prevented. The functionality remains unchanged. This ability will now work with enslaved demons. 

And some comments from wowhead:

rlyeh on 2007/07/19 (Patch 2.1.3)
From my experience as a lock in Mech and enslaving Makazradon for fun and profit, I can tell you that my demonic knowledge bonus from enslaved demons is craptastic. It's almost always between 40-50 spell dmg. Compare to the 150 I get from my imp. But hey, at least it's 40-50 dmg MORE than we used to get from this! I wish we could enslave other players' demon pets in the arena (then sacrifice them of course).

Zeshar on 2007/05/16 (Patch 2.0.12)
It works much like Mind Control, in that the level of creature you can enslave increases as your level increases. At level 70, this spell would let you enslave a demon up to level 74. Also some good news from the 2.1.0 patch: "Demonic Knowledge: This ability will now work with enslaved demons." "Soul Link: This ability will now work with enslaved demons." With these changes, a very viable option for Demonology Warlocks is to run around with Demonic Sacrifice and an enslaved demon.

By Greytusks (579 – 1·8) on 2006/12/08 (Patch 2.0.1)  
Enslaved demon do not get benefits from your demonology talents except Improved enslaved demon. Nor does it benefit from scalability or give you boost via demonology talents.

So it seems to me that the demonology talents started being (mechanically) effective since 2.1 patch

**Comment by ccshiro** [comment]
@nz54445 I see, thanks.

**Comment by ccshiro** [comment]
Fixed soul link, can't do anything about Demonic Knowledge until #422 is fixed.
