### ISSUE TITLE
[Spell][DR] Feral Charge wrong DR category

### ISSUE THREAD

**Issue by braide** [ccshiro/cc-buglist#317]
Feral Charge shares DR with Entangling Roots right now which it should not.
Here is a link to the same issue on Feenix Archangel bugtracker: https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2938
I'll quote the feenix issue: 
"To back this up I have digged through just about every druid TBC PvP movie until I stumbled over this clip http://www.youtube.com/watch?v=hS82JzE6F0I&feature=player_detailpage#t=351s
What happends is that at
05:55 the rogue gets rooted by Nature's Grasp and now has controlled root DR for 15 seconds. at
06:00 the druid feral charges and applies Feral Charge immobilize debuff, at
06:04 the debuff fades. Which means even though the rogue still had Controlled Root Dr for 10 more seconds when the immobilize was applied the immobilize was still full duration. Clearly they are on different DRs."

I can try find more evidence if it is needed, there is probably a lot of other vidoes with this scenario. In the feenix issue it says that Feral Charge does not share DR even with itself. I think this is correct but I'm not sure the evidence is enough. Might need further investigation.

**Comment by Isuel** [comment]
i can confirm, charge shouldn't share DR with roots.

**Comment by ccshiro** [comment]
The video definitely proves that entangling roots doesn't share DR with feral charge's snare. It'd be nice to find if feral charge has any DR at all, though.

**Comment by braide** [comment]
No DR at all would mean that 4 druids would be able to keep a character at the same place forever, which seems a little unbelievable to me. 15 sec DR would mean that one druid will never notice a DR anyway (since the spell has 15 sec CD). DR on itself feels the most logical, but that's just my opinion I guess...

**Comment by Shakeandbake** [comment]
I believe it shared DR with other immobilize effects not removed by damage such as improved wing clip. Although I cannot remember any instance while playing a feral druid on retail where the feral charge duration was not the full 4 seconds.

**Comment by ccshiro** [comment]
@braide DR is 15-20 seconds (or more correctly, DR is 15 seconds, but DRs that have expired are only pruned every 5 seconds), so in theory it is possible to notice, just not very likely to find a video of it.

**Comment by teddys** [comment]
http://www.youtube.com/watch?feature=player_detailpage&v=WsZjTVcQyWw#t=593s

wingclip, improved hamstring and entrapment are all random roots
charge is something more like a counterattack(does that dr with random roots?)

**Comment by ghost** [comment]
Author of the Feenix report here, glad to see someone tested this, very important issue in my opinion and I really hope CC fixes it unlike other private servers. I have done some more research into this and I've found evidence that feral charge completely lacks DR. Check this video:

https://www.youtube.com/watch?v=PYWw7e97bmw specifically at [14:14](https://youtu.be/PYWw7e97bmw?t=854)

The priest gets charged by the other feral druid and 3 seconds later Azoth charged the priest applying a full duration feral charge. Interesting to note is that it does not replace the previously applied feral charge. Similar thing happens at [15:49](https://youtu.be/PYWw7e97bmw?t=948) when Azoth charged about a second before the other druid, and you can see the second druids application expires a second after. It happens again at [19:40](https://youtu.be/PYWw7e97bmw?t=1180). The other druid charges the warrior (it's a bit hard to see it happens behind the pillar but you can see the debuff). Azoth then charges the warrior 4-5 seconds later applying a second full duration immobilize. You this example you can also see that the warrior is clearly immobilized for the full duration dispelling any doubt that this would be an interface error or the like.
Also [23:03](https://youtu.be/PYWw7e97bmw?t=1386) [26:48](https://youtu.be/PYWw7e97bmw?t=1607), I kind of struck gold with this video.
Conclusion: Feral charge does not share DR with itself. I can only assume since there is no other CC that doesn't share DR with itself that it also does not share DR with any other CC.

**Comment by braide** [comment]
Only problem with those videos @caffeinez linked is that they are outdated. It's a very early patch as the terrain in the arenas show and blind here is a poison (pre patch 2.3.0). Sure if you look at the logs of feral charge no changes are made about the DR, but there were undocumented changes as well. Would be nice with a 2.4.3 video of 2 druids feral charging same target :)

**Comment by ghost** [comment]
Yeah it's not ideal I guess, but I don't think there any precedent for DR changes not being documented, Wowwiki usually documents everything including undocumented changes. I've went through them before and the only change about feral charge is about the immobilize and interrupt resisting separately.
All the other DR changes atleast pre/mid wrath are documented here:
http://www.wowwiki.com/Diminishing_returns

If you know of any other sources for patch logs let me know and I can check through those as well.

These threads both list feral charge as not DRing with itself. I think they're both as recent as Cata/MoP:
http://www.arenajunkies.com/topic/227748-mop-diminishing-returns-updating-the-list/
http://eu.battle.net/wow/en/forum/topic/7339014515 

So if it didn't DR pre say 2.3 and also not pre/during 5.0~ I think it's kind of unlikely it changed AND reverted feral charge without any mention or documentation. I mean it would be different if in wrath it shared DR with a bunch of stuff and we only knew it didn't in 2.3 then we would need confirmation it didn't change before or 2.4.3.

Anyway I think the assumption should be that it does not DR with anything at all including itself, since all evidence point that way. There's only so much retail 2.4.3, (I've looked through a lot by now ,) that I think it's unlikely we'll find any definitive proof one way or another, I think we're lucky to have Azoth's video to give us any retail  TBC video documentation.

**Comment by ccshiro** [comment]
@caffeinez That's some really nice evidence you've gathered there. Thanks for sharing. I think this looks fairly compelling to Feral Charge not having a DR category at all.
