### ISSUE TITLE
Imp. Drain Soul

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#32]
Drain Soul's tooltip read:
"Drains the soul of the target, causing X Shadow damage over 15 seconds. If the target dies while being drained, and yields experience or honor, the caster gains a Soul Shard. Soul Shards are required for other spells."

Improved Drain Soul reads:
"Returns X% of your maximum mana if the target is killed by you while you drain its soul. In addition, your Affliction spells generate Y% less threat."

The question (stemming from a report) is should imp. drain soul's mana return proc when:
a) A party member scores the kill
b) Your pet scores the kill

a) seems unlikely given the tooltip (although you never know with wow tooltips), b) seems more probable, however.

**Comment by DeeMarie** [comment]
http://www.wowwiki.com/Improved_Drain_Soul?oldid=808692 - Revision as of 20:04, August 10, 2007 

"In order for this talent's mana return to activate, the warlock or its minion must land the killing blow, which can be tricky in groups."

**Comment by ccshiro** [comment]
Mustonen linked me these two links:

http://www.wowwiki.com/Warlock_tactics?oldid=1625177
"Improved Drain Soul is an ideal ability for regaining mana. If you don't often rely on it other than for soul shards, it is a good strategy to cast Drain Soul on a mob right as it is about to die for a quick restoration of 15% of total mana, which can take a considerable amount away from downtime after a fight. The downsides to this is that it needs to be channeled while the mob dies, meaning you need to rely on your pet or party members or a DoT to kill it (something that must be considered if you are Destruction specced or dislike relying on DOTs), and that the spell takes up a considerable amount of mana to cast, which can be resolved by casting Drain Soul (rank 1) which is a cost of a mere 55 points."

http://vanilla-wow.wikia.com/wiki/Drain_Soul
"Combined with the Affliction talent Improved Drain Soul, you can gain back lots of mana for free simply by casting Drain Soul at the end of a fight. This is applicable both while playing solo and in a party or raid, as long as the target is struck first by a member of your group."

**Comment by DeeMarie** [comment]
There's this to suggest b) is correct.

http://wowmb.net/forums/f9/29748-improved_drain_soul/ - October 2008

This talent has two parts to it:

```
Mana returned:
```

There is a little bit of confusion between some Warlocks in regards to the killing blow part of this talent. Just to clarify, for the mana return the killing blow does not need to be made by Drain Soul itself, however it does need to be made by you. So long as it is one of your spells that lands the killing blow, you will get the benefit.

```
Threat reduction:
```

The second part to this talent is the threat reduction of all your affliction spells. The threat reductions is constant and passive so you do not need to worry about activating anything.

**Comment by Ickler** [comment]
I think this should fall in under the same thing as Spirit Tap for priests, Remorseless for rogues, Victory Rush for warriors and the Rapid Killing for hunters. 

As far as I can remember those should all be requiring to land the last blow. About the pet though, that could be possible.

**Comment by Mustonen1** [comment]
http://www.wowwiki.com/Drain_Soul?oldid=1576634

"Combined with the Affliction talent Improved Drain Soul, you can gain back lots of mana for free simply by casting Drain Soul at the end of a fight. This works best when playing solo since you or your pet needs to land the killing blow."

http://vanilla-wow.wikia.com/wiki/Drain_Soul
This one can probably be ignored since it seems to be a private server repository.

**Comment by Raiilan** [comment]
As a start i have played/lvled several affliction warlock/s since vanilla till wotlk on retail.
And i remeber it as yesterday that i did rely on this talent when "Grindlvling" and that i got my mana return 100% of the kills as long as no other Player/source of damage interfered.

( I know you want Videos as proof but i dont have it for now) 

Im 100% sure that Imp.Drain soul returns mana when the warlock OR his pet does the killing blow regardless if in group or solo. And the rumor that the "drain soul" spell itself needs to do the killing blow is FALSE.

Imp. Drain soul does not return mana if another "source of damage" than the warlock OR his pet  does the killing blow. so if a partymember does the killing blow there wont be any manareturn.

**Comment by ccshiro** [comment]
Thanks for the input, should work correctly now.
