### ISSUE TITLE
Invalid herb

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#335]
Sometimes the herb stays after being herbed and if you click on it again you will get the error "Invalid Target".

**Comment by shadowraider** [comment]
i may know where is the problem, have been looking for this many times and the conclusion i found was that game object activate (click) range is 1 yard larger than loot range, so if you are staying in this 1 yard radius, you can click on it, but will not get any loot because you are out of range of the loot

how to reproduce? go to a herb, find the gameobject activation outer edge by walking back and forward (slowly), try to click it and in 100% cases you will not get any loot

**Comment by netherspite** [comment]
It happens also for gameobjects, I've reported it after some of the previous tests.
It is related to the range, yes.
If you attempt to loot the gameobject at the max possible distance it will end up like this.
