### ISSUE TITLE
Create Healthstone recast

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#34]
"Create Healthstone can be cast if a healthstone of the same rank is already present in the Warlock's inventory. Creating a second healthstone will consume mana and a soulshard, but the second healthstone will not be created in the inventory."

Spells like create soulstone for example, do indeed error out when trying to create another of the same item, so it'd seem natural create healthstone would do the same. However, its spell data and implementation is a tad bit different which makes it fall outside of the generic category that the former mentioned spell is in, making me question if it did indeed function like this on retail. All in all this seems like a fairly minor thing, but I thought we might as well put up the research topic.

**Comment by r00ty-tc** [comment]
http://www.wowwiki.com/Patch_3.0.8

Create Healthstone: Attempting to create a healthstone when you already have one no longer consumes mana or triggers the cooldown of this ability.

This suggests that prior to 3.0.8, it did indeed cast and consume mana, but not produce a healthstone.

No mention of soul shard though there.

**Comment by Bearmanpig** [comment]
I was the one who made that report, but it seems my information was inacurate (I remembered it like it was in WotLK). Still, it makes sense and it's propably a bug overlooked by Blizzard for quite some time.

Either way, we want a blizzlike server, so it's working 'as intended' at the moment. Still not sure about the soulshard, can't find anything on the internet archive either. But seeing it used to trigger cooldown and use mana I'd say it would use a soulshard as well, since that's listed in the spell cost.

**Comment by ccshiro** [comment]
@pete318 @Bearmanpig Thanks. I will close it as working as intended.
