### ISSUE TITLE
Molten Core

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#412]

**Comment by ccshiro** [comment]
Our initial plan was to keep vanilla raids locked. Since vanilla raids are quite important still in TBC we've changed our decision. So I've begun work on implementing vanilla raids. As a first step I've implemented Molten Core.

The raid has been fully implemented and could definitely use some testing, if anyone feels like it. Since our systems are quite different from mangos at this point I've had to implement Molten Core from the ground up. I'm mentioning this because everything needs testing in the raid, even if it works by default in mangos.

(P.S. this raid is open and available atm on the test realm, if you feel like trying it out. P.P.S. You can PM shiro on irc if you need water for dousing or attunement completed.)
