### ISSUE TITLE
stealth - rog

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#435]
when a rogue stealthes while a pet chases him/her the pet shouldn't stop chasing the rogue and should attack when within range (didnt test with prowl)

https://www.youtube.com/watch?v=Q0O4RKeD4g4

---

burn rogues

**Comment by Sakatoro** [comment]
This is a typical pserver bug

**Comment by tedrasiel** [comment]
this is a fucking retail bug even blizz considered as one, im glad they didnt took it into cc. just lame and not fair at all.

**Comment by Chulain** [comment]
not fair? rogues are fair, right?

**Comment by Soyoen** [comment]
The video & comments is from mid to late vanilla content. Can't find any signs of changes throughout burning crusade content, in fact up until 2011 there were still discussion towards the issue.

"Ive been chased in the improved stealth effect provided by vanish several times by a pet. Its just rediculous when that happens. But as others have said, marks n all that shiz yo. "
http://www.mmo-champion.com/threads/972292-How-do-hunters-see-through-vanish

" That vanish problem has become so legendary that it's almost part of the game."
"...In PvP I've had the same problems with pets chasing you halfway across the map and as a lock I've had the pleasure (this time) of seeing it chase rogue's and pull them out of stealth for me..."
"Really bloody annoying tho and should have been fixed as a priorty. "
http://eu.battle.net/wow/en/forum/topic/1549666230?page=1

"well luckily there is a difference between mobs and pets, since pets are like players, can get out of combat after 5 sec non combat action in pvp, hence why some rogues are allowed to restealth. This is clearly bugged and blizzard haven't done anything about it, this bug implies to Vanish too. Fucking redicolous. Besides, you can't do distract when targets are in combat."
"when you stealth anything that had you targetted should lose its target, like players do, but for some reason the implementation does not remove the pets target so it continues to advance towards you and attack you even though you are supposed to be invisible."
- Comments from the linked video

The same mechanics can be found on LOTR boards within the timeline.
" At first it was random but now most weavers on our server have learned how to exploit a bug where their pet follows a burg in stealth after hipsing. Pretty game breaking for burgs in any group fight of course."
https://www.lotro.com/forums/showthread.php?411501-Pretty-sick-of-weaver-pets-following-me-in-stealth

So why does two seperate games mirror each other mechanics so closely, and why is no fix submitted from closed beta up until late 2011 (havn't checked post 2011). There has clearly been quite the outcry for a change against it (aka pet target loss), so either the develoopers thought of it intended or the issue would at that time take to much time to correct with more pressing concerns.

**Comment by vexxedd** [comment]
30 april 2006 
Daaat proof

**Comment by Chulain** [comment]
Actually soyoen's comments prove me right

If this still wasn't fixed in 2011 and blizzard knew about it, therefore this mechanic should be implemented.

It's not like seal twisting's case where it got well-known and fixed immediately in wotlk

**Comment by tedrasiel** [comment]
Ill check early wrath Videos for proof but im pretty shure it got "fixed" at the end of bc allready. Just not completely. As i remember it the pets sometimes dient follow, and sometimes they did ( and they got u out of stealth), later on, it happened not that often anymore and there was a time they sometimes followed you (while beein in stealth) but didnt attack ( This was, if i remember This issue correctly, "shortly" before it got fixed completely) . So in least situation, the hunt knew posotion of rogue and could get him out of stealth. And just think about this , its not like hunt allready got mark + flaire + aoe. Video footage to follow.

**Comment by ccshiro** [comment]
I thought this mechanics was already in. As I remember it, pets would let go if you vanished, but would keep chasing if you just stealthed.

**Comment by tedrasiel** [comment]
Shiro i think youre right

**Comment by tedrasiel** [comment]
ive made the research. Pet behaviour vanish related.

11:18 - 11.24 stealth - hunt/wl pet behaviour early wotlk. (vanish related)

http://www.warcraftmovies.com/movieview.php?id=122825&stream=&h=acc01f0a9d3d60a14072cb367bb31d45

---

04:10 - 04:15  12:18 - 12:24

http://www.warcraftmovies.com/movieview.php?id=107581

early bc: 

05:58 - 06:05

http://www.warcraftmovies.com/movieview.php?id=38775
