### ISSUE TITLE
WF totem + Paladin Seal of Command

### ISSUE THREAD

**Issue by Suomussalmi** [ccshiro/cc-buglist#44]
Hello, there is problem with WF totem, which is not adding another melee hit to Seal of Command when it procs. WF attack just give +1hit to your basic Auto attack(White hit), but if the WF and SoC proc is at the same time, the WF must give +1hit to the Seal of Command too, example: 1AA, 1SoC melee hit + WF = 2AA, 2SoC melee hit. So there is ingame screenshot how it works on CC test http://postimg.org/image/mbk4n2r75/ and there is screenshot how it must work: http://postimg.org/image/k1scjkgrn/ and some video from TBC arena tournament or next-gen wow https://www.youtube.com/watch?v=4O7cDzr8YxA .... thx for reading the report :)

**Comment by braide** [comment]
Arena tournament and next-gen wow are not reliable sources for this.

**Comment by Suomussalmi** [comment]
TBC Patch 2.1.0 (2007-05-22):
Mixing two different ranks of Windfury Weapon while dual-wielding will no longer increase the number of Windfury Weapon procs.
A bug with this spell was making off-hand procs receive less bonus damage than intended. It is now fixed.  
Notes: In Pre-TBC, a lucky shaman was able to one-shot Clothies with slow two-handed weapon if Windfury proc'd.
As to above,  [Windfury Totem] worked a lot differently back then as well. It used to give all party members windfury-like effect. This made Windfury Totem gave an unrealistic damage increase to melee classes (And especially those who wore two-handed weapons). 
Source:http://wow.gamepedia.com/Windfury_Weapon

**Comment by Suomussalmi** [comment]
Nothing about that the WF can´t proc on SoC melee attack, true that WF can´t proc on Mortal Strike for expample, but SoC is not the same ability as  the Mortal Strike is

**Comment by solowt** [comment]
I'm not familiar with this mechanic.

However I don't see how the patch notes you linked are relevant at all.  Shamans could one shot with WF weapon because WF weapon gives two extra attacks.  WF totem only gives one.

I believe SoC procs were treated like white attacks in some way...but I don't see why this means that you get a WF SoC and WF white every time WF procs on the same swing as SoC.  Frankly that doesn't seem logical at all so if you could provide evidence from retail please do.

**Comment by Suomussalmi** [comment]
I can´t find that much info about WF and Paladin on retail, cos nobody at that times played with shaman, maybe few peoples who didn´t want to release information. I played on many free servers where WF gives another swing to SoC. I know that free servers are not reliable that much, but if you try more than like 20private servers where WF gives to SoC another melee swing, that can mean it´s was scriptted good on this servers. 

I saw some topics that WF can´t proc on abilities like Mortal Strike, Sinister Strike, etc. But SoC is different ability. I mean the definition of SoC is: Gives the palading chance of dealing additional Holy damage equal to 70% of normal weapon dmg. So we can say, that SoC is giving to pala one more melee swing (white attack) + additional holy dmg which transfers this white attack to yellow attack.

**Comment by FurioCC** [comment]
Maybe I'm misunderstanding, but are you saying that proc of two independent chance-based abilities (not discussing percentages here) should automatically give you another proc just because they both procced?

**Comment by FurioCC** [comment]
http://www.wowwiki.com/Seal_of_Command_(old)?oldid=1400972
"The actual attack made when Seal of Command procs is resolved as a separate melee special-attack that deals holy damage. It is resolved identically to any Instant Attack -- it can miss, be dodged, be parried, and be blocked, and will do double damage on a crit (rather than 1.5x damage as a normal spell crit would)."

It clearly states that procced SoC atack is considered as any instant ability atack and thus shouldn't be proccing WF totem atack.

http://www.wowwiki.com/Windfury_Totem?oldid=1431588
"the totem acts in the same manner as Sword Specialization: It will ONLY trigger on white (auto-attack) swings, and cannot trigger off itself."

**Comment by braide** [comment]
Yeah as I thought. Ret/Sham has been stronger on private servers and people seems to think they're suppose to be. Double proc does not seem logical at all.

**Comment by Suomussalmi** [comment]
So that means, the Ret will be underpowered on CC, cos AA wf hit is not strong at all and without any reduce healing debuff you won´t be able to kill Rdruid for exapmple. The next thing is, when i was dmging the dummies in Shatt on Corecraft test, i´ve dodged WF attack 5times in a row to the target. And the next issue, why paladin resisting Holy dmg to the target? I mean, you hit with SoC and what happened SoC dmg 1503 (372resisted) for example. Why is this happening if there is no Holy resistance in whole game from Vanilla to WoD.

**Comment by FurioCC** [comment]
Dunno where you took concept that Ret paladins supposed to dominate 2v2.
In any case this discussion doesn't belong here and you can close the issue.

**Comment by ccshiro** [comment]
There needs to be some sort of evidence or basis provided for us to start investgiating claims like these. How it works on other servers notwithstanding.
