### ISSUE TITLE
Relogging while drinking makes character lose gear proficiency

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#450]
After relogging while drinking I lose proficiency to wear all the gear.
I become naked and my gear arrives back to me by ingame mail. However, I can't wear it until I relog again (while not drinking).
If I relog again while drinking I am still not proficient to wear any gear.
This is reliably reproducible.

**Comment by deltafoxnine** [comment]
I had the same problem twice :+1:

**Comment by whocares8310** [comment]
i also have video of this if we need it, but it also occurs when you are drinking and server crashes. Weapon/Armour Skills still show up in menu as being there/350 but require you to relog in order to put your gear back on.

edit: video added
https://www.youtube.com/watch?v=5GHEsRAPSz0&feature=youtu.be

**Comment by ccshiro** [comment]
That is one awesome bug.
