### ISSUE TITLE
Underbog: the black stalkers adds do not despawn upon boss death

### ISSUE THREAD

**Issue by PolarCookie** [ccshiro/cc-buglist#455]
We ran through UB and after killing last boss her adds did not despawn
had to run around knocking out 9+/- of them
harmless but shouldn't happen

https://www.youtube.com/watch?v=LVcRCGwNCVY
at the 20 sec mark boss goes down and all adds fade

**Comment by ccshiro** [comment]
That is intentional. It worked like that in 2.0.3, as you can see in this video: https://youtu.be/GtFAfZBLsXU?t=130

Whether or not we want to keep it can be debated I guess (probably was an oversight on retail, as opposed to trying to make people to focus adds). But we did it like that intentionally.
