### ISSUE TITLE
Warp Stalkers in front of Shattrath: floating corpses attacking incl. ability usage

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#471]
Hey there,

the Warp Stalkers in front of Shattrath, that should be in stealth all the time, can be seen for 1-2 seconds at range followed by a "vanish" for ~2 seconds - after, they're visible again and so on.

After killing them, the corpses floated, were not lootable and attacked me. Notably, the floating corpses still used their abilitys like sprint & this shadowstep-like warp.

![wowscrnshot_042015_233232](https://cloud.githubusercontent.com/assets/12044027/7245582/c45aa4a8-e7ed-11e4-91d1-ffe2cdaec8c9.jpg)

**Comment by nz54445** [comment]
Most likely related to #424.

**Comment by netherspite** [comment]
Got this issue as well. Seems it depends on when do you kill them.
If they use their Sprint or Blink ability (not sure which one causes the bug) and you kill them - their corpse starts to stalk you until you run far enough away to evade them. You can't attack the corpse yourself.
![wowscrnshot_042115_162156](https://cloud.githubusercontent.com/assets/5777848/7253302/4b01537a-e844-11e4-98bb-04fd81370321.jpg)
![wowscrnshot_042115_162216](https://cloud.githubusercontent.com/assets/5777848/7253303/4b020144-e844-11e4-8282-b33f09daab1f.jpg)
![wowscrnshot_042115_162315](https://cloud.githubusercontent.com/assets/5777848/7253304/4b051744-e844-11e4-8a3c-b79725f586b7.jpg)

**Comment by netherspite** [comment]
Some more observations:
- It is really depending on the location of the mobs rather than the state in which they were killed.
  Warp Stalkers farther from Shattrath are not affected by this issue while I was able to reproduce it on Timber Worg at the same location where bugged Warp Stalkers reside.
  ![wowscrnshot_042115_165102](https://cloud.githubusercontent.com/assets/5777848/7255304/04ac4dd2-e851-11e4-8a6d-b7ceec3243b2.jpg)
- When you relog after getting this issue, problematic mobs are not displayed as corpses anymore. However, they seem to be not in the place they are shown up.
  It can be seen on these screenshots:
  ![wowscrnshot_042115_165451](https://cloud.githubusercontent.com/assets/5777848/7255367/78c3f436-e851-11e4-986b-3146ea2d2c6c.jpg)
  ![wowscrnshot_042115_165454](https://cloud.githubusercontent.com/assets/5777848/7255368/78c574e6-e851-11e4-8057-ea4fd170f3b8.jpg)

**Comment by DaRealBoss** [comment]
As a hunter I've went to the warp stalkers outside shattrath to tame one during the test, and after taming it I would get attacked by an invisible warp stalker. After moving around a bit it comes out of stealth and i get the error msg of out of range or the target is dead when i try to use any moves on it or attack it. I didnt have time to test if other mobs react that way around shattrath when i tame them, but the warp stalkers around shattrath seemed to do that everytime.
