### ISSUE TITLE
[Druid] Nature's Grace talent

### ISSUE THREAD

**Issue by punker85** [ccshiro/cc-buglist#477]
The talent in the druid's Balance tree should give a .5 cast speed reduction on the next spell cast after a critical occurs.  Currently, if I am chain spamming a non-instant spell and a critical occurs, it will not reduce the cast time of the next spell unless I delay the start of the cast (not sure if this is intentional or a bug).  The real problem comes when I finish casting that next spell and the Nature's Grace buff disappears when it didn't even give a cast speed reduction to my rapidly spammed spell cast.  I can cast 2 Starfires in a row in rapid succession and if the first one is critical, the second one will still cast in 3 seconds and my Nature's Grace buff will disappear.  I had 5/5 Starlight Wrath talent also if that will make a difference in reproducing this issue.

**Comment by Barroth** [comment]
From wowwiki http://www.wowwiki.com/Nature%27s_Grace?oldid=1369517
"The Nature's Grace proc can affect cast time of your current spellcast, so if a wrath spell hits and crits while you are casting another, the effect of Nature's grace will be consumed by your current spellcast reducing it's cast time by 0.5 seconds."

A tbc moonkin video, to see this effect would be useful

**Comment by Isuel** [comment]
from what I know (there was a bug report on gamer-district about nature's grace with proof), nature's grace should give the buff on spell cast, not spell hit. idk if it has anything to do with this bug, since i haven't tested balance at all

**Comment by punker85** [comment]
Even if that should be the case, there still exists a problem.  The Nature's Grace buff is not reducing the cast time of my currently casted spell when it appears.  My Starfire spell has a 3 second default cast time with the Balance talents that I have picked.  I can chain-cast the spell and see all these Nature's Grace buffs and they will disappear at the end of the next spellcast without any benefit to my current spell cast.

**Comment by ccshiro** [comment]
Need some video or something to see how it works.

**Comment by matalm** [comment]
Here's a video from retail showing how Nature's Grace should work.
This example is for the Wrath spell, not Starfire.

The moonkin gains the Nature's Grace effect as soon as the Wrath spell is done casting, not when it lands. The cast time of the next Wrath spell is indeed reduced, even if it was cast before the crit lands.

Premonition Downing Curator
https://www.youtube.com/watch?v=Dq9cTNsfCMQ
At 4:17 is a good example.

**Comment by ccshiro** [comment]
@matalm cheers.

**Comment by ccshiro** [comment]
I've compiled a list of on critical spells that buff you (that I can think of) that should probably work as @matalm showed nature's grace working:
Nature's Grace (Druid)
Elemental Focus (Shaman)
Elemental Devastation (Shaman)
Doing this change to all of them.

**Comment by petaal** [comment]
I'm still having this problem. When I'm constantly spamming starfire, for example, the buff appears after the next cast has started, casting takes 3 seconds and after the cast is finished the buff disappears. This is very easy to produce with 50-60 ms ping. This also happens if I click the spell one time when the cast is almost finished (like 0.2 secs left) and the next spell goes to spell buffer and starts casting after the current cast is finished. I recorded a video and analyzed it frame by frame and it seems that Nature's Grace buff sometimes appears 10-19 frames (60 fps) after I see the first visual effect of Starfire, and sometimes it appears the next frame (in which case it will work fine). The next cast usually starts after like 3-8 frames of first visual effect.
![wowscrnshot_081215_165354](https://cloud.githubusercontent.com/assets/11743711/9556277/452f6e3e-4ddc-11e5-8845-475e51ac9d6d.jpg)

I also noticed the same kind of behavior with the mage spell Arcane Blast (should I make a new report?). The buff sometimes appears late and won't affect the cast already in progress.
![wowscrnshot_081215_163508](https://cloud.githubusercontent.com/assets/11743711/9557111/faecd770-4de1-11e5-9a2f-430baa55646a.jpg)

Here's the vids if you're interested: https://www.dropbox.com/s/hqknkhj67yr3k4d/wow_starfire.mp4?dl=1 https://www.dropbox.com/s/wrrez5i8ztxte4p/wow_arcane.mp4?dl=1

**Comment by Duums** [comment]
Nature's Grace - how it should work - Nature's Grace procs after landed critical wrath
https://youtu.be/onimVSWwZLg?t=131
Retail signs: publicity year, few seconds later at scoreboard shows Kor'Gall realm by rogues nickname.

**Comment by Peter1337** [comment]
http://wowwiki.wikia.com/wiki/Nature's_Grace 
"The Nature's Grace effect occurs when a spell that will crit has finished being cast, meaning that wraths that are still travelling to the target, but are predetermined critical strikes, will proc Nature's Grace before the damage is dealt to the target." 
this is how it works right now on retail and this is how it is shown in many different tbc retail videos - except the only one Duums posted.

examples:
~0:38, ~0:46, ~3:45 https://www.youtube.com/watch?v=d1XzHH4yORw (TBC beta)
~1:03, ~3:29 https://www.youtube.com/watch?v=WaDEK5Oqn_E
~0:58, ... https://www.youtube.com/watch?v=WB4sL6tfBWA (1 month after TBC release)
~1:00, ... https://www.youtube.com/watch?v=I3345gBs1WA (uploaded 21.7.08; patch 2.4.3 released 15.7.08 source: http://wowwiki.wikia.com/wiki/Patches/2.x )
Retail signs: publicity year, " (*) " after names of group members from other realms, added realm name after the name of enemies in battlegrounds

**Comment by joovah** [comment]
I wouldnt count the video Duums brought up as a valid proof cause the player is using some sort of addon to track his buffs and you can see that from 2 main things:
- it tracks 1 stack for the Nature's Grace buff
- moonkin form and moonkin aura buffs are switched if you compare to the other videos where people dont use buff tracking addons

i'm not an expert in those things but I bet the way the addon he uses sorts buffs make it so there is a small delay in showing "buff procs"

also in that clip the druid doesn't cast an immidiate wrath following the crit so we can't prove that an immidiate spellcast after a spellcrit (still traveling) was not reduced by 0.5s (which is the only way you can prove Duums point given buff tracking is not reliable because of the addon involved)

another link that proves nature's grace should proc on spellcast and not spellhit:
"the reason you get the buff as soon as it leaves your hands it becuase teh server has already determined that wrath will crit,"
source: http://www.gamefaqs.com/boards/534914-world-of-warcraft/41508706
might be not as official as other websites but still is 8 years old

sorry for my english, hope the post is understandable
