### ISSUE TITLE
Prayer of mending reapplication

### ISSUE THREAD

**Issue by Philosophers** [ccshiro/cc-buglist#501]
From patch 2.3.0 prayer of mending CAN NOT be reapplied to target that already has it. It means that priest cannot refresh buff until it ends or is dispelled. On Corecraft you can do it. This seems like minor issue, but can have impact on arenas.

Link to proof.
http://www.wowwiki.com/Patch_2.3.0_(undocumented_changes)

**Comment by Iliana-sc** [comment]
Are you sure this is the correct interpretation of what is supposed to happen? The priest can click the buff away so it would not make sense in the self cast scenario, though it would make some sense when casting on other players.

The page does not link to any source and does not provide any proof, it's just a list on wowwiki, which is known to contain mistakes and only has very loose review.

**Comment by Philosophers** [comment]
It is about other players.

I remembered fact, when I was healer on raids and I've put mending on tank and he did go into trash group / boss alone buff was consumed. Moreover second cannot be applied until it ended or was dispelled. I tested it on Corecraft and after I looked for a proof. That is the best I could find (in a reasonable time). Occured in late TBC and early wotlk, don't know how it works in later patches.

What I try to say is that I was convinced that behavior of mending on server is incorrect, then I found that note on wowwiki. Not in reverse order.

**Comment by maxmore031** [comment]
2.3.0 made it so the 5 charges of prayer of mending would only bounce from one target to another. Prior to 2.3.0, prayer of mending didnt require a second target in range and the 5 charges were healing the same person on the next 5 hits they would suffer instead of disapearing after 1 charge if there was no other target in range.

This bug report is only due to a missinterpretation of the patch note and should be removed from the list.

**Comment by maxmore031** [comment]
The one thing that is sad is that if you make it so it doesnt bounce on single target anymore, you would nerf priest in pvp for the first 2 arena season. Before priest had access to higher item level pvp gear, they were more skwishy just like any other cloth wearer but by the time they nerfed the prayer of mending bouncing on self, then I was full mercyless with vengeful off pieces so I was still somewhat tanky and the nerf was welcome.

I would love prayer of mending to be like it was during the first 2 arena seasons then fixed in time for  the 2.3.0 season which I think is the third season ( vengeful )

**Comment by ccshiro** [comment]
I'm fairly sure what @maxmore031 is saying is correct. I will close this issue as invalid, if you think I'm wrong it's still possible to respond and reopen it with further evidence.
