### ISSUE TITLE
Blinking through enemy NPC's results in damage

### ISSUE THREAD

**Issue by BeerfishWoW** [ccshiro/cc-buglist#53]
As a mage, blinking through a group of enemies, results in damage. Blinking through enemies should allow a mage to teleport through an enemy without getting hurt.

**Comment by ccshiro** [comment]
You never blink "through" anything. When you use blink you're instantly moved, there's no in-between states. The only way this could happen is if the mob got close enough before the blink or after it. Unless I'm misunderstanding the report, this bug is not possible to trigger. Most likely this was just a bi-effect of the server-lag we had last test.
