### ISSUE TITLE
pathing issues

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#537]
http://webmup.com/f5809/
http://webmup.com/49768/

watch the pet

**Comment by ccshiro** [comment]
We generate our pathing data for WMOs (like the arenas) using recast. We currently don't have a way to tweak it manually when the recast method fails (except changing the generation parameters and passes). In order to allow pathing over ropes we have to remain in this state of pathing in Blade's Edge Arena.

In other words, I can't fix the underlying pathing issue at the moment (without breaking the rope pathing), but I will disable pets being able to cheat their path in arenas. So instead of soaring through the sky it'd just stand still at its position, forcing the warlock to reposition to make it come back to its owner.

That's not an ideal solution, but it's the best we can do without spending significant time on it. Hopefully I can get it fixed better at a later time.
