### ISSUE TITLE
Legion Fel Cannon MKII

### ISSUE THREAD

**Issue by jlavier9359** [ccshiro/cc-buglist#58]
Description: One of the many fel cannons around Outlands that the Burning Legion use to shoot down players while riding their flying mount.

If I'm not mistaken they should have a larger aggro radius in order to sense nearby players in the sky and start attacking. I'm currently at both Forge Camp: Terror & Forge Camp: Wrath and neither seem to respond to me unless I deliberately get in front of them.

**Comment by ghost** [comment]
Clarification.
http://www.wowwiki.com/Fel_cannon?oldid=1438576
"There are two types of fel cannons, one that only fires are ground units, and one that only fires at aerial units (see Combat 15 Legion Flak Cannon)."

So Fel should target ground.
http://www.wowwiki.com/Fel_Cannon?oldid=1476847
http://www.wowhead.com/npc=22461/fel-cannon-mki#comments

 And Flak target air. 
http://www.wowwiki.com/Legion_Flak_Cannon?oldid=1474383
"Stationed around Forge Camp: Terror south and Forge Camp: Wrath north of Ogri'la in the western Blade's Edge Mountains plateau, Legion Flak Cannons only fire their fiery Fel Flak Fire at flying targets."
http://www.wowhead.com/npc=23076/legion-flak-cannon
"They will shoot you down from your flying mount if you fly too close, or if you fly inside the flak fire in the air on purpose. Watch out since you can die from the fall."

_
So working as intended?

**Comment by ccnim** [comment]
Reading Subzero's comment made me realize that this is indeed not a bug and once ogri'la is up I will remake them to the aerial assualt ones.
