### ISSUE TITLE
Crowd Control Issue

### ISSUE THREAD

**Issue by Stoney21** [ccshiro/cc-buglist#584]
You can't trinket CC like Polymorph or Blind and after it passes you can't move at all until relog.

**Comment by ceyscro** [comment]
For what I've seen, you can move after these cc. The bug is on sap https://github.com/ccshiro/cc-buglist/issues/592

Then about trinket, I did not test every stuns but there are some you can trinket and others you can't.
You can't trinket sap,cheapshot,kidney shot, gouge

What I could trinket : fear, mind control, deathcoil, blind.

**Comment by ccshiro** [comment]
Here's some debug linked to me: http://imgur.com/4x6vARK,XLqiX6u#0
