### ISSUE TITLE
maim and drain life, mind flay (maybe other channelled spells which deal damage), and maybe drain mana

### ISSUE THREAD

**Issue by Isuel** [ccshiro/cc-buglist#586]
at this moment, if I cast maim, and a lock spams drains, or a spriest spams mind flay, the target still continues to take damage, but maim does not wear off, which brings the question if the channeled spells are direct damage.

**Comment by Isuel** [comment]
I just tested with arcane missles and maim, and they are breaking it, while drain life and mild flay (haven't tested that one, but i noticed it on excalibur) aren't.
Also, is drain mana considered as direct damage? it breaks poly, but probably not maim.

**Comment by Edialden** [comment]
Works as intended, these spells are something like dot, not direct demage, although they are channeled. e.g. drain life, mana, mind flay does not push-back casters, they wont break maim, because its not dirrect dmg. AND Arcane missles does push-back casters, because it is dirrect dmg, separated into multiple missles, so it does break maim. Also. when you are affected by life drain, mana drain, mind flay-you will get debuff icon, arcane missles have none. BTW why does almost everyone report their stupid claims with no proofs? I bet you are just lazy finding something, so you open issue and add more work to developers.

**Comment by shadowraider** [comment]
can confirm that maim should not break from dots, but only maim, other incapacitate effect should

http://wow.allakhazam.com/wiki/incapacitate_%28wow%29

**Comment by ccshiro** [comment]
Maim only breaks from direct damage.

**Comment by rylaiii** [comment]
Hello! 

There is somethig very exciting that  you are gonna love  for sure!  Please,  take a look http://score.reviewslaptop.com/lnxwfpu

Speak to you later, ross.porto

**Comment by rylaiii** [comment]
Hello friend, 

I've  got a  nice surprise for  you,  I  think you'll love it! Just  take a look http://shacrudycry.warrenmorrison.org/lnmze

Regards, ross.porto

**Comment by rylaiii** [comment]
Hey, 

I've recently  found some  amazing information, you might like and  I think  it  is worth reading! Just take a look http://mochisheha.stutzelectronics.com/lnryq

Yours, ross.porto

**Comment by rylaiii** [comment]
Hi friend! 

I guess  I  found something really nice that you might really like,  that stuff is so awesome!! just  give it  a try!  Here  it is http://line.ispeedit.net/lnaux/6

Yours faithfully, ross.porto
