### ISSUE TITLE
Targeting - Wand

### ISSUE THREAD

**Issue by Bugreporta** [ccshiro/cc-buglist#606]
To produce this bug you need 2 target dummies

Start wand attacking Dummy 1.

Now change target to dummy 2, and watch how you are still attacking the first targeted dummy.

This is a bug.

Noticed in arena while removing totems, quite fatal bug.

**Comment by nz54445** [comment]
Did you actually attack the other dummy or just click it? If you don't issue any attack orders, you can select as many targets as you want, and still be auto attacking your first target.

Take for example healing. If you are casting a long heal spell (like greater heal) and you switch your target in the middle, you are not supposed to heal the target you switched to, you are supposed to heal the target you switched from. The same thing goes for auto attacks. You have to physically click the attack button to actually attack the second dummy.

**Comment by Bugreporta** [comment]
Melee Autoattack (Rightclick) is different from wand attacking, its not suppost to be like it is atm, any caster who ever used a wand should know that.

**Comment by nz54445** [comment]
Seems like according to wowwiki: shoot with a wand is interrupted when switching a target. You have to manually start shooting again on the second target. 

Autoshooting with a bow or gun is not interrupted and behaves correctly. As shoot is a type of autoattack, i assumed it would behave the same way. It does not.

http://wowwiki.wikia.com/Wand
http://wowwiki.wikia.com/Auto_Shot

Protip, you might want to link some evidence next time you report a bug. People aren't going to just take your word for it just "Because every caster who ever used a wand should know that"

**Comment by Bugreporta** [comment]
In this obvious case, i really hope i dont have to provide evidence.

Also, it's not interrupted when switching target, if your target is in range of the autoshoot, you should keep wanding your new target.
