### ISSUE TITLE
(Warlock) Pet behavior

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#618]
Pet attacks the new target even when not commanded to when you use a ranged spell such as spell lock on the felhunter it should counterspell the target but continue to attack the target it was told to attack.

**Comment by teddys** [comment]
So when you focus spell lock someone, the felhunter should keep attacking its current target instead of switching to the one he was commanded to spell lock?
Do u have any evidence for this?

**Comment by tedrasiel** [comment]
i guess it just works that way if u use a macro... but it shouldnt be so hard to find a video about that for proof at all.

**Comment by shadowraider** [comment]
played few years warlock myself, never studied this behaviour but I think there are 2 options.... 

1st: warlock's pet is in idle state out of combat with no target, when master commands to cast a spell, the pet will cast a spell and starts to attack the same target

2nd: warlock's pet is in combat and already melee attacking target, when master commands to cast a spell on another target than the pet is currently attacking, the pet should cast the spell once, and then switch back to previous target, until the master gives him command to attack another target by attack move

**Comment by Klimpb** [comment]
Got some stuff:
http://webm.host/3f096/vid.webm
http://webm.host/7a5da/vid.webm
http://webm.host/91619/vid.webm (he ordered the pet to attack on the second spell lock)
http://webm.host/5583f/vid.webm
http://webm.host/7f5e1/vid.webm (he ordered the pet to "stay" at the start of the webm, then casts devour magic after some time)

I suspect that the pet's stance could have some impact on this.. Would be nice with a video of someone with their pet on defensive or aggressive.

I'm also interested in how the pet would act if it's out of range when ordered to spell lock etc. Will it move towards the target then use spell lock when in range and then attack the target or will it just move towards the target and use spell lock when in range then go back to the warlock, or will it just say out of range and do nothing?

Could also be good with some source from another video, because you never know if my source used some obnoxious spell lock/follow macro, which I doubt though since you can see the clicking frames on the spell lock bar.

**Comment by shadowraider** [comment]
IMO this is not a big bug (if it is) since in TBC u can manage your pet behaviour exactly how you want to through macros

**Comment by lawzftw** [comment]
I can't find proof atm, maybe tomorrow if no one found some before, but here is how pet should behave.
First, there are 2 kinds of pet spells. The one that damage the enemy, and the others (which only apply a debuff, dispel, etc).
- For spells that damage enemies, whether your pet is in stay, already attacks someone, it's always the same : if you order it to use this spell on an enemy, it will keep attacking it.
- For other spells, pet will do what you asked it to do, even if it's not in LoS, and then come back to what it was doing, if it's in passive (I don't know the exact behavior in defensive and offensive, anyway it should always be in passive, I prefer not talking about what I don't know for sure).

Some examples :
- If pet was attacking target 1, and you ask it to spell lock target 2, let's say target 2 isn't in los, pet will go in target 2's LoS, spell lock it, and come back attacking target 1
- If pet was in stay, and you ask it to dispel your mate who isn't in los of pet, pet will move to dispel him, and after that come back to its initial position, not moving. If it was in follow, after the dispel it will come back to the master

I think those 2 examples sum up pretty much everything. I hope it was clear.

**Comment by ccshiro** [comment]
@lawzftw I think this sounds very plausible. Looking at @SuddenDeath's videos I think it proves half of your claim. We just need to find a video of a damaging ability working the way you describe. Maybe something like felguard's intercept used on an off-target?

**Comment by missmore** [comment]
ccshiro commented 2 days ago:  
`We just need to find a video of a damaging ability working the way you describe. Maybe something like felguard's intercept used on an off-target?`

I remember like if it was yesterday. If your Felguard is already attacking one target and you ask him to do an intercept on another creature, it will intercept and run right back at the primary target. 
The second target has to be in intercept range otherwise you will get the error message (target out of range) same thing applies if the target is out of sigh... pet just keep attacking primary target and you get the error message.

**Comment by boroppi** [comment]
missmore is right.

**Comment by Klimpb** [comment]
@missmore I think your memory has been corrupted :-)

Here's some Felguard videos:
1. http://webm.host/a8d00/vid.webm (short)
2. http://webm.host/39e7c/vid.webm (most clear, happened twice)
3. http://webm.host/f5927/vid.webm (short)
4. https://www.youtube.com/watch?v=7L99OdQ0Wns&hd=1  (other mechanics involving death/vanish etc)(file too large for webm.host)
5. http://webm.host/8a2ea/vid.webm (not much info here, except for the last bit with the death of the rogue, interesting)

I'm still not sure what should happen when out of range or line of sight when using pet abilties, damaging or non-damaging. If someone kind find proof of that, it would be nice. I almost got proof of it in the second video, but shaman moves from pillar and is no longer LoS too quickly, not reliable source.

**Comment by Chulain** [comment]
@SuddenDeath why are these uploads so slow? took me almost a minute to load that 4sec video

**Comment by ivanprgin** [comment]
fix it alrdy i can't look at that 1 bug left anymore xD

**Comment by Klimpb** [comment]
@Chulain They load instantly for me, maybe strange routing.

**Comment by ivanprgin** [comment]
@Chulain can be firewall issue

**Comment by Aasamath** [comment]
https://www.youtube.com/watch?v=kzmPNTDcfnQ
at 2:14
because of a zoom at the start of the clip you can't see the lock ordering the succbus to seduce, but  after the zoom, no pet button is activated, meaning he ordered the pet to seduce and the pet moved on his own to go cast ( what i mean is the player didn't send the pet to attack and then seduce when in range)

**Comment by YourNewfriend** [comment]
Yo, just contributing.  I searched a bit for definitive proof on the topic of "if pets should move towards a target for the sole purpose of using an ability", but couldn't find any.  I'll be back tomorrow, and I should find something if somebody else doesn't beat me to it.

The little I collected:
**_Felhound doesn't attack after CSing with Tainted Blood set to auto-cast on passive**_ https://youtu.be/vxjC-pnlkYU?t=40s

**_The succubus definitely wasn't in range when it was commanded to use Seduction.  I'm not sure if it ran up to him to cast it, or if it stood by its master and queued it, or my eyes just missed something.**_  https://youtu.be/zh7K7SxcCIk?t=1m45s

**_Succubus is ordered to use Seduction (no auto-cast), and returns to its master Seduce ends even.  It's in defensive mode.**_  https://youtu.be/qAbH3_FXhKQ?t=30s

**_Seduction breaks, and the Succubus attacks without being commanded in Defensive Stance with Soothing Kiss on auto-cast?**_  https://youtu.be/qAbH3_FXhKQ?t=2m14s

**_Seduction breaks, and the Succubus doesn't attack without being commanded even though Soothing Kiss is on auto-cast.  Passive stance.  Uncertain if the above video's quality was just too poor**_  https://youtu.be/KnXN_KuJWcE?t=25s

**Comment by missmore** [comment]
SuddenDeath commented 16 hours ago:

@missmore I think your memory has been corrupted :-)

Here's some Felguard videos:

http://webm.host/a8d00/vid.webm (short)
http://webm.host/39e7c/vid.webm (most clear, happened twice)
http://webm.host/f5927/vid.webm (short)
https://www.youtube.com/watch?v=7L99OdQ0Wns&hd=1 (other mechanics involving death/vanish etc)(file too large for webm.host)

## http://webm.host/8a2ea/vid.webm 

While I appreciate the effort, I have serious doubts that these footage are from the release servers because there is a ( Nelithar orc Warlock ) posting videos of private TBC server on dailymotion and youtube. 

Here is an exemple of Nelithar who posted a video of the same looking / geared orc warlock about 9 months ago https://www.youtube.com/watch?v=czV-xTY6NV0

Or if you are on a PC you can also go watch the dozen of videos of TBC posted over the past recent years from Nelithar. http://www.warcraftmovies.com/movieview.php?id=122339

by reading the comments below the videos we clearly see that those are not Re-uploaded old videos from the release servers but actual new videos being uploaded.

So I am sorry but I still think I am right with my own claims.

**Comment by ceyscro** [comment]
In thoses footage you can see in the combat chat the name of the opponent followed by a server name, you can also see it when arena ends and the window with teams appears.

If you see In a video a "name - server" that's could only be a video from retail.

**Comment by missmore** [comment]
@Ceyscro servers were not linked back in the TBC days. Your comment doesnt make sense ceyscro because the ( name in the chat box  before the nicknames) isnt the actual server name but the channel name or the guild name.

So much disinformation going on here.

**Comment by missmore** [comment]
@YourNewfriend Tks for the videos, your videos are legit

**Comment by ceyscro** [comment]
@missmore Lol, it seems you never played retail and your memories are completely false. In TBC days you could meet any team from the same Battlegroup as your, so you could see the opponents server by his name.

In footages linked by @SuddenDeath you can see : Koshan - Dunemaul, guild : So What
and Riggs - Daggerspine Cryptikz - Daggerspine

I just don't know where you saw a guild name or a channel name appearing just after a name with a hyphen, even currently it's impossible.

@missmore http://wowwiki.wikia.com/Patch_1.12.0

"Cross-Realm Battlegrounds
For the first time in the history of World of Warcraft, you will be able to face off against players from other realms in the Battlegrounds. PvP Battlegrounds link Alterac Valley, Warsong Gulch, and Arathi Basin so that players from several realms will be combined into one huge matchmaking pool."

**Comment by ivanprgin** [comment]
@missmore Ceys is right it is retail like. Only bgs and arenas were linked in tbc, but only few server 3-4

**Comment by ccshiro** [comment]
@SuddenDeath Nice, that seems to prove @lawzftw claim of how it works to be the most accurate interpretation we have at the moment. I will implement it as described.

Everyone, thanks for the input.

**Comment by ivanprgin** [comment]
Last bug has fallen

**Comment by Jigodian** [comment]
ACE!
