### ISSUE TITLE
[Hunter] Winderpent's Lighting Breath ability scales with RAP

### ISSUE THREAD

**Issue by TheVcelar** [ccshiro/cc-buglist#655]
bug: Lighting Breath scales now with RAP. It should NOT.

LB dmg should scale only with %-dmg modifiers like orc racial, pet species, ferocious inspiration, pet mood, etc.

proof here: https://www.youtube.com/watch?v=1foguXp-xts 
retail Brutallus kill - SV hunter POV with wind serpent:
     - +7% pet species (wind serpent)
     - +25% pet mood
     - +3% and +3% Ferocious inspiration (not 100% uptime)
     - +10% Curse of elements
     - +5% Misery
     + maybe sometimes +20% dmg Stormstrike debuff (not sure if it happen on this video)
- equation for this example for most of the time is: (101~116)(1.07)(1.25)(1.03)(1.03)(1.1)(1.05)=165~190

**Comment by meowmewo** [comment]
LB scales with 1,25% of RAP as of 2.4.3 after a nerf that happened. Previously earlier in BC it was 12.5%.
LB will get affected by totem of wrath, totem of air and stormstrike +the things u mentioned above. So LB gets 101dmg more, 3% hit & crit & 20% more dmg. I remeber some formulas somewhere. Il try to find them and post them here.

**Comment by meowmewo** [comment]
Here:

Lightning Breath is an instant cast spell. instant casts do not get the full benefit of +Spell Damage bonuses, they are only supposed to get a percentage. Specifically they are supposed to get 42.86% of the bonus +Spell Damage( thats the pet's spell damage)  provides.

LB_Base_Damage = ( LB_Low + LB_High ) / 2
LB_Base_Damage = ( 99 + 113 ) / 2 = 106

LB_Damage = 106 + ( RAP \* 0.125 ) this .125 coefficient was calculated without the 42.86% in mind.

then it went to
LB_Damage = LB_Base_Damage + ( Spell_Power_Damage \* 42.86% )
LB_Damage = LB_Base_Damage + ( RAP \* 0.125 \* 42.86% )
LB_Damage = 106 + ( RAP \* 0.125 \* 0.4286 )
LB_Damage = 106 + ( RAP \* 0.053575 )

Howerver this is with 12.5% of RAP and since when Corecraft releases in 30 years, it will be 2.4.3 patch notes, that means we have to use 1.25% of RAP, so for 1.25% we are changing the number 0.125 to 0.0125 in every place in the formulas, then it should result in the right numbers. Then LB dmg should be: ((99~114)+RAP \* 0,0125 \* 0,4286)*modifiers

**Comment by meowmewo** [comment]
So...
A average hit of LB - 106`~
If we have a hunter with 2500 AP = 106 + ( 2500 \* 0.0125 \* 0.4286) = 106+ (2500 \* 0.0053575) = 106 + 13,39 = 120~ + whatever extra buffs pet has (mood 25%,totems,species etc.)

In conculusion. The post is wrong.  However. It needs to be tested, i gave up on Corecraft so i havent actually tested it but to the guy who made the post -> Try to test it next time knowing all these stuff now and see if its actually scaling right or not.

**Comment by TheVcelar** [comment]
ok, now i know, where i made mistake
CoE does not increase nature dmg, so LB should scale with RAP as you said and as it is described in cheeky's

i would like to test LB again, but i lost my password

**Comment by Barroth** [comment]
Went through a few Hunter tbc videos and can confirm that Lightning Breath and Scorpid Poison have a 10% scaling.

**Comment by ccshiro** [comment]
Think this should be working as intended, I will move it to needs testing anyway in case someone wants to confirm.

**Comment by TheVcelar** [comment]
i did some testing with these new information i gained and scaling still seems too high ... i was testing with orc BM hunter with ~1900 RAP and LB was hitting for 300 noncrit dmg in average into target dummy.... that is more than for example this wind serpent does: https://www.youtube.com/watch?v=KJGmWbrGuOo  (usualy hitting for 210-230 noncrit)

**Comment by meowmewo** [comment]
Yep 300 is too much in any case.

**Comment by meowmewo** [comment]
Wich means CC is probebly using the old formula wich uses 12.5% from rap, rather then 1.25%.
