### ISSUE TITLE
Health/Manabar display at % or numeric?

### ISSUE THREAD

**Issue by KuroiKensai** [ccshiro/cc-buglist#668]
Was wondering about it, but found old theme at forum. It proofs that since 2.3.0 u can use numberic values for any target in game. Will stick it here, cos I personally think than numbers are just more comfortable/accurate and has nothing do with "hardcore":

So Corecraft is gonna be 2.4.3 talents etc, But with all the unnerfed content, (as it was before the big nerf patch/es).

Are the target's health or mana etc, only gonna be displayed in Percentages here on CC as it was pre-2.3.0 where you only had the choice to be able to see your own and your party's Health/mana in numeric text? Or is it gonna be like after patch 2.3 where you can choose in the UI-Meny between, A.-Percentages or B.-Numeric text for Everything Enemytarget,friendlytarget,Raid,Party etc.

(PROOF). From patchnotes 2.3.0 Under the (User Interface) Category.

There are now options for displaying health and mana values on your health/mana bars for you/your party/your target and to display that information either as percentages or as numbers.

Source - http://us.battle.net/wow/en/game/patch-notes/2-3-0

(PROOF). From patchnotes 2.1.0 Under the (User Interface) Category.

The 'Status Bar Text' option in the interface options UI will now display numeric values for all party members health/mana bars in addition to your own.

Source - http://us.battle.net/wow/en/game/patch-notes/2-1-0

**Comment by darkcranio** [comment]
Also we should see the friendly NPC's numbers all the time.

**Comment by Klimpb** [comment]
This is how it worked in TBC.

Like you said, in patch 2.1.0 they implemented the option to display numeric values for all party members health/mana.

and in patch 2.3.0 they implemented the option to display it in percentages. They probably just worded it a little bit different and forgot to include that it still only applies for your party members and yourself.

This is just a guess though but regardless, there has been no proof what so ever of it being possible to display enemy health in numeric values in any patch of TBC. As far as I know, it was implemented as an undocumented change in patch 3.0.2.

Just take a look at some retail videos yourself of patch 2.4.X
https://www.youtube.com/watch?v=QyTyNaiEJKs - Hydra 6
https://www.youtube.com/watch?v=5HnthGAKrn8 - Tuska 4 ft. Boozt - World #1 Spriest/Rogue

They have health in percentage and mana in numeric values.

**Comment by KuroiKensai** [comment]
Dont you think they have it this way cos they USED TO such look and just DID NOT use new function at all, maybe cos they even DONT READ about it at patch notes?
I remember that I was able to toggle % or numbers in 2.4.3. And also 2.3.0 patch notes CLEARLY states:

There are now options for displaying health and mana values on your health/mana bars for you/your party/your target and to display that information either as percentages or as numbers.

No word about "Returning % back", only about NEW functions.

And tell me HOW Sk Gaming was able to see accurate boss hp at this video? MobHealth? Dont think so.
https://www.youtube.com/watch?v=Uf7j4IIIZrU

**Comment by Klimpb** [comment]
@KuroiKensai The player recording in that video is most likely using mobinfo2 to attempt to display the correct health of enemies. You can see this by looking at the mobs that he targets, as they lose health their maximum health changes slightly. This is because the addon is constantly estimating the health based on the combat log.

As far as I know, it is not possible in the interface options to set target health to percentage and leave mana as a numeric value. You either have to set both to percentage or both to a numeric value. That is of course without the help of addons. Which means that in those 2 videos they had it set to numeric value since you can clearly see their teammates health & mana in numeric values. There's also a part in the Hydra 6 video where he plays without any addons at all and it displays the same:

![](http://i.gyazo.com/0ce65de5f556d38a59b32dfb1c738713.png)

Also when he targets his teammate in the same match, numeric values are displayed for his health:

![](http://i.gyazo.com/d51606fdb77e9ca06b755614880552e5.png)

As for patch 2.3.0, essentially what it says is that you now have the option to display the values in percentage, before you couldn't. Sure it mentions your target but it doesn't specifically say hostile/enemy target. One would assume that all types of targets are implied in that statement but since it actually was not the case then we can only assume that it wasn't implied or that Blizzard left some information out either on purpose or by accident.

**Comment by Barroth** [comment]
Since the 2.4 version of Mobinfo2 still uses percentages to approximate the health values I think it's pretty safe to assume, that there was no option to see the actual value.Would be quite weird to still calculate it, if blizz had added the values to patch 2.3.

**Comment by KuroiKensai** [comment]
Okay, maybe I remember wrong. But still will be good to have numbers as an option, cos it dont affect gameplay that much, only make it more comfortable. Lets wait for Shiro's answer.

**Comment by ccshiro** [comment]
Please search the tracker before opening bugs, this one has been reported before, and invalidated.
