### ISSUE TITLE
[NPC] Silvermoon City Guardian

### ISSUE THREAD

**Issue by Adunai** [ccshiro/cc-buglist#682]
These NPCs respond to emotes done by any blood elf class. They are supposed only to respond to emotes made by blood elf Paladins.

They didn't respond to any emotes earlier, so I can admit that the work has been done to correct such a small issue.

Screenshot (as a Paladin): http://i.imgur.com/3bw7LOy.jpg
Screenshot (as a Warlock): http://i.imgur.com/XWuRcz0.jpg
Link: http://www.wowhead.com/npc=16222/silvermoon-city-guardian

**Comment by ccnim** [comment]
Seems like they should respond to all classes except for when /eye'd in which case you need to be a BF paladin to get a response and you might need to have done a paladin Q (which one I'm not sure).

**Comment by vove9000** [comment]
As ccnim says most of the guards respond to some emots made by any class/race from the same faction. In Silvermoon City when a Blood Elf paladin did /eye emote on any guard they would /kneel but afaik you didn't have to do any q in order to achieve that.

I am also reading now on wowwiki that not all guards respond to emots, I think this rather applies to Darnassus Sentinels or guards at the posts than guards in general, as every guard in Orgrimmar (and other capital cities) responded to the basic emots.

Also there was this thing as in Warcraft strategy game- when you right clicked many times at the same NPC they would get pissed off changing the standard greetings to more rude ones.

Guards of cities will respond to some emotes such as /wave, /rude, /kiss,/chicken,/shy, or /salute.
<a href="http://wowwiki.wikia.com/Easter_eggs#Guards">Guards<a/>

They seem to be politically under the sway of the Blood Knight order. When a blood elf paladin uses the emote "/eye" on a Guardian, he will kneel before the paladin.
<a href="http://wowwiki.wikia.com/Silvermoon_City_Guardian">Silvermoon City Guardian<a/>
