### ISSUE TITLE
Mounting on Zeppelin Towers and Zeppelins

### ISSUE THREAD

**Issue by Adunai** [ccshiro/cc-buglist#683]
Ground mounts are not allowed on top of the zeppelin towers and on zeppelins. Is that intended?
I'm not sure about the inside of the tower. It doesn't allow mounting either.

Screenshot (zeppelin tower): http://i.imgur.com/iEyMZCy.jpg
Screenshot (zeppelin): http://i.imgur.com/8EOzJ8p.jpg

**Comment by Ghhlox** [comment]
You weren't able to mount in a lot of places that people are able to today. The zeppelin and towers was one of them. The whole mounting thing became apparent after WOTLK was released because they cared less that it didn't make sense to have a kodo climbing on stairs and were more interested in creating functional game appeal.

**Comment by Klimpb** [comment]
Like Ghhlox said, you had to stand on the very edge of the zeppelin to be able to mount. I Remember people often did that at the very front.

**Comment by Ghhlox** [comment]
But be careful doing that -- if you're standing there when the loading zone hits you'll fall off the zeppelin when the screen reloads. I remember it being a long swim to Grom'gol :)

**Comment by netherspite** [comment]
At retail it was possible since vanilla to mount up when standing on the zep at some specific point close to the edge between the zeppelin border and its floor. I did it often to be ready to jump from the zeppelin and ride to the city when it'll arrive.
All other places of the zeppelin and the tower were not available for mounting.

**Comment by netherspite** [comment]
Found the proof: https://www.youtube.com/watch?v=U2Ms9zqxDeg
