### ISSUE TITLE
Faerie Fire (feral) multiple ranks in spellbook.

### ISSUE THREAD

**Issue by Yagrulol** [ccshiro/cc-buglist#720]
why does in my spellbook show faerie fire (feral) rank 1 till 6, even tho that skill costs no mana.
shouldn't it only show the highest rank like it does with other skills that have no additional cost to a higher rank? (like most rogue and warrior ability's)

to reproduce:
Make a druid, choose the faerie fire (feral) tallent and learn all ranks from the trainer.
Open spellbook and observe.

**Comment by ccshiro** [comment]
This was done intentionally. The commit when we changed this said according to sources that this should be the case, for some reason the commit didn't include the sources though :/. Anyway, since it's working as we intended it, this will need some proof for us to reconsider it.

If you do find sources, just reply with them and reopen the issue.
