### ISSUE TITLE
Vengeful Harbinger 

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#752]
Can't turn in the quest, you get stuck on continue.

**Comment by ccshiro** [comment]
This quest is actually completed when you get it, and you just need to be present when someone finishes the event to turn it in. I.e., there's no quest objective to track or no objective completed message when you do the event.

I'll post the proof for that since it looks very ugly and wrong to me before I researched it:
https://www.youtube.com/watch?v=AOKItoYC-u0
https://www.youtube.com/watch?v=J4OXliKrVco
http://www.wowhead.com/quest=10842/vengeful-souls#comments:id=31841:reply=292384
