### ISSUE TITLE
Combat duration too long

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#769]
Combat Timer should be 5-6seconds randomly(1sec batches) or set 5seconds, perhaps it was changed in some patch during TBC.

Woundman drops combat after 5seconds every time: https://www.youtube.com/watch?v=6cMJFN-eNRU 

Gouge into sap, notice how GCD of sap starts before gouge has finished: https://youtu.be/DGtsAvpn3xo?t=179

Wowwiki history says combat is 5seconds: http://wowwiki.wikia.com/Combat?oldid=1665778

The corecraft thread: https://www.worldofcorecraft.com/content/combat-time

AT TBC(only tbc) changes combat to 5sec: http://web.archive.org/web/20150617172247/http://temp.arena-tournament.com/forum/viewtopic.php?p=114029&sid=f181d2fe04630a390400739e8c3f281f

first AT thread discussing it: http://web.archive.org/web/20150617172037/http://temp.arena-tournament.com/forum/viewtopic.php?p=135409&sid=2d8e3552ed6a594e84da5525e05ef0dd

**Comment by Stoney21** [comment]
Noticed same thing on HG. Their developers weren't sure if it was latency or something else. It might be connected with latency.

**Comment by SuddenDeath** [comment]
He used vanish in the video though, I have yet to see a video where a rogue uses gauge then wait to leave to combat, then stealth and sap, all before the gauge ends.

**Comment by Peonstomperx** [comment]
Kind of related: https://youtu.be/fT_aZfg9AP0?t=153
He gets blinded, drops combat roughly 2sec after (because the other rogue vanishes?)

**Comment by Mephisto22** [comment]
In theory it should be 5 seconds, but in practice it is really variable. Probably due to latency, between 5 - 7 seconds depending on the server - client latency. If that is not possible to implement on CC then I don't think that 5 seconds would be blizzlike. We would have to remove vanish - blind things and such...

Arena junkies discussions:

http://www.arenajunkies.com/topic/23238-rogue-how-to-sap-in-combat/

http://www.arenajunkies.com/topic/56403-in-combat-timer/

http://www.arenajunkies.com/topic/5623-getting-out-of-combat-to-drink/

**Comment by ccshiro** [comment]
There's a misconception about the combat timer, and how it's actually supposed to be exact but that it used to vary depending on server lag. This is completely untrue. The combat timer being variable is not a result of latency, but rather a product of how it was implemented by Blizzard.

We have it implemented in a way that's quite similar (if not the same) to how it works on retail. This means the combat timer can get really low (less than 5 seconds in fact), or really high (upwards to almost 7 seconds) depending on what is essentially RNG. Note: I say essentially RNG, because it's not actually random (in fact it's completely deterministic), but will feel like it to players.

It's the same type of mechanic you have for Diminishing Return. DR's "official" timer is 15 seconds, however since it's checked in batches of 5 seconds interval a DR can last between 15 and 20 seconds. The same logic applies for the combat timer but with a different minimal timer and a different refresh interval.

**Comment by Peonstomperx** [comment]
@ccshiro is there an explanation to the 5sec addon then, or are you saying he's just lucky it's on time every time in the video?

Maybe I'll download some videos and count frames when I find the motivation or some fast way of doing it.

**Comment by Peonstomperx** [comment]
Well ok, so it does seem Woundman 1 was recorded on the official arena-tournament realm from blizzard, both ways are blizzlike. 
My guess is you will just stick to the "RNG"-way(average 5.5sec?) to nerf rogues however I noticed something important;
Combat batches seem to be perfectly synced with energy ticks (see energy addon):
https://youtu.be/eJWNMCD8SMU?t=76
https://youtu.be/eJWNMCD8SMU?t=87
https://youtu.be/eJWNMCD8SMU?t=175
https://youtu.be/fT_aZfg9AP0?t=61
https://youtu.be/fT_aZfg9AP0?t=74

I hope you realize this will be exploited and rogues will have 4.5second combat instead of 5, hooray for not even needing improved gouge.

**Comment by Ickler** [comment]
In all vids I've seen linked here, it does appear to be synced with Energy ticks as Peon says, but also 6 seconds on the button every time. Am I mistaken? This is pretty interesting. It always felt random to me, at least in vanilla when I started with rogue.
But never gave it any thought after TBC, and I didn't main rogue then only played as an alt. But I always still figured it was 6-6.5 seconds. Since from all the countless times you gouge someone, I don't think I ever managed to restealth unless I had imp gouge... I mean, there were times I specced imp gouge only to gain this ability (that was after all the main implication of having it). So if it can be down to less than 5 seconds.. That sounds really odd to me. 
That sounds like Cata and above to me. Where they messed around with that stuff.

**Comment by justinbeaver** [comment]
Pretty interesting find

<b>Arena_2v2_Rogue-Priest.avi</b>
It took 10 (!) seconds for rogue to get out of combat, after he gouged a druid and then just ran around
![1](https://cloud.githubusercontent.com/assets/13700367/9562719/18ed1fa0-4e7d-11e5-963d-fcec512b353d.png)
![2](https://cloud.githubusercontent.com/assets/13700367/9562720/1bab45fa-4e7d-11e5-9ef1-206086c93ed3.png)
___
7 seconds to get out of combat when cycloned
![1](https://cloud.githubusercontent.com/assets/13700367/9562775/ddb10ddc-4e7e-11e5-8017-91e151a8a2c1.png)
Left cyclone but still in combat
![2](https://cloud.githubusercontent.com/assets/13700367/9562776/dff11a2e-4e7e-11e5-8439-d6fc156bf0a0.png)
He need one full second to get out of combat
![3](https://cloud.githubusercontent.com/assets/13700367/9562777/e1a8e770-4e7e-11e5-8916-d81d7a86d392.png)
WCM link: <i>http://www.warcraftmovies.com/movieview.php?id=68683</i>
Game font download:<i>http://www.gamefront.com/files/Arena+2v2+Rogue+Priest/;9899698;/fileinfo.html</i>

**Comment by ccshiro** [comment]
Closing the issue, we have it synced up with the energy timer now btw. Thanks for pointing that out.
