### ISSUE TITLE
Player movement 

### ISSUE THREAD

**Issue by balsh** [ccshiro/cc-buglist#771]
Like every single pre WOTLK (only the wotlk private servers with the new trinity core got it right) the displayed movement of other players is a bit off sometimes. It's better than most servers, but there are still bugs where players seem to teleport/glitch their orientation in random directions (especialy on mounts).

**Comment by Klimpb** [comment]
Even blizzard's servers still have these issues, and it's actually a lot worse on the retail servers than on pretty much any private server.

source: https://youtu.be/Z_rs4YVbZag?t=19m46s

**Comment by balsh** [comment]
Yeah sprinting was rly bad on retail.
But not normal running.
Here it's a mess in pvp sometimes like every crappy private server

**Comment by darkcranio** [comment]
Was good some tests ago, wasn't it?

**Comment by ccshiro** [comment]
I don't see anything that's changed since we looked at this last time. Will move to high priority and take a better look at it at a later time.

**Comment by CarboCorecraft** [comment]
From my observations during August 6, 2015 test, it's the most common "movement" bug i've seen so far. This bug is also the most annoying from melee class pov, you can't take any melee action against a target if the "teleportation" range is more then melee range.

The most common are "few yards teleports" such as these: https://youtu.be/4PtKqHTe4Ek (the final episode of this vid shows also teleportation while being mind controlled). However i also noticed 10-15 yards distant teleports few times.

Moreover i noticed that this issue may be associated not only with target being stunned. Please look at the final shadowstep teleportation spot in this vid: https://youtu.be/KSjZYORAGHg (it may seem that "the target we can see on the vid" and "the target of shadowstep" are in different places). I couldn't cheap shot that priest (pressed cs keybind immediately after shadowstep).

I agree with OP that the trinity core got it right (i remember that also TBC trinity used on AT server had great coding regarding movement).

At the end i also want to add, that i noticed this bug in a clip from TBC period on retail :) https://www.youtube.com/watch?v=kKaBbrqfXTY&t=0m58s

**Comment by Klimpb** [comment]
@CarboCorecraft You noticed that in a video on retail since it literally was like that on retail. You could not shadowstep a mounted target and expect to get a cheap shot on him. There are tons of videos of this on retail, mostly rogue arena videos etc.

Movement delay on players were higher than it ever was on private servers.. and it still is more delay on retail when it comes to movement.

**Comment by ccshiro** [comment]
I spoke to namreeb, who's reversed the movement procedures in the client. With his help I've made some changes that should make it more blizzlike now.

**Comment by inreverseess** [comment]
@ccshiro Player movement is fucked up now. This is not blizzlike

Why spend time on unnecessary stuff, movement was good before.
