### ISSUE TITLE
(Crowd Control) Fear+Nova

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#812]
If a mob is feared then has a frost nova applied it will start attacking near by targets even if it still is feared

http://www.twitch.tv/nanettie/v/6936131

**Comment by JayDee81** [comment]
works the same if a player is feared. got feared and frost nova'd and was still attacking my target.

**Comment by Peonstomperx** [comment]
I think the same happened to me, blinded while in nova, when I got out of nova and started moving I could auto attack my target.

**Comment by Ensipid** [comment]
Same problem exists with:
Gouge into Kidneyshot, target can attack/move after gouge ends.
Kidneyshot into Gouge, target can attack/move after kidneyshot ends.
Sap into Cheapshot, taget can attack/move after cheapshot ends.

The problem doesn't seem to exist with Blind, possibly because it has a movement component with it?

EDIT
The problem doesn't seem to happen with other movement base CC, scatter into freezing trap still leaves you unable to attack/move/etc.

I don't know anything about WoW's code base but it seems to me that when two 'same' CCs are applied on top of each other, they both activate the same 'can't play your character' flag, then when one of them expires, it takes both flags with them.

e.g.
Player is sapped, given a 'can't do stuff' flag.
Player is cheap shotted on top of sap, applying the same 'can't do stuff' flag.
Cheap shot fades from Player, clearing the 'can't do stuff flag', taking Sap's flag with it.
Player is still afflicted with Sap, but can move/attack/do stuff.

This would also explain blind as it would apply a different 'can't do stuff' flag as it has to give the player random movements, so even when another cc's 'can't do stuff' flag is cleared, player still has a 'randomly moving without control' flag.

EDIT 2:
CS/Gouge/Sap/KS all inflict stun(140) in .movegen, while blind inflicts confused(130).
