### ISSUE TITLE
Master Spellstone is removed upon entering arena(not sure/research needed)

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#862]
I'm not sure if this is a bug or not, only way to find a source of this would be to find some high level arena warlock from TBC that recorded the entire preparation phase in arena.

**Comment by Doppelmoral** [comment]
I'm positive it should be removed. The spellstone's tooltip clearly states "Conjured item", thus it suffers the same fate as Mana Biscuits, Healthstones etc. when entering an arena match.

Invalid report, please do the research before submitting an issue !

**Comment by Doppelmoral** [comment]
How does this require more evidence than what I wrote though ? Okey, since logic ain't enough:

http://wow.gamepedia.com/Arena

<i>Pre-match
Inside the arena.

<b>Upon zoning into the arena</b>, players start in a staging area. Health, mana, and energy are all restored, all buffs and <b>conjured items are removed</b> and pets are dismissed (debuffs will remain, and pets can be re-summoned once you zone in). Players are also given the Arena Preparation buff, which removes the resource cost of all abilities.</i>

Before any genius questions my previous statement and is too lazy to check ingame: 
![spellstone](https://cloud.githubusercontent.com/assets/2018747/8531460/d4d0bab8-2427-11e5-8551-d6d2c2098342.png)

I can provide plenty more proof. Videos, various sources - you name it.

**Comment by Klimpb** [comment]
@Doppelmoral Videos would be nice, if you can find any.

I just think that this item could have been an exception simply because conjured equippable items are very rare. Warlock is probably the only class with a spell like it(can't think of anything else right now at the top of my head).

It's not like it's something that would make a ton of difference anyway, it's just annoying having to create it in every arena match. But if it's currently blizzlike then leave it as it is.

**Comment by Klimpb** [comment]
Found some evidence here, I guess it is enough. Maybe..

http://www.arenajunkies.com/topic/23087-what-are-you-doing-before-a-match-starts/

"Summon imp.
Create healthstone while fire shielding.
Create weaker healthstone.
Summon void while trading to 2s partner.
Create healthstone.
Underwater Breathing.
Detect Lesser Invisibility.
Underwater Breaking.
Detect Lesser Invisibility.
Create Spellstone.
Summon Felhunter.

Oh, the joys of warlock. "
