### ISSUE TITLE
[Warlock] Improved health funnel

### ISSUE THREAD

**Issue by Mephisto22** [ccshiro/cc-buglist#925]
Demonology Tier 2 talent

The 20% increase only applies to tooltip amount and does not scale with healing power. At the current state it increases healing by 37, no matter whats your bonus healing. It should increase the amount healed by 20% but after bonus healing coefficient.

Proof - last post in this topic: http://www.arenajunkies.com/topic/39602-warlock-improved-health-funnel-for-my-lock-partner/

If it would be only +37, that would mean +370 hp over 10 seconds and that makes it really worthless

**Comment by ccshiro** [comment]
Looked at the Improved Health Funnel talent, and its effect is to increase the starting value of the spell by 20%. In which case I guess this is the correct behavior. Needs more evidence, as the spell data seems to contradict the report.

**Comment by robinsch** [comment]
Same problem with Elemental Weapons, the SPELLMOD_EFFECT2 should be applied after the 10% spelldamage scaling, but I think there is no general way checking if SPELLMOD_EFFECT_X should be applied before or after damage modifiers.

Also for Improved Righteous Fury.

**Comment by Mephisto22** [comment]
I found a possible counterproof for my report. Even though its from Wotlk...

http://forums.elitistjerks.com/topic/38579-warlock-bugs/page-9

Posted 23 January 2009 - 11:57 AM
"The improved health funnel talent appears to be bugged. The increase in healing provided by improved health funnel does not appear to match the tooltip. The damage reduction part of the talent appears to be working correctly, but the talented health funnel does not appear to provide 20% more healing. Healing provided without the talent was 1474, and with the talent it was 1577. According to the tooltip if my health funnel is 1474 unimproved I would expect it to be 1769 when improved (20%), if the phrase "Increases the amount of health transfered" means that it should increase healing by that amount. "

Posted 23 January 2009 - 12:41 PM
"It's not bugged - it works off the base healing, not the total healing. Base healing is 520, 20% of that is 104, which matches the increase you're seeing."

Apparently there are many worthless talents in WoW

**Comment by MorbidMike** [comment]
Improved Health Funnel used to work before Spell Damage or Healing back in WotLK. In some Felguard raiding guide (I can't find it any more though...) it was argued that the only reason to take this talent was the damage reduction, because the increase in healing was way too low to justify 2 talent points.
I really believe it worked the same way in TBC, essentially making the talent worthless, because I remember talenting this spell but noticing a very minor increase. I can't find any proof for it. I have been through all the Felguard raiding guides in WoWmb.net and ones that I found on Google but none mention this talent.

**Comment by Ghhlox** [comment]
Justification below, not useful proof:

The talent works to provide 20% of base healing probably because it's supposed to be useful while leveling, not in other scenarios (like the shadow priest talent that provides bonus spirit after slaying a mob). It isn't "useless", just limited. 20% is a large increase when you don't have any +sp or healing, and those numbers will reduce the time you spend eating/drinking while leveling considerably.

Source: leveled a demo warlock.

**Comment by Chulain** [comment]
https://youtu.be/S0XcCgyjClA?t=30

ticks for 541
shouldn't be possible unless it scales with healing power too

**Comment by Aasamath** [comment]
On the video he has a proc of this item http://www.wowhead.com/item=29370/icon-of-the-silver-crescent
the ticks of health funnel goes from 541 to 585 with a boost of 155 healing bonus. 
Using the info from this page http://wowwiki.wikia.com/wiki/Spell_power
I determined that the coefficient of heal gained by each tick of health funnel is 28.57% of the bonus healing statistic.
28.57% of 155 is 44.
541+44=585
So if this warlock had the improved health funnel. Then this talent does indeed only increase the base heal of the spell.
The fact these ticks seems high is most certainly due to the lock wearing some healer gear.
