### ISSUE TITLE
Spell : Mind Control

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#937]
Using Mind control on a npc make the priest and every other players who attacked that npc out of combat in less than a second. I don't know if it's the correct behavior, but this can leads to several situations like : 
-The priest gets ooc health regeneration
-Allowing the whole team to regen/stealth in the middle of the fight
-In a PvP situation, the priest can get zap

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/799 is related.

**Comment by YourNewfriend** [comment]
https://youtu.be/fnqgbiBYsds?t=1m56s it seemed to wipe his aggro table.  Priest couldn't MC him since he was tapped, but somebody managed to MC cap him  He went into evade.  People dropped combat after a while and were mounting.

https://github.com/ccshiro/cc-buglist/issues/28 was this not dealt with here?
